In [3]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
# Read the Excel file exactly as it is
raw_df = pd.read_excel("ATM_MASTER_2025.xlsx", header=None)

print("ATM Excel file loaded successfully!")
print("Number of rows:", raw_df.shape[0])
print("Number of columns:", raw_df.shape[1])

ATM Excel file loaded successfully!
Number of rows: 860
Number of columns: 33

In [6]:
# Display rows 0 to 20 without hiding any columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 30)

display(raw_df.iloc[0:20, :])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"ATM, Acceptance Infrastruc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category,Infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Card Payments and Cash Wit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Number - Outstanding (as o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Credit Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Debit Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ATMs & CRMs,NaN,PoS,Micro ATMs,Bharat QR Codes,UPI QR Codes,Credit Cards,Debit Cards,Card Payments Transactions,NaN,NaN,NaN,NaN,NaN,Cash Withdrawal,NaN,Card Payments Transactions,NaN,NaN,NaN,NaN,NaN,Cash Withdrawal,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,at PoS,NaN,Online (e-com),NaN,Others,NaN,At ATM,NaN,at PoS,NaN,Online (e-com),NaN,Others,NaN,ATM,NaN,PoS,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,On-site,Off-site,NaN,NaN,NaN,NaN,NaN,NaN,Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000),Volume (in actuals),Value (in Rs'000)
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
8,NaN,NaN,NaN,NaN,NaN,Scheduled Commercial Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,Public Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,1,BANK OF BARODA,Public Sector Banks,8504,2411,48728,44612,23532,2379429,2936005,87899577,6834186,13647802.709,3209685,17215566.729,0,0,12589,63510.312,3232534,7933859.70533,339817,2414933.40477,16,38.2,23893359,120380329.817,51,47.65
11,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,2,BANK OF INDIA,Public Sector Banks,5341,2895,18267,22334,0,1238013,72345,36546639,136483,547386.06676,47299,200080.79311,0,0,5436,29163.36734,2132758,4713490.35815,410611,948643.39569,0,0,15092018,63783083.665,260,256.46
12,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,3,BANK OF MAHARASHTRA,Public Sector Banks,2197,252,1368,3660,355014,932607,31206,13998450,44145,204863.47411,18261,102290.4897,0,0,775,3709.1,1077781,2278071.79288,213751,625654.08579,5862,65085.23398,6243739,29366539.4579,0,0
13,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,4,CANARA BANK,Public Sector Banks,8174,3794,78258,13180,0,3499846,998100,60036049,1074161,4244651.36738,473533,2830585.08072,0,0,99144,560312.4,5649610,16144774.83175,912430,3886619.66856,4643,79944.994,30643558,150843428.951,47,43.55499
14,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,5,CENTRAL BANK OF INDIA,Public Sector Banks,2857,1144,3324,2722,36032,1964679,0,28256084,0,0,0,0,0,0,0,0,1393749,3504843.55032,202024,721396.88168,0,0,8403997,39560576.22,2977,3014.244
15,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,6,INDIAN BANK,Public Sector Banks,4616,607,20924,13653,0,2855046,282701,33140182,222614,982200.72909,273579,1329668.69701,0,0,4389,33912.933,2919428,7135228.33404,517359,1253490.53,172,573.658,18994852,92238269.06962,1192,1189
16,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,7,INDIAN OVERSEAS BANK,Public Sector Banks,2765,733,0,9737,0,444312,67280,17767446,73644,234237.66004,24221,93679.5053,0,0,2609,13141.3789,2136718,4942472.49172,316016,824293.02672,0,0,11719990,50149331.18839,0,0
17,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,8,PUNJAB AND SIND BANK,Public Sector Banks,1019,27,941,1681,1087,168908,0,3478508,0,0,0,0,0,0,0,0,296623,809352.08986,83816,240866.38372,0,0,1391280,6995930.5,0,0
18,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,9,PUNJAB NATIONAL BANK,Public Sector Banks,7816,4188,34151,0,678151,903047,584549,41061227,353392,1575636.49677,258518,1567207.1538,2,119,6805,21490.1,3882226,10518438.76339,1141117,3126512.33744,0,0,24393039,127630387.21833,0,0
19,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,10,STATE BANK OF INDIA,Public Sector Banks,27254,37739,1511604,47060,982184,4702096,20481479,237986554,26503243,111736985.74757,47427768,178029832.9507,0,0,140771,587473.4192,29919640,75395547.77302,6486538,20120401.49991,778,10062.07534,157188702,847272075.18452,16029,14777.92968

In [7]:
df = raw_df.iloc[10:].copy()

df.columns = raw_df.iloc[2].values

df = df.reset_index(drop=True)

print("ATM data table created successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

ATM data table created successfully!
Rows: 850
Columns: 33

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category,Infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Card Payments and Cash Withdrawal Transactions during the month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,1,BANK OF BARODA,Public Sector Banks,8504,2411,48728,44612,23532,2379429,2936005,87899577,6834186,13647802.709,3209685,17215566.729,0,0,12589,63510.312,3232534,7933859.70533,339817,2414933.40477,16,38.2,23893359,120380329.817,51,47.65
1,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,2,BANK OF INDIA,Public Sector Banks,5341,2895,18267,22334,0,1238013,72345,36546639,136483,547386.06676,47299,200080.79311,0,0,5436,29163.36734,2132758,4713490.35815,410611,948643.39569,0,0,15092018,63783083.665,260,256.46
2,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,3,BANK OF MAHARASHTRA,Public Sector Banks,2197,252,1368,3660,355014,932607,31206,13998450,44145,204863.47411,18261,102290.4897,0,0,775,3709.1,1077781,2278071.79288,213751,625654.08579,5862,65085.23398,6243739,29366539.4579,0,0
3,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,4,CANARA BANK,Public Sector Banks,8174,3794,78258,13180,0,3499846,998100,60036049,1074161,4244651.36738,473533,2830585.08072,0,0,99144,560312.4,5649610,16144774.83175,912430,3886619.66856,4643,79944.994,30643558,150843428.951,47,43.55499
4,2025,January,Q1,ATMJANUARY2025B1FB692B5934...,5,CENTRAL BANK OF INDIA,Public Sector Banks,2857,1144,3324,2722,36032,1964679,0,28256084,0,0,0,0,0,0,0,0,1393749,3504843.55032,202024,721396.88168,0,0,8403997,39560576.22,2977,3014.244

In [8]:
# Show the header information from rows 2 to 7
header_rows = raw_df.iloc[2:8, :]

# Display all 33 columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 40)

display(header_rows.T)

,2,3,4,5,6,7
0,Year,NaN,NaN,NaN,NaN,NaN
1,Month,NaN,NaN,NaN,NaN,NaN
2,Quarter,NaN,NaN,NaN,NaN,NaN
3,Source File,NaN,NaN,NaN,NaN,NaN
4,Sr. No.,NaN,NaN,NaN,NaN,NaN
5,Bank Name,NaN,NaN,NaN,NaN,NaN
6,Bank Category,NaN,NaN,NaN,NaN,NaN
7,Infrastructure,Number - Outstanding (as on month end),ATMs & CRMs,NaN,On-site,1
8,NaN,NaN,NaN,NaN,Off-site,2
9,NaN,NaN,PoS,NaN,NaN,3
10,NaN,NaN,Micro ATMs,NaN,NaN,4
11,NaN,NaN,Bharat QR Codes,NaN,NaN,5
12,NaN,NaN,UPI QR Codes,NaN,NaN,6
13,NaN,NaN,Credit Cards,NaN,NaN,7
14,NaN,NaN,Debit Cards,NaN,NaN,8
15,Card Payments and Cash Withdrawal Tr...,Credit Card,Card Payments Transactions,at PoS,Volume (in actuals),9
16,NaN,NaN,NaN,NaN,Value (in Rs'000),10
17,NaN,NaN,NaN,Online (e-com),Volume (in actuals),11
18,NaN,NaN,NaN,NaN,Value (in Rs'000),12
19,NaN,NaN,NaN,Others,Volume (in actuals),13
20,NaN,NaN,NaN,NaN,Value (in Rs'000),14
21,NaN,NaN,Cash Withdrawal,At ATM,Volume (in actuals),15
22,NaN,NaN,NaN,NaN,Value (in Rs'000),16
23,NaN,Debit Card,Card Payments Transactions,at PoS,Volume (in actuals),17
24,NaN,NaN,NaN,NaN,Value (in Rs'000),18
25,NaN,NaN,NaN,Online (e-com),Volume (in actuals),19
26,NaN,NaN,NaN,NaN,Value (in Rs'000),20
27,NaN,NaN,NaN,Others,Volume (in actuals),21
28,NaN,NaN,NaN,NaN,Value (in Rs'000),22
29,NaN,NaN,Cash Withdrawal,ATM,Volume (in actuals),23
30,NaN,NaN,NaN,NaN,Value (in Rs'000),24
31,NaN,NaN,NaN,PoS,Volume (in actuals),25
32,NaN,NaN,NaN,NaN,Value (in Rs'000),26

In [9]:
# Create the correct 33 column names
# based on the original multi-level headers in the ATM Excel file

column_names = [
    "Year",
    "Month",
    "Quarter",
    "Source File",
    "Sr. No.",
    "Bank Name",
    "Bank Category",

    "Infrastructure - ATMs & CRMs - On-site",
    "Infrastructure - ATMs & CRMs - Off-site",
    "Infrastructure - PoS",
    "Infrastructure - Micro ATMs",
    "Infrastructure - Bharat QR Codes",
    "Infrastructure - UPI QR Codes",
    "Infrastructure - Credit Cards",
    "Infrastructure - Debit Cards",

    "Credit Card - Card Payments - PoS - Volume (in actuals)",
    "Credit Card - Card Payments - PoS - Value (in Rs'000)",
    "Credit Card - Card Payments - Online (e-com) - Volume (in actuals)",
    "Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)",
    "Credit Card - Card Payments - Others - Volume (in actuals)",
    "Credit Card - Card Payments - Others - Value (in Rs'000)",
    "Credit Card - Cash Withdrawal - ATM - Volume (in actuals)",
    "Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)",

    "Debit Card - Card Payments - PoS - Volume (in actuals)",
    "Debit Card - Card Payments - PoS - Value (in Rs'000)",
    "Debit Card - Card Payments - Online (e-com) - Volume (in actuals)",
    "Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)",
    "Debit Card - Card Payments - Others - Volume (in actuals)",
    "Debit Card - Card Payments - Others - Value (in Rs'000)",
    "Debit Card - Cash Withdrawal - ATM - Volume (in actuals)",
    "Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)",
    "Debit Card - Cash Withdrawal - PoS - Volume (in actuals)",
    "Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)"
]

# Safety check
print("Number of columns in dataset:", df.shape[1])
print("Number of new column names:", len(column_names))

if df.shape[1] == len(column_names):
    df.columns = column_names
    print("\nColumn names assigned successfully!")
else:
    print("\nERROR: Column count does not match.")

Number of columns in dataset: 33
Number of new column names: 33

Column names assigned successfully!

In [10]:
# Check that all 33 columns are present and unique

print("Total columns:", len(df.columns))
print("Unique columns:", df.columns.nunique())

print("\nAll column names:")
for i, column in enumerate(df.columns, start=1):
    print(i, ":", column)

Total columns: 33
Unique columns: 33

All column names:
1 : Year
2 : Month
3 : Quarter
4 : Source File
5 : Sr. No.
6 : Bank Name
7 : Bank Category
8 : Infrastructure - ATMs & CRMs - On-site
9 : Infrastructure - ATMs & CRMs - Off-site
10 : Infrastructure - PoS
11 : Infrastructure - Micro ATMs
12 : Infrastructure - Bharat QR Codes
13 : Infrastructure - UPI QR Codes
14 : Infrastructure - Credit Cards
15 : Infrastructure - Debit Cards
16 : Credit Card - Card Payments - PoS - Volume (in actuals)
17 : Credit Card - Card Payments - PoS - Value (in Rs'000)
18 : Credit Card - Card Payments - Online (e-com) - Volume (in actuals)
19 : Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)
20 : Credit Card - Card Payments - Others - Volume (in actuals)
21 : Credit Card - Card Payments - Others - Value (in Rs'000)
22 : Credit Card - Cash Withdrawal - ATM - Volume (in actuals)
23 : Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)
24 : Debit Card - Card Payments - PoS - Volume (in actuals)
25 : Debit Card - Card Payments - PoS - Value (in Rs'000)
26 : Debit Card - Card Payments - Online (e-com) - Volume (in actuals)
27 : Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)
28 : Debit Card - Card Payments - Others - Volume (in actuals)
29 : Debit Card - Card Payments - Others - Value (in Rs'000)
30 : Debit Card - Cash Withdrawal - ATM - Volume (in actuals)
31 : Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)
32 : Debit Card - Cash Withdrawal - PoS - Volume (in actuals)
33 : Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)

In [11]:
# Check missing values in every column

missing_values = df.isnull().sum()

missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": missing_values.values,
    "Missing Percentage": (missing_values.values / len(df) * 100).round(2)
})

display(missing_report)

,Column,Missing Values,Missing Percentage
0,Year,70,8.24
1,Month,70,8.24
2,Quarter,70,8.24
3,Source File,70,8.24
4,Sr. No.,82,9.65
5,Bank Name,0,0.00
6,Bank Category,82,9.65
7,Infrastructure - ATMs & CRMs - On-site,70,8.24
8,Infrastructure - ATMs & CRMs - Off-site,70,8.24
9,Infrastructure - PoS,70,8.24
10,Infrastructure - Micro ATMs,70,8.24
11,Infrastructure - Bharat QR Codes,70,8.24
12,Infrastructure - UPI QR Codes,70,8.24
13,Infrastructure - Credit Cards,70,8.24
14,Infrastructure - Debit Cards,70,8.24
15,Credit Card - Card Payments - PoS - ...,70,8.24
16,Credit Card - Card Payments - PoS - ...,70,8.24
17,Credit Card - Card Payments - Online...,70,8.24
18,Credit Card - Card Payments - Online...,70,8.24
19,Credit Card - Card Payments - Others...,70,8.24
20,Credit Card - Card Payments - Others...,70,8.24
21,Credit Card - Cash Withdrawal - ATM ...,70,8.24
22,Credit Card - Cash Withdrawal - ATM ...,70,8.24
23,Debit Card - Card Payments - PoS - V...,70,8.24
24,Debit Card - Card Payments - PoS - V...,70,8.24
25,Debit Card - Card Payments - Online ...,70,8.24
26,Debit Card - Card Payments - Online ...,70,8.24
27,Debit Card - Card Payments - Others ...,70,8.24
28,Debit Card - Card Payments - Others ...,70,8.24
29,Debit Card - Cash Withdrawal - ATM -...,70,8.24
30,Debit Card - Cash Withdrawal - ATM -...,70,8.24
31,Debit Card - Cash Withdrawal - PoS -...,70,8.24
32,Debit Card - Cash Withdrawal - PoS -...,70,8.24

In [12]:
# Find rows where Year is missing
# We are NOT deleting anything yet

missing_year_rows = df[df["Year"].isna()]

print("Number of rows where Year is missing:", len(missing_year_rows))

display(missing_year_rows)

Number of rows where Year is missing: 70

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
12,NaN,NaN,NaN,NaN,NaN,Private Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,Foreign Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,Payment Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,Small Finance Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,Scheduled Commercial Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,NaN,NaN,NaN,NaN,NaN,Public Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
793,NaN,NaN,NaN,NaN,NaN,Private Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,NaN,NaN,NaN,NaN,NaN,Foreign Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,NaN,NaN,NaN,NaN,NaN,Payment Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,NaN,NaN,NaN,NaN,NaN,Small Finance Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Check whether these missing-Year rows contain actual bank names

check_rows = df[
    df["Year"].isna() &
    df["Bank Name"].notna()
]

print("Rows with missing Year but Bank Name present:", len(check_rows))

display(check_rows)

Rows with missing Year but Bank Name present: 70

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
12,NaN,NaN,NaN,NaN,NaN,Private Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,Foreign Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,Payment Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,Small Finance Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,Scheduled Commercial Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
780,NaN,NaN,NaN,NaN,NaN,Public Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
793,NaN,NaN,NaN,NaN,NaN,Private Sector Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,NaN,NaN,NaN,NaN,NaN,Foreign Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,NaN,NaN,NaN,NaN,NaN,Payment Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,NaN,NaN,NaN,NaN,NaN,Small Finance Banks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Identify rows that are category/section rows
# These rows have a Bank Name but no Year

category_rows = df[
    df["Year"].isna() &
    df["Bank Name"].notna()
].copy()

print("Number of category rows:", len(category_rows))

print("\nCategory names found:")
print(category_rows["Bank Name"].value_counts())

Number of category rows: 70

Category names found:
Bank Name
Private Sector Banks          12
Foreign Banks                 12
Payment Banks                 12
Small Finance Banks           12
Scheduled Commercial Banks    11
Public Sector Banks           11
Name: count, dtype: int64

In [15]:
# Identify actual bank-level records
# Actual records have a Year value

bank_records = df[df["Year"].notna()].copy()

print("Total rows in dataset:", len(df))
print("Category/section rows:", len(category_rows))
print("Actual bank records:", len(bank_records))

Total rows in dataset: 850
Category/section rows: 70
Actual bank records: 780

In [16]:
# Display the first 10 actual bank records

display(bank_records.head(10))

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
0,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,1,BANK OF BARODA,Public Sector Banks,8504,2411,48728,44612,23532,2379429,2936005,87899577,6834186,13647802.709,3209685,17215566.729,0,0,12589,63510.312,3232534,7933859.70533,339817,2414933.40477,16,38.2,23893359,120380329.817,51,47.65
1,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,2,BANK OF INDIA,Public Sector Banks,5341,2895,18267,22334,0,1238013,72345,36546639,136483,547386.06676,47299,200080.79311,0,0,5436,29163.36734,2132758,4713490.35815,410611,948643.39569,0,0,15092018,63783083.665,260,256.46
2,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,3,BANK OF MAHARASHTRA,Public Sector Banks,2197,252,1368,3660,355014,932607,31206,13998450,44145,204863.47411,18261,102290.4897,0,0,775,3709.1,1077781,2278071.79288,213751,625654.08579,5862,65085.23398,6243739,29366539.4579,0,0
3,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,4,CANARA BANK,Public Sector Banks,8174,3794,78258,13180,0,3499846,998100,60036049,1074161,4244651.36738,473533,2830585.08072,0,0,99144,560312.4,5649610,16144774.83175,912430,3886619.66856,4643,79944.994,30643558,150843428.951,47,43.55499
4,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,5,CENTRAL BANK OF INDIA,Public Sector Banks,2857,1144,3324,2722,36032,1964679,0,28256084,0,0,0,0,0,0,0,0,1393749,3504843.55032,202024,721396.88168,0,0,8403997,39560576.22,2977,3014.244
5,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,6,INDIAN BANK,Public Sector Banks,4616,607,20924,13653,0,2855046,282701,33140182,222614,982200.72909,273579,1329668.69701,0,0,4389,33912.933,2919428,7135228.33404,517359,1253490.53,172,573.658,18994852,92238269.06962,1192,1189
6,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,7,INDIAN OVERSEAS BANK,Public Sector Banks,2765,733,0,9737,0,444312,67280,17767446,73644,234237.66004,24221,93679.5053,0,0,2609,13141.3789,2136718,4942472.49172,316016,824293.02672,0,0,11719990,50149331.18839,0,0
7,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,8,PUNJAB AND SIND BANK,Public Sector Banks,1019,27,941,1681,1087,168908,0,3478508,0,0,0,0,0,0,0,0,296623,809352.08986,83816,240866.38372,0,0,1391280,6995930.5,0,0
8,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,9,PUNJAB NATIONAL BANK,Public Sector Banks,7816,4188,34151,0,678151,903047,584549,41061227,353392,1575636.49677,258518,1567207.1538,2,119,6805,21490.1,3882226,10518438.76339,1141117,3126512.33744,0,0,24393039,127630387.21833,0,0
9,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,10,STATE BANK OF INDIA,Public Sector Banks,27254,37739,1511604,47060,982184,4702096,20481479,237986554,26503243,111736985.74757,47427768,178029832.9507,0,0,140771,587473.4192,29919640,75395547.77302,6486538,20120401.49991,778,10062.07534,157188702,847272075.18452,16029,14777.92968

In [17]:
# Check how many records belong to each month

print(bank_records["Month"].value_counts())

Month
January      65
February     65
March        65
April        65
May          65
June         65
July         65
August       65
September    65
October      65
November     65
December     65
Name: count, dtype: int64

In [18]:
# Count bank records for each month
# This checks whether the number of banks is consistent every month

monthly_bank_counts = (
    bank_records
    .groupby("Month")["Bank Name"]
    .count()
    .sort_index()
)

print("Bank records by month:")
print(monthly_bank_counts)

Bank records by month:
Month
April        65
August       65
December     65
February     65
January      65
July         65
June         65
March        65
May          65
November     65
October      65
September    65
Name: Bank Name, dtype: int64

In [19]:
# Count unique bank names in the complete 2025 dataset

unique_banks = bank_records["Bank Name"].nunique()

print("Number of unique banks in 2025:", unique_banks)

Number of unique banks in 2025: 66

In [20]:
# List all unique bank names
unique_bank_names = sorted(bank_records["Bank Name"].dropna().unique())

print("Total unique bank names:", len(unique_bank_names))

for i, bank in enumerate(unique_bank_names, start=1):
    print(i, ":", bank)

Total unique bank names: 66
1 : AIRTEL PAYMENTS BANK
2 : AMERICAN EXPRESS BANKING CORPORATION
3 : AU SMALL FINANCE BANK LTD
4 : AXIS BANK LTD
5 : BANDHAN BANK LTD
6 : BANK OF AMERICA
7 : BANK OF BAHRAIN & KUWAIT B.S.C.
8 : BANK OF BARODA
9 : BANK OF INDIA
10 : BANK OF MAHARASHTRA
11 : BARCLAYS BANK PLC
12 : CANARA BANK
13 : CAPITAL SMALL FINANCE BANK LTD
14 : CENTRAL BANK OF INDIA
15 : CITI BANK
16 : CITY UNION BANK LTD.
17 : CSB BANK LTD.
18 : DBS INDIA BANK LTD
19 : DCB BANK LTD
20 : DEUTSCHE BANK LTD
21 : DHANALAXMI BANK LTD
22 : DOHA BANK Q.P.S.C.
23 : EQUITAS SMALL FINANCE BANK LTD
24 : ESAF SMALL FINANCE BANK LTD
25 : FEDERAL BANK LTD
26 : FINO PAYMENTS BANK
27 : HDFC BANK LTD
28 : HSBC LTD
29 : ICICI BANK LTD
30 : IDBI BANK LTD
31 : IDFC FIRST BANK LTD
32 : INDIA POST PAYMENTS BANK
33 : INDIAN BANK
34 : INDIAN OVERSEAS BANK
35 : INDUSIND BANK LTD
36 : JAMMU AND KASHMIR BANK LTD
37 : JANA SMALL FINANCE BANK LTD
38 : JIO PAYMENTS BANK
39 : KARNATAKA BANK LTD
40 : KARUR VYSYA BANK LTD
41 : KEB HANA BANK
42 : KOOKMIN BANK
43 : KOTAK MAHINDRA BANK LTD
44 : NAINITAL BANK LTD
45 : NORTH EAST SMALL FINANCE BANK LTD
46 : NSDL PAYMENTS BANK
47 : PAYTM PAYMENTS BANK
48 : PUNJAB AND SIND BANK
49 : PUNJAB NATIONAL BANK
50 : RBL BANK LTD
51 : SBM BANK INDIA LTD
52 : SHIVALIK SMALL FINANCE BANK LTD
53 : SLICE SMALL FINANCE BANK LTD
54 : SOUTH INDIAN BANK
55 : STANDARD CHARTERED BANK LTD
56 : STATE BANK OF INDIA
57 : SURYODAY SMALL FINANCE BANK LTD
58 : TAMILNAD MERCANTILE BANK LTD
59 : Total
60 : UCO BANK
61 : UJJIVAN SMALL FINANCE BANK LTD
62 : UNION BANK OF INDIA
63 : UNITY SMALL FINANCE BANK LTD
64 : UTKARSH SMALL FINANCE BANK LTD
65 : WOORI BANK
66 : YES BANK LTD

In [21]:
# Count the number of months in which each bank appears

bank_month_counts = (
    bank_records
    .groupby("Bank Name")["Month"]
    .nunique()
    .sort_values()
)

display(bank_month_counts)

Bank Name
NORTH EAST SMALL FINANCE BANK LTD        4
SLICE SMALL FINANCE BANK LTD             8
AIRTEL PAYMENTS BANK                    12
AMERICAN EXPRESS BANKING CORPORATION    12
BANDHAN BANK LTD                        12
                                        ..
UNION BANK OF INDIA                     12
UNITY SMALL FINANCE BANK LTD            12
UTKARSH SMALL FINANCE BANK LTD          12
WOORI BANK                              12
YES BANK LTD                            12
Name: Month, Length: 66, dtype: int64

In [22]:
# Check exactly which months are present for the two banks

banks_to_check = [
    "NORTH EAST SMALL FINANCE BANK LTD",
    "SLICE SMALL FINANCE BANK LTD"
]

for bank in banks_to_check:
    print("\n", bank)
    
    months_present = (
        bank_records.loc[
            bank_records["Bank Name"] == bank,
            "Month"
        ]
        .unique()
    )
    
    print("Months present:", list(months_present))

 NORTH EAST SMALL FINANCE BANK LTD
Months present: ['January', 'February', 'March', 'April']

 SLICE SMALL FINANCE BANK LTD
Months present: ['May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

In [23]:
# Check the bank category associated with these two banks

display(
    bank_records[
        bank_records["Bank Name"].isin(banks_to_check)
    ][
        ["Year", "Month", "Bank Name", "Bank Category"]
    ].sort_values(["Bank Name", "Month"])
)

     Year      Month                          Bank Name        Bank Category
275  2025      April  NORTH EAST SMALL FINANCE BANK LTD  Small Finance Banks
133  2025   February  NORTH EAST SMALL FINANCE BANK LTD  Small Finance Banks
62   2025    January  NORTH EAST SMALL FINANCE BANK LTD  Small Finance Banks
204  2025      March  NORTH EAST SMALL FINANCE BANK LTD  Small Finance Banks
559  2025     August       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
843  2025   December       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
488  2025       July       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
417  2025       June       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
346  2025        May       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
772  2025   November       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
701  2025    October       SLICE SMALL FINANCE BANK LTD  Small Finance Banks
630  2025  September       SLICE SMALL FINANCE BANK LTD  Small Finance Banks

In [24]:
# Check for duplicate bank-month records

duplicate_records = bank_records[
    bank_records.duplicated(
        subset=["Year", "Month", "Bank Name"],
        keep=False
    )
].sort_values(["Year", "Month", "Bank Name"])

print("Number of duplicate rows:", len(duplicate_records))

display(duplicate_records)

Number of duplicate rows: 0

Empty DataFrame
Columns: [Year, Month, Quarter, Source File, Sr. No., Bank Name, Bank Category, Infrastructure - ATMs & CRMs - On-site, Infrastructure - ATMs & CRMs - Off-site, Infrastructure - PoS, Infrastructure - Micro ATMs, Infrastructure - Bharat QR Codes, Infrastructure - UPI QR Codes, Infrastructure - Credit Cards, Infrastructure - Debit Cards, Credit Card - Card Payments - PoS - Volume (in actuals), Credit Card - Card Payments - PoS - Value (in Rs'000), Credit Card - Card Payments - Online (e-com) - Volume (in actuals), Credit Card - Card Payments - Online (e-com) - Value (in Rs'000), Credit Card - Card Payments - Others - Volume (in actuals), Credit Card - Card Payments - Others - Value (in Rs'000), Credit Card - Cash Withdrawal - ATM - Volume (in actuals), Credit Card - Cash Withdrawal - ATM - Value (in Rs'000), Debit Card - Card Payments - PoS - Volume (in actuals), Debit Card - Card Payments - PoS - Value (in Rs'000), Debit Card - Card Payments - Online (e-com) - Volume (in actuals), Debit Card - Card Payments - Online (e-com) - Value (in Rs'000), Debit Card - Card Payments - Others - Volume (in actuals), Debit Card - Card Payments - Others - Value (in Rs'000), Debit Card - Cash Withdrawal - ATM - Volume (in actuals), Debit Card - Cash Withdrawal - ATM - Value (in Rs'000), Debit Card - Cash Withdrawal - PoS - Volume (in actuals), Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)]
Index: []

In [25]:
# Check uniqueness of Year + Month + Bank Name

unique_keys = bank_records[
    ["Year", "Month", "Bank Name"]
].drop_duplicates()

print("Total bank records:", len(bank_records))
print("Unique Year-Month-Bank combinations:", len(unique_keys))

if len(bank_records) == len(unique_keys):
    print("✓ Every bank has only one record per month.")
else:
    print("⚠ Duplicate Year-Month-Bank combinations found.")

Total bank records: 780
Unique Year-Month-Bank combinations: 780
✓ Every bank has only one record per month.

In [26]:
# Check the data types of all columns

print("Data types of the ATM dataset:\n")
print(bank_records.dtypes)

Data types of the ATM dataset:

Year                                                                  object
Month                                                                    str
Quarter                                                                  str
Source File                                                              str
Sr. No.                                                               object
Bank Name                                                                str
Bank Category                                                            str
Infrastructure - ATMs & CRMs - On-site                                object
Infrastructure - ATMs & CRMs - Off-site                               object
Infrastructure - PoS                                                  object
Infrastructure - Micro ATMs                                           object
Infrastructure - Bharat QR Codes                                      object
Infrastructure - UPI QR Codes                                         object
Infrastructure - Credit Cards                                         object
Infrastructure - Debit Cards                                          object
Credit Card - Card Payments - PoS - Volume (in actuals)               object
Credit Card - Card Payments - PoS - Value (in Rs'000)                 object
Credit Card - Card Payments - Online (e-com) - Volume (in actuals)    object
Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)      object
Credit Card - Card Payments - Others - Volume (in actuals)            object
Credit Card - Card Payments - Others - Value (in Rs'000)              object
Credit Card - Cash Withdrawal - ATM - Volume (in actuals)             object
Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)               object
Debit Card - Card Payments - PoS - Volume (in actuals)                object
Debit Card - Card Payments - PoS - Value (in Rs'000)                  object
Debit Card - Card Payments - Online (e-com) - Volume (in actuals)     object
Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)       object
Debit Card - Card Payments - Others - Volume (in actuals)             object
Debit Card - Card Payments - Others - Value (in Rs'000)               object
Debit Card - Cash Withdrawal - ATM - Volume (in actuals)              object
Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)                object
Debit Card - Cash Withdrawal - PoS - Volume (in actuals)              object
Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)                object
dtype: object

In [27]:
# Check basic information about the dataset

bank_records.info()

<class 'pandas.DataFrame'>
Index: 780 entries, 0 to 849
Data columns (total 33 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Year                                                                780 non-null    object
 1   Month                                                               780 non-null    str
 2   Quarter                                                             780 non-null    str
 3   Source File                                                         780 non-null    str
 4   Sr. No.                                                             768 non-null    object
 5   Bank Name                                                           780 non-null    str
 6   Bank Category                                                       768 non-null    str
 7   Infrastructure - ATMs & CRMs - On-site                              780 non-null    object
 8   Infrastructure - ATMs & CRMs - Off-site                             780 non-null    object
 9   Infrastructure - PoS                                                780 non-null    object
 10  Infrastructure - Micro ATMs                                         780 non-null    object
 11  Infrastructure - Bharat QR Codes                                    780 non-null    object
 12  Infrastructure - UPI QR Codes                                       780 non-null    object
 13  Infrastructure - Credit Cards                                       780 non-null    object
 14  Infrastructure - Debit Cards                                        780 non-null    object
 15  Credit Card - Card Payments - PoS - Volume (in actuals)             780 non-null    object
 16  Credit Card - Card Payments - PoS - Value (in Rs'000)               780 non-null    object
 17  Credit Card - Card Payments - Online (e-com) - Volume (in actuals)  780 non-null    object
 18  Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)    780 non-null    object
 19  Credit Card - Card Payments - Others - Volume (in actuals)          780 non-null    object
 20  Credit Card - Card Payments - Others - Value (in Rs'000)            780 non-null    object
 21  Credit Card - Cash Withdrawal - ATM - Volume (in actuals)           780 non-null    object
 22  Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)             780 non-null    object
 23  Debit Card - Card Payments - PoS - Volume (in actuals)              780 non-null    object
 24  Debit Card - Card Payments - PoS - Value (in Rs'000)                780 non-null    object
 25  Debit Card - Card Payments - Online (e-com) - Volume (in actuals)   780 non-null    object
 26  Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)     780 non-null    object
 27  Debit Card - Card Payments - Others - Volume (in actuals)           780 non-null    object
 28  Debit Card - Card Payments - Others - Value (in Rs'000)             780 non-null    object
 29  Debit Card - Cash Withdrawal - ATM - Volume (in actuals)            780 non-null    object
 30  Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)              780 non-null    object
 31  Debit Card - Cash Withdrawal - PoS - Volume (in actuals)            780 non-null    object
 32  Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)              780 non-null    object
dtypes: object(28), str(5)
memory usage: 279.4+ KB

In [28]:
# Check rows where Sr. No. is missing

sr_missing = bank_records[bank_records["Sr. No."].isna()]

print("Rows with missing Sr. No.:", len(sr_missing))

display(
    sr_missing[
        ["Year", "Month", "Quarter", "Source File",
         "Sr. No.", "Bank Name", "Bank Category"]
    ]
)

Rows with missing Sr. No.: 12

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category
68,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,NaN,Total,NaN
139,2025,February,Q1,ATMFEBRUARY20257E29C21AB6AD4CDFAB6C0...,NaN,Total,NaN
210,2025,March,Q1,ATMMARCH202530FC885C0DD7498F9F94FA60...,NaN,Total,NaN
281,2025,April,Q2,ATMAPRIL25A53BB941D2DD420396BFADA671...,NaN,Total,NaN
352,2025,May,Q2,ATMMAY2306202583416DC93AF04D958DBA2E...,NaN,Total,NaN
423,2025,June,Q2,ATMJUNE2025599A531681334E06B9CF942D0...,NaN,Total,NaN
494,2025,July,Q3,ATMJULY20259DD80A92103A477A88BEDB6A5...,NaN,Total,NaN
565,2025,August,Q3,ATMAUGUST2025FE83AB680ECC4DE48661FF1...,NaN,Total,NaN
636,2025,September,Q3,ATMSEPTEMBER202541852720BAFD4A8A90E3...,NaN,Total,NaN
707,2025,October,Q4,ATMOCTOBER202555BCB90087E940BD92477C...,NaN,Total,NaN
778,2025,November,Q4,ATMOCTOBER20251BB945D4B48243919FC752...,NaN,Total,NaN
849,2025,December,Q4,ATM122025010824B80F314664BFB1DA8F179...,NaN,Total,NaN

In [29]:
# Check rows where Bank Category is missing

category_missing = bank_records[bank_records["Bank Category"].isna()]

print("Rows with missing Bank Category:", len(category_missing))

display(
    category_missing[
        ["Year", "Month", "Bank Name", "Bank Category"]
    ]
)

Rows with missing Bank Category: 12

     Year      Month Bank Name Bank Category
68   2025    January     Total           NaN
139  2025   February     Total           NaN
210  2025      March     Total           NaN
281  2025      April     Total           NaN
352  2025        May     Total           NaN
423  2025       June     Total           NaN
494  2025       July     Total           NaN
565  2025     August     Total           NaN
636  2025  September     Total           NaN
707  2025    October     Total           NaN
778  2025   November     Total           NaN
849  2025   December     Total           NaN

In [30]:
# Identify the 12 official monthly Total rows

monthly_total_records = bank_records[
    bank_records["Bank Name"].astype(str).str.strip().eq("Total")
].copy()

print("Number of monthly Total rows:", len(monthly_total_records))

display(
    monthly_total_records[
        ["Year", "Month", "Quarter", "Source File",
         "Sr. No.", "Bank Name", "Bank Category"]
    ]
)

Number of monthly Total rows: 12

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category
68,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,NaN,Total,NaN
139,2025,February,Q1,ATMFEBRUARY20257E29C21AB6AD4CDFAB6C0...,NaN,Total,NaN
210,2025,March,Q1,ATMMARCH202530FC885C0DD7498F9F94FA60...,NaN,Total,NaN
281,2025,April,Q2,ATMAPRIL25A53BB941D2DD420396BFADA671...,NaN,Total,NaN
352,2025,May,Q2,ATMMAY2306202583416DC93AF04D958DBA2E...,NaN,Total,NaN
423,2025,June,Q2,ATMJUNE2025599A531681334E06B9CF942D0...,NaN,Total,NaN
494,2025,July,Q3,ATMJULY20259DD80A92103A477A88BEDB6A5...,NaN,Total,NaN
565,2025,August,Q3,ATMAUGUST2025FE83AB680ECC4DE48661FF1...,NaN,Total,NaN
636,2025,September,Q3,ATMSEPTEMBER202541852720BAFD4A8A90E3...,NaN,Total,NaN
707,2025,October,Q4,ATMOCTOBER202555BCB90087E940BD92477C...,NaN,Total,NaN
778,2025,November,Q4,ATMOCTOBER20251BB945D4B48243919FC752...,NaN,Total,NaN
849,2025,December,Q4,ATM122025010824B80F314664BFB1DA8F179...,NaN,Total,NaN

In [31]:
# Create a dataset containing only individual bank records
# Total rows are excluded from this analytical dataset

bank_data = bank_records[
    ~bank_records["Bank Name"].astype(str).str.strip().eq("Total")
].copy()

print("Actual bank-level records:", len(bank_data))
print("Columns:", len(bank_data.columns))

display(bank_data.head())

Actual bank-level records: 768
Columns: 33

,Year,Month,Quarter,Source File,Sr. No.,Bank Name,Bank Category,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
0,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,1,BANK OF BARODA,Public Sector Banks,8504,2411,48728,44612,23532,2379429,2936005,87899577,6834186,13647802.709,3209685,17215566.729,0,0,12589,63510.312,3232534,7933859.70533,339817,2414933.40477,16,38.2,23893359,120380329.817,51,47.65
1,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,2,BANK OF INDIA,Public Sector Banks,5341,2895,18267,22334,0,1238013,72345,36546639,136483,547386.06676,47299,200080.79311,0,0,5436,29163.36734,2132758,4713490.35815,410611,948643.39569,0,0,15092018,63783083.665,260,256.46
2,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,3,BANK OF MAHARASHTRA,Public Sector Banks,2197,252,1368,3660,355014,932607,31206,13998450,44145,204863.47411,18261,102290.4897,0,0,775,3709.1,1077781,2278071.79288,213751,625654.08579,5862,65085.23398,6243739,29366539.4579,0,0
3,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,4,CANARA BANK,Public Sector Banks,8174,3794,78258,13180,0,3499846,998100,60036049,1074161,4244651.36738,473533,2830585.08072,0,0,99144,560312.4,5649610,16144774.83175,912430,3886619.66856,4643,79944.994,30643558,150843428.951,47,43.55499
4,2025,January,Q1,ATMJANUARY2025B1FB692B5934404B883922...,5,CENTRAL BANK OF INDIA,Public Sector Banks,2857,1144,3324,2722,36032,1964679,0,28256084,0,0,0,0,0,0,0,0,1393749,3504843.55032,202024,721396.88168,0,0,8403997,39560576.22,2977,3014.244

In [34]:
# Columns that should contain numerical data
numeric_columns = list(bank_data.columns[7:])

# Check for non-numeric values in each numerical column
for column in numeric_columns:
    
    # Try converting to numeric without changing the original data
    converted = pd.to_numeric(bank_data[column], errors="coerce")
    
    # Find values that could not be converted
    non_numeric = bank_data.loc[
        converted.isna() & bank_data[column].notna(),
        column
    ].unique()
    
    if len(non_numeric) > 0:
        print("\nCOLUMN:", column)
        print("Non-numeric values found:", non_numeric[:20])

In [35]:
# Check missing values in the 768 bank records

missing_summary = pd.DataFrame({
    "Missing Values": bank_data.isna().sum(),
    "Missing Percentage": (bank_data.isna().sum() / len(bank_data) * 100).round(2)
})

display(missing_summary)

                                          Missing Values  Missing Percentage
Year                                                   0                 0.0
Month                                                  0                 0.0
Quarter                                                0                 0.0
Source File                                            0                 0.0
Sr. No.                                                0                 0.0
Bank Name                                              0                 0.0
Bank Category                                          0                 0.0
Infrastructure - ATMs & CRMs - On-site                 0                 0.0
Infrastructure - ATMs & CRMs - Off-site                0                 0.0
Infrastructure - PoS                                   0                 0.0
Infrastructure - Micro ATMs                            0                 0.0
Infrastructure - Bharat QR Codes                       0                 0.0
Infrastructure - UPI QR Codes                          0                 0.0
Infrastructure - Credit Cards                          0                 0.0
Infrastructure - Debit Cards                           0                 0.0
Credit Card - Card Payments - PoS - V...               0                 0.0
Credit Card - Card Payments - PoS - V...               0                 0.0
Credit Card - Card Payments - Online ...               0                 0.0
Credit Card - Card Payments - Online ...               0                 0.0
Credit Card - Card Payments - Others ...               0                 0.0
Credit Card - Card Payments - Others ...               0                 0.0
Credit Card - Cash Withdrawal - ATM -...               0                 0.0
Credit Card - Cash Withdrawal - ATM -...               0                 0.0
Debit Card - Card Payments - PoS - Vo...               0                 0.0
Debit Card - Card Payments - PoS - Va...               0                 0.0
Debit Card - Card Payments - Online (...               0                 0.0
Debit Card - Card Payments - Online (...               0                 0.0
Debit Card - Card Payments - Others -...               0                 0.0
Debit Card - Card Payments - Others -...               0                 0.0
Debit Card - Cash Withdrawal - ATM - ...               0                 0.0
Debit Card - Cash Withdrawal - ATM - ...               0                 0.0
Debit Card - Cash Withdrawal - PoS - ...               0                 0.0
Debit Card - Cash Withdrawal - PoS - ...               0                 0.0

In [36]:
# Create a copy for the cleaned dataset

cleaned_atm = bank_data.copy()

# Columns that should be numeric
numeric_columns = cleaned_atm.columns[7:]

# Convert all numerical columns to numeric
for column in numeric_columns:
    cleaned_atm[column] = pd.to_numeric(
        cleaned_atm[column],
        errors="raise"
    )

# Convert Year and Sr. No. to numeric
cleaned_atm["Year"] = pd.to_numeric(
    cleaned_atm["Year"],
    errors="raise"
)

cleaned_atm["Sr. No."] = pd.to_numeric(
    cleaned_atm["Sr. No."],
    errors="raise"
)

print("Numeric conversion completed successfully.")

Numeric conversion completed successfully.

In [37]:
# Check the data types after conversion

print(cleaned_atm.dtypes)

Year                                                                    int64
Month                                                                     str
Quarter                                                                   str
Source File                                                               str
Sr. No.                                                                 int64
Bank Name                                                                 str
Bank Category                                                             str
Infrastructure - ATMs & CRMs - On-site                                  int64
Infrastructure - ATMs & CRMs - Off-site                                 int64
Infrastructure - PoS                                                    int64
Infrastructure - Micro ATMs                                             int64
Infrastructure - Bharat QR Codes                                        int64
Infrastructure - UPI QR Codes                                         float64
Infrastructure - Credit Cards                                           int64
Infrastructure - Debit Cards                                            int64
Credit Card - Card Payments - PoS - Volume (in actuals)                 int64
Credit Card - Card Payments - PoS - Value (in Rs'000)                 float64
Credit Card - Card Payments - Online (e-com) - Volume (in actuals)      int64
Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)      float64
Credit Card - Card Payments - Others - Volume (in actuals)              int64
Credit Card - Card Payments - Others - Value (in Rs'000)              float64
Credit Card - Cash Withdrawal - ATM - Volume (in actuals)               int64
Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)               float64
Debit Card - Card Payments - PoS - Volume (in actuals)                  int64
Debit Card - Card Payments - PoS - Value (in Rs'000)                  float64
Debit Card - Card Payments - Online (e-com) - Volume (in actuals)       int64
Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)       float64
Debit Card - Card Payments - Others - Volume (in actuals)               int64
Debit Card - Card Payments - Others - Value (in Rs'000)               float64
Debit Card - Cash Withdrawal - ATM - Volume (in actuals)                int64
Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)                float64
Debit Card - Cash Withdrawal - PoS - Volume (in actuals)                int64
Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)                float64
dtype: object

In [38]:
# Check missing values after numeric conversion

final_missing = cleaned_atm.isna().sum()

print("Total missing values:", final_missing.sum())

if final_missing.sum() == 0:
    print("✓ No missing values were introduced.")
else:
    print("⚠ Missing values found:")
    display(final_missing[final_missing > 0])

Total missing values: 0
✓ No missing values were introduced.

In [39]:
# Final shape check

print("Rows:", cleaned_atm.shape[0])
print("Columns:", cleaned_atm.shape[1])

Rows: 768
Columns: 33

In [40]:
# Check whether any bank has more than one Bank Category

category_consistency = (
    cleaned_atm
    .groupby("Bank Name")["Bank Category"]
    .nunique()
    .sort_values(ascending=False)
)

print("Banks with more than one category:")

display(
    category_consistency[category_consistency > 1]
)

Banks with more than one category:

Series([], Name: Bank Category, dtype: int64)

In [41]:
# Check the number of banks in each category

bank_category_counts = (
    cleaned_atm
    .groupby("Bank Category")["Bank Name"]
    .nunique()
    .sort_values(ascending=False)
)

print("Unique banks by category:")

display(bank_category_counts)

Unique banks by category:

Bank Category
Private Sector Banks    21
Foreign Banks           14
Public Sector Banks     12
Small Finance Banks     12
Payment Banks            6
Name: Bank Name, dtype: int64

In [42]:
# Check for negative values in all numerical columns

negative_values = {}

for column in numeric_columns:
    negative_count = (cleaned_atm[column] < 0).sum()
    
    if negative_count > 0:
        negative_values[column] = negative_count

if len(negative_values) == 0:
    print("✓ No negative values found.")
else:
    print("⚠ Negative values found:")
    print(negative_values)

✓ No negative values found.

In [43]:
# Count zero values in numerical columns

zero_summary = (
    (cleaned_atm[numeric_columns] == 0)
    .sum()
    .sort_values(ascending=False)
)

display(zero_summary)

Credit Card - Card Payments - Others - Volume (in actuals)            718
Credit Card - Card Payments - Others - Value (in Rs'000)              718
Debit Card - Cash Withdrawal - PoS - Volume (in actuals)              600
Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)                600
Debit Card - Card Payments - Others - Value (in Rs'000)               534
Debit Card - Card Payments - Others - Volume (in actuals)             534
Infrastructure - Bharat QR Codes                                      526
Infrastructure - Micro ATMs                                           409
Infrastructure - PoS                                                  381
Credit Card - Cash Withdrawal - ATM - Volume (in actuals)             353
Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)               351
Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)      297
Credit Card - Card Payments - Online (e-com) - Volume (in actuals)    297
Credit Card - Card Payments - PoS - Value (in Rs'000)                 295
Credit Card - Card Payments - PoS - Volume (in actuals)               295
Infrastructure - Credit Cards                                         291
Infrastructure - UPI QR Codes                                         288
Infrastructure - ATMs & CRMs - Off-site                               243
Infrastructure - ATMs & CRMs - On-site                                204
Debit Card - Card Payments - Online (e-com) - Volume (in actuals)      66
Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)        66
Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)                 50
Debit Card - Cash Withdrawal - ATM - Volume (in actuals)               50
Debit Card - Card Payments - PoS - Value (in Rs'000)                   48
Debit Card - Card Payments - PoS - Volume (in actuals)                 48
Infrastructure - Debit Cards                                           36
dtype: int64

In [44]:
# Check for leading or trailing spaces in Bank Name

bank_names = cleaned_atm["Bank Name"]

leading_spaces = bank_names[bank_names.str.startswith(" ")]
trailing_spaces = bank_names[bank_names.str.endswith(" ")]

print("Names with leading spaces:", len(leading_spaces))
print("Names with trailing spaces:", len(trailing_spaces))

Names with leading spaces: 0
Names with trailing spaces: 12

In [45]:
# Compare original bank names with stripped bank names

stripped_names = cleaned_atm["Bank Name"].str.strip()

print("Original unique bank names:", cleaned_atm["Bank Name"].nunique())
print("Unique bank names after stripping spaces:", stripped_names.nunique())

Original unique bank names: 65
Unique bank names after stripping spaces: 65

In [46]:
# Remove leading and trailing spaces from Bank Name

cleaned_atm["Bank Name"] = cleaned_atm["Bank Name"].str.strip()

print("Bank names cleaned successfully.")
print("Unique banks:", cleaned_atm["Bank Name"].nunique())

Bank names cleaned successfully.
Unique banks: 65

In [47]:
# Verify there are no leading/trailing spaces remaining

print(
    "Leading spaces:",
    cleaned_atm["Bank Name"].str.startswith(" ").sum()
)

print(
    "Trailing spaces:",
    cleaned_atm["Bank Name"].str.endswith(" ").sum()
)

Leading spaces: 0
Trailing spaces: 0

In [48]:
# Number of records available for each bank

bank_frequency = (
    cleaned_atm["Bank Name"]
    .value_counts()
    .sort_values()
)

display(bank_frequency)

Bank Name
NORTH EAST SMALL FINANCE BANK LTD     4
SLICE SMALL FINANCE BANK LTD          8
BANK OF MAHARASHTRA                  12
BANK OF BARODA                       12
CENTRAL BANK OF INDIA                12
                                     ..
SURYODAY SMALL FINANCE BANK LTD      12
UJJIVAN SMALL FINANCE BANK LTD       12
UNITY SMALL FINANCE BANK LTD         12
CSB BANK LTD.                        12
UTKARSH SMALL FINANCE BANK LTD       12
Name: count, Length: 65, dtype: int64

In [49]:
# Check which Quarter is associated with each Month

month_quarter_check = (
    cleaned_atm[["Month", "Quarter"]]
    .drop_duplicates()
)

display(month_quarter_check)

         Month Quarter
0      January      Q1
71    February      Q1
142      March      Q1
213      April      Q2
284        May      Q2
355       June      Q2
426       July      Q3
497     August      Q3
568  September      Q3
639    October      Q4
710   November      Q4
781   December      Q4

In [50]:
# Check the Year values

print("Unique Year values:")
print(cleaned_atm["Year"].unique())

print("\nNumber of records for each Year:")
print(cleaned_atm["Year"].value_counts())

Unique Year values:
[2025]

Number of records for each Year:
Year
2025    768
Name: count, dtype: int64

In [51]:
# Check number of source files

print("Number of unique source files:",
      cleaned_atm["Source File"].nunique())

display(
    cleaned_atm[["Month", "Source File"]]
    .drop_duplicates()
    .sort_values("Month")
)

Number of unique source files: 12

         Month                              Source File
213      April  ATMAPRIL25A53BB941D2DD420396BFADA671...
497     August  ATMAUGUST2025FE83AB680ECC4DE48661FF1...
781   December  ATM122025010824B80F314664BFB1DA8F179...
71    February  ATMFEBRUARY20257E29C21AB6AD4CDFAB6C0...
0      January  ATMJANUARY2025B1FB692B5934404B883922...
426       July  ATMJULY20259DD80A92103A477A88BEDB6A5...
355       June  ATMJUNE2025599A531681334E06B9CF942D0...
142      March  ATMMARCH202530FC885C0DD7498F9F94FA60...
284        May  ATMMAY2306202583416DC93AF04D958DBA2E...
710   November  ATMOCTOBER20251BB945D4B48243919FC752...
639    October  ATMOCTOBER202555BCB90087E940BD92477C...
568  September  ATMSEPTEMBER202541852720BAFD4A8A90E3...

In [52]:
# Check Sr. No. range for each month

sr_no_summary = (
    cleaned_atm
    .groupby("Month")["Sr. No."]
    .agg(["count", "min", "max", "nunique"])
)

display(sr_no_summary)

           count  min  max  nunique
Month
April         64    1   64       64
August        64    1   64       64
December      64    1   64       64
February      64    1   64       64
January       64    1   64       64
July          64    1   64       64
June          64    1   64       64
March         64    1   64       64
May           64    1   64       64
November      64    1   64       64
October       64    1   64       64
September     64    1   64       64

In [53]:
# Check whether Sr. No. values are duplicated within a month

sr_duplicates = (
    cleaned_atm
    .groupby(["Month", "Sr. No."])
    .size()
    .reset_index(name="count")
)

sr_duplicates = sr_duplicates[sr_duplicates["count"] > 1]

print("Duplicate Sr. No. within the same month:", len(sr_duplicates))

display(sr_duplicates)

Duplicate Sr. No. within the same month: 0

Empty DataFrame
Columns: [Month, Sr. No., count]
Index: []

In [54]:
# Extract the 12 official monthly Total rows from the original dataset

total_rows = bank_records[
    bank_records["Bank Name"].astype(str).str.strip().eq("Total")
].copy()

print("Number of Total rows:", len(total_rows))

display(
    total_rows[["Year", "Month", "Quarter", "Bank Name"]]
)

Number of Total rows: 12

     Year      Month Quarter Bank Name
68   2025    January      Q1     Total
139  2025   February      Q1     Total
210  2025      March      Q1     Total
281  2025      April      Q2     Total
352  2025        May      Q2     Total
423  2025       June      Q2     Total
494  2025       July      Q3     Total
565  2025     August      Q3     Total
636  2025  September      Q3     Total
707  2025    October      Q4     Total
778  2025   November      Q4     Total
849  2025   December      Q4     Total

In [55]:
# Numerical columns used for total validation

numeric_columns = cleaned_atm.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Number of numerical columns:", len(numeric_columns))

for i, col in enumerate(numeric_columns, 1):
    print(i, ":", col)

Number of numerical columns: 28
1 : Year
2 : Sr. No.
3 : Infrastructure - ATMs & CRMs - On-site
4 : Infrastructure - ATMs & CRMs - Off-site
5 : Infrastructure - PoS
6 : Infrastructure - Micro ATMs
7 : Infrastructure - Bharat QR Codes
8 : Infrastructure - UPI QR Codes
9 : Infrastructure - Credit Cards
10 : Infrastructure - Debit Cards
11 : Credit Card - Card Payments - PoS - Volume (in actuals)
12 : Credit Card - Card Payments - PoS - Value (in Rs'000)
13 : Credit Card - Card Payments - Online (e-com) - Volume (in actuals)
14 : Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)
15 : Credit Card - Card Payments - Others - Volume (in actuals)
16 : Credit Card - Card Payments - Others - Value (in Rs'000)
17 : Credit Card - Cash Withdrawal - ATM - Volume (in actuals)
18 : Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)
19 : Debit Card - Card Payments - PoS - Volume (in actuals)
20 : Debit Card - Card Payments - PoS - Value (in Rs'000)
21 : Debit Card - Card Payments - Online (e-com) - Volume (in actuals)
22 : Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)
23 : Debit Card - Card Payments - Others - Volume (in actuals)
24 : Debit Card - Card Payments - Others - Value (in Rs'000)
25 : Debit Card - Cash Withdrawal - ATM - Volume (in actuals)
26 : Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)
27 : Debit Card - Cash Withdrawal - PoS - Volume (in actuals)
28 : Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)

In [56]:
# Calculate totals from the 64 bank records for each month

calculated_monthly_totals = (
    cleaned_atm
    .groupby("Month")[numeric_columns]
    .sum()
)

display(calculated_monthly_totals)

,Year,Sr. No.,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
Month,,,,,,,,,,,,,,,,,,,,,,,,,,,,
April,129600,2080,131265,82526,11283266,1473668,6663778,662384943.0,110437069,995983731,228140764,6.789929e+08,221275020,1.163224e+09,854442,156864.76193,686493,3.727257e+06,87530236,2.618749e+08,29478270,1.178628e+08,84978,1.393438e+06,457805976,2.434936e+09,14548,14252.621700
August,129600,2080,130897,76122,11964613,1471422,6573082,697747231.0,112495592,1018042450,250162542,7.275332e+08,241618661,1.183811e+09,1795973,354787.56652,671163,3.656376e+06,84359478,2.466282e+08,27641922,1.259930e+08,78872,1.441900e+06,460136709,2.388832e+09,10137,10156.621810
December,129600,2080,133729,73756,11474672,1414547,5890220,731365285.0,115791713,1034345867,272631988,7.847648e+08,264617358,1.261428e+09,2584779,673423.65048,696197,3.931495e+06,79435329,2.459910e+08,25407654,1.251232e+08,81047,1.629609e+06,444401793,2.389248e+09,11876,19588.618500
February,129600,2080,132059,84777,10717514,1467966,6548149,649691280.0,109315356,985676745,199995593,6.212491e+08,196284815,1.050708e+09,678682,122706.55300,684455,3.697635e+06,80342355,2.321622e+08,27813305,1.095293e+08,94042,1.448942e+06,447376890,2.344080e+09,19281,21360.331500
January,129600,2080,130902,85804,10352730,1473899,6443092,640164702.0,108873184,982039277,217743317,6.942940e+08,212193992,1.146851e+09,635076,116861.51800,779153,4.123902e+06,91091391,2.599880e+08,30470254,1.279346e+08,107782,1.711062e+06,488353232,2.506461e+09,24327,27679.510190
July,129600,2080,131223,76840,11913080,1466668,6641351,688030939.0,111807972,1012727337,243275291,7.038031e+08,241322355,1.234404e+09,1583475,287200.42900,662973,3.616172e+06,83219175,2.392119e+08,28764405,1.406622e+08,77390,1.500947e+06,444765520,2.317224e+09,10595,10373.780941
June,129600,2080,131169,78801,11782954,1459218,6699048,678160811.0,110969493,1005180283,233869565,6.746779e+08,223606182,1.155977e+09,1234386,226492.93000,628066,3.448546e+06,81289624,2.307924e+08,27210465,1.225478e+08,71982,1.293975e+06,435858139,2.287347e+09,11475,10832.765900
March,129600,2080,131323,83518,11098051,1481883,6718039,657929517.0,109884686,990812421,230266329,7.147301e+08,227565189,1.300057e+09,818905,151420.27789,743191,4.101396e+06,89581561,2.581804e+08,30622450,1.307736e+08,97940,1.592844e+06,495721528,2.625398e+09,19075,20745.019030
May,129600,2080,134809,81162,11581161,1478043,6642075,669729906.0,111049553,1000369817,235914154,6.960742e+08,230745664,1.202053e+09,1033673,189531.77800,670129,3.701260e+06,86156629,2.473544e+08,28805524,1.209646e+08,84674,1.465297e+06,457987566,2.449449e+09,12800,12621.420320
November,129600,2080,133339,74457,11253425,1427193,5952557,728199555.5,115001607,1031703169,253839650,7.563987e+08,246854090,1.130994e+09,2290438,596967.10374,671955,3.784610e+06,76331463,2.275412e+08,24803398,1.123690e+08,76453,1.523649e+06,438022645,2.340546e+09,12269,19892.082240
October,129600,2080,132454,74923,12308241,1464566,6047707,717433868.0,114133565,1027150225,260941537,8.835700e+08,255272591,1.258196e+09,2075421,536969.75580,711645,4.038789e+06,82878827,2.910353e+08,26666791,1.288813e+08,78957,1.513487e+06,463633544,2.503215e+09,12577,19953.592470
September,129600,2080,131664,75047,12116102,1459945,6070528,708974740.0,113507240,1024808790,241614615,7.254390e+08,251718295,1.441178e+09,1907738,453096.05260,668889,3.688142e+06,77755830,2.277268e+08,26904171,1.385427e+08,79030,1.487487e+06,437090119,2.297134e+09,9740,12202.583940

In [57]:
# Convert official Total row numerical columns to numeric

for col in numeric_columns:
    total_rows[col] = pd.to_numeric(
        total_rows[col],
        errors="coerce"
    )

official_monthly_totals = (
    total_rows
    .set_index("Month")[numeric_columns]
)

display(official_monthly_totals)

,Year,Sr. No.,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
Month,,,,,,,,,,,,,,,,,,,,,,,,,,,,
January,2025,NaN,130902,85804,10352730,1473899,6443092,640164702.0,108873184,982039277,217743317,6.942940e+08,212193992,1.146851e+09,635076,116861.51800,779153,4.123902e+06,91091391,2.599880e+08,30470254,1.279346e+08,107782,1.711062e+06,488353232,2.506461e+09,24327,27679.510190
February,2025,NaN,132059,84777,10717514,1467966,6548149,649691280.0,109315356,985676745,199995593,6.212491e+08,196284815,1.050708e+09,678682,122706.55300,684455,3.697635e+06,80342355,2.321622e+08,27813305,1.095293e+08,94042,1.448942e+06,447376890,2.344080e+09,19281,21360.331500
March,2025,NaN,131323,83518,11098051,1481883,6718039,657929517.0,109884686,990812421,230266329,7.147301e+08,227565189,1.300057e+09,818905,151420.27789,743191,4.101396e+06,89581561,2.581804e+08,30622450,1.307736e+08,97940,1.592844e+06,495721528,2.625398e+09,19075,20745.019030
April,2025,NaN,131265,82526,11283266,1473668,6663778,662384943.0,110437069,995983731,228140764,6.789929e+08,221275020,1.163224e+09,854442,156864.76193,686493,3.727257e+06,87530236,2.618749e+08,29478270,1.178628e+08,84978,1.393438e+06,457805976,2.434936e+09,14548,14252.621700
May,2025,NaN,134809,81162,11581161,1478043,6642075,669729906.0,111049553,1000369817,235914154,6.960742e+08,230745664,1.202053e+09,1033673,189531.77800,670129,3.701260e+06,86156629,2.473544e+08,28805524,1.209646e+08,84674,1.465297e+06,457987566,2.449449e+09,12800,12621.420320
June,2025,NaN,131169,78801,11782954,1459218,6699048,678160811.0,110969493,1005180283,233869565,6.746779e+08,223606182,1.155977e+09,1234386,226492.93000,628066,3.448546e+06,81289624,2.307924e+08,27210465,1.225478e+08,71982,1.293975e+06,435858139,2.287347e+09,11475,10832.765900
July,2025,NaN,131223,76840,11913080,1466668,6641351,688030939.0,111807972,1012727337,243275291,7.038031e+08,241322355,1.234404e+09,1583475,287200.42900,662973,3.616172e+06,83219175,2.392119e+08,28764405,1.406622e+08,77390,1.500947e+06,444765520,2.317224e+09,10595,10373.780941
August,2025,NaN,130897,76122,11964613,1471422,6573082,697747231.0,112495592,1018042450,250162542,7.275332e+08,241618661,1.183811e+09,1795973,354787.56652,671163,3.656376e+06,84359478,2.466282e+08,27641922,1.259930e+08,78872,1.441900e+06,460136709,2.388832e+09,10137,10156.621810
September,2025,NaN,131664,75047,12116102,1459945,6070528,708974740.0,113507240,1024808790,241614615,7.254390e+08,251718295,1.441178e+09,1907738,453096.05260,668889,3.688142e+06,77755830,2.277268e+08,26904171,1.385427e+08,79030,1.487487e+06,437090119,2.297134e+09,9740,12202.583940
October,2025,NaN,132454,74923,12308241,1464566,6047707,717433868.0,114133565,1027150225,260941537,8.835700e+08,255272591,1.258196e+09,2075421,536969.75580,711645,4.038789e+06,82878827,2.910353e+08,26666791,1.288813e+08,78957,1.513487e+06,463633544,2.503215e+09,12577,19953.592470
November,2025,NaN,133339,74457,11253425,1427193,5952557,728199555.5,115001607,1031703169,253839650,7.563987e+08,246854090,1.130994e+09,2290438,596967.10374,671955,3.784610e+06,76331463,2.275412e+08,24803398,1.123690e+08,76453,1.523649e+06,438022645,2.340546e+09,12269,19892.082240
December,2025,NaN,133729,73756,11474672,1414547,5890220,731365285.0,115791713,1034345867,272631988,7.847648e+08,264617358,1.261428e+09,2584779,673423.65048,696197,3.931495e+06,79435329,2.459910e+08,25407654,1.251232e+08,81047,1.629609e+06,444401793,2.389248e+09,11876,19588.618500

In [58]:
# Compare calculated totals with official Total rows

comparison = (
    calculated_monthly_totals
    .subtract(official_monthly_totals)
)

display(comparison)

,Year,Sr. No.,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
Month,,,,,,,,,,,,,,,,,,,,,,,,,,,,
April,127575,NaN,0,0,0,0,0,0.0,0,0,0,3.576279e-07,0,-1.907349e-06,0,0.000000e+00,0,0.000000e+00,0,2.384186e-07,0,-1.490116e-08,0,0.000000e+00,0,1.907349e-06,0,0.000000e+00
August,127575,NaN,0,0,0,0,0,0.0,0,0,0,1.192093e-07,0,-2.622604e-06,0,0.000000e+00,0,-4.656613e-10,0,8.940697e-08,0,-5.960464e-08,0,0.000000e+00,0,5.722046e-06,0,0.000000e+00
December,127575,NaN,0,0,0,0,0,0.0,0,0,0,2.384186e-07,0,4.768372e-07,0,0.000000e+00,0,0.000000e+00,0,1.490116e-07,0,-1.192093e-07,0,2.328306e-10,0,4.768372e-07,0,0.000000e+00
February,127575,NaN,0,0,0,0,0,0.0,0,0,0,-2.384186e-07,0,3.576279e-07,0,0.000000e+00,0,0.000000e+00,0,1.192093e-07,0,-1.192093e-07,0,0.000000e+00,0,-5.245209e-06,0,0.000000e+00
January,127575,NaN,0,0,0,0,0,0.0,0,0,0,2.384186e-07,0,7.152557e-07,0,1.455192e-11,0,0.000000e+00,0,1.192093e-07,0,2.980232e-08,0,0.000000e+00,0,9.536743e-07,0,0.000000e+00
July,127575,NaN,0,0,0,0,0,0.0,0,0,0,-3.576279e-07,0,-4.768372e-07,0,0.000000e+00,0,0.000000e+00,0,1.192093e-07,0,-2.682209e-07,0,-2.328306e-10,0,-4.291534e-06,0,0.000000e+00
June,127575,NaN,0,0,0,0,0,0.0,0,0,0,-1.192093e-07,0,-7.152557e-07,0,0.000000e+00,0,0.000000e+00,0,-5.960464e-08,0,-1.192093e-07,0,0.000000e+00,0,-4.768372e-06,0,0.000000e+00
March,127575,NaN,0,0,0,0,0,0.0,0,0,0,-8.344650e-07,0,-1.430511e-06,0,0.000000e+00,0,4.656613e-10,0,1.490116e-07,0,-1.788139e-07,0,2.328306e-10,0,-2.861023e-06,0,0.000000e+00
May,127575,NaN,0,0,0,0,0,0.0,0,0,0,-1.192093e-07,0,-7.152557e-07,0,2.910383e-11,0,0.000000e+00,0,2.980232e-08,0,-7.450581e-08,0,0.000000e+00,0,-1.907349e-06,0,0.000000e+00
November,127575,NaN,0,0,0,0,0,0.0,0,0,0,-4.768372e-07,0,-1.192093e-06,0,0.000000e+00,0,0.000000e+00,0,-8.940697e-08,0,0.000000e+00,0,0.000000e+00,0,2.861023e-06,0,-3.637979e-12
October,127575,NaN,0,0,0,0,0,0.0,0,0,0,9.536743e-07,0,-2.622604e-06,0,0.000000e+00,0,0.000000e+00,0,5.960464e-08,0,-5.960464e-08,0,0.000000e+00,0,-5.245209e-06,0,0.000000e+00
September,127575,NaN,0,0,0,0,0,0.0,0,0,0,-1.192093e-07,0,3.099442e-06,0,0.000000e+00,0,0.000000e+00,0,5.960464e-08,0,-1.192093e-07,0,0.000000e+00,0,-4.768372e-06,0,-1.818989e-12

In [59]:
# Check whether calculated and official totals match
# within a very small numerical tolerance

import numpy as np

matches = np.isclose(
    calculated_monthly_totals,
    official_monthly_totals,
    rtol=1e-9,
    atol=1e-6
)

print("All totals match:", matches.all())

print(
    "Number of mismatched cells:",
    (~matches).sum().sum()
)

All totals match: False
Number of mismatched cells: 336

In [61]:
# Count mismatches for each numerical column

mismatch_count = (~matches).sum(axis=0)

# Convert the NumPy array into a Pandas Series
mismatch_summary = pd.Series(
    mismatch_count,
    index=numeric_columns
)

# Keep only columns having mismatches
mismatch_summary = (
    mismatch_summary[mismatch_summary > 0]
    .sort_values(ascending=False)
)

print("Columns with mismatches:")
display(mismatch_summary)

Columns with mismatches:

Year                                                                  12
Sr. No.                                                               12
Infrastructure - ATMs & CRMs - On-site                                12
Infrastructure - ATMs & CRMs - Off-site                               12
Infrastructure - PoS                                                  12
Infrastructure - Micro ATMs                                           12
Infrastructure - Bharat QR Codes                                      12
Infrastructure - UPI QR Codes                                         12
Infrastructure - Credit Cards                                         12
Infrastructure - Debit Cards                                          12
Credit Card - Card Payments - PoS - Volume (in actuals)               12
Credit Card - Card Payments - PoS - Value (in Rs'000)                 12
Credit Card - Card Payments - Online (e-com) - Volume (in actuals)    12
Credit Card - Card Payments - Online (e-com) - Value (in Rs'000)      12
Credit Card - Card Payments - Others - Volume (in actuals)            12
Credit Card - Card Payments - Others - Value (in Rs'000)              12
Credit Card - Cash Withdrawal - ATM - Volume (in actuals)             12
Credit Card - Cash Withdrawal - ATM - Value (in Rs'000)               12
Debit Card - Card Payments - PoS - Volume (in actuals)                12
Debit Card - Card Payments - PoS - Value (in Rs'000)                  12
Debit Card - Card Payments - Online (e-com) - Volume (in actuals)     12
Debit Card - Card Payments - Online (e-com) - Value (in Rs'000)       12
Debit Card - Card Payments - Others - Volume (in actuals)             12
Debit Card - Card Payments - Others - Value (in Rs'000)               12
Debit Card - Cash Withdrawal - ATM - Volume (in actuals)              12
Debit Card - Cash Withdrawal - ATM - Value (in Rs'000)                12
Debit Card - Cash Withdrawal - PoS - Volume (in actuals)              12
Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)                12
dtype: int64

In [62]:
# Count mismatches for each month

monthly_mismatch_count = (~matches).sum(axis=1)

print("Mismatches by month:")

display(
    monthly_mismatch_count[
        monthly_mismatch_count > 0
    ]
)

Mismatches by month:

array([28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28])

In [63]:
# Show the differences between our calculated totals
# and the official Total rows

difference = (
    calculated_monthly_totals
    - official_monthly_totals
)

# Show only non-zero differences
difference_nonzero = difference.where(
    ~np.isclose(
        difference,
        0,
        rtol=1e-9,
        atol=1e-6
    ),
    0
)

display(difference_nonzero)

,Year,Sr. No.,Infrastructure - ATMs & CRMs - On-site,Infrastructure - ATMs & CRMs - Off-site,Infrastructure - PoS,Infrastructure - Micro ATMs,Infrastructure - Bharat QR Codes,Infrastructure - UPI QR Codes,Infrastructure - Credit Cards,Infrastructure - Debit Cards,Credit Card - Card Payments - PoS - Volume (in actuals),Credit Card - Card Payments - PoS - Value (in Rs'000),Credit Card - Card Payments - Online (e-com) - Volume (in actuals),Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),Credit Card - Card Payments - Others - Volume (in actuals),Credit Card - Card Payments - Others - Value (in Rs'000),Credit Card - Cash Withdrawal - ATM - Volume (in actuals),Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Card Payments - PoS - Volume (in actuals),Debit Card - Card Payments - PoS - Value (in Rs'000),Debit Card - Card Payments - Online (e-com) - Volume (in actuals),Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),Debit Card - Card Payments - Others - Volume (in actuals),Debit Card - Card Payments - Others - Value (in Rs'000),Debit Card - Cash Withdrawal - ATM - Volume (in actuals),Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),Debit Card - Cash Withdrawal - PoS - Volume (in actuals),Debit Card - Cash Withdrawal - PoS - Value (in Rs'000)
Month,,,,,,,,,,,,,,,,,,,,,,,,,,,,
April,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,-0.000002,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000002,0,0.0
August,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,-0.000003,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000006,0,0.0
December,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0
February,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000005,0,0.0
January,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000000,0,0.0
July,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000004,0,0.0
June,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000005,0,0.0
March,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,-0.000001,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000003,0,0.0
May,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000000,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000002,0,0.0
November,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,-0.000001,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,0.000003,0,0.0
October,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,-0.000003,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000005,0,0.0
September,127575,NaN,0,0,0,0,0,0.0,0,0,0,0.0,0,0.000003,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0,0,-0.000005,0,0.0

In [64]:
# Compare January calculated totals vs official totals

january_comparison = pd.DataFrame({
    "Calculated from Banks": calculated_monthly_totals.loc["January"],
    "Official Total Row": official_monthly_totals.loc["January"]
})

january_comparison["Difference"] = (
    january_comparison["Calculated from Banks"]
    - january_comparison["Official Total Row"]
)

display(january_comparison)

,Calculated from Banks,Official Total Row,Difference
Year,1.296000e+05,2.025000e+03,1.275750e+05
Sr. No.,2.080000e+03,NaN,NaN
Infrastructure - ATMs & CRMs - On-site,1.309020e+05,1.309020e+05,0.000000e+00
Infrastructure - ATMs & CRMs - Off-site,8.580400e+04,8.580400e+04,0.000000e+00
Infrastructure - PoS,1.035273e+07,1.035273e+07,0.000000e+00
Infrastructure - Micro ATMs,1.473899e+06,1.473899e+06,0.000000e+00
Infrastructure - Bharat QR Codes,6.443092e+06,6.443092e+06,0.000000e+00
Infrastructure - UPI QR Codes,6.401647e+08,6.401647e+08,0.000000e+00
Infrastructure - Credit Cards,1.088732e+08,1.088732e+08,0.000000e+00
Infrastructure - Debit Cards,9.820393e+08,9.820393e+08,0.000000e+00
Credit Card - Card Payments - PoS - Volume (in actuals),2.177433e+08,2.177433e+08,0.000000e+00
Credit Card - Card Payments - PoS - Value (in Rs'000),6.942940e+08,6.942940e+08,2.384186e-07
Credit Card - Card Payments - Online (e-com) - Volume (in actuals),2.121940e+08,2.121940e+08,0.000000e+00
Credit Card - Card Payments - Online (e-com) - Value (in Rs'000),1.146851e+09,1.146851e+09,7.152557e-07
Credit Card - Card Payments - Others - Volume (in actuals),6.350760e+05,6.350760e+05,0.000000e+00
Credit Card - Card Payments - Others - Value (in Rs'000),1.168615e+05,1.168615e+05,1.455192e-11
Credit Card - Cash Withdrawal - ATM - Volume (in actuals),7.791530e+05,7.791530e+05,0.000000e+00
Credit Card - Cash Withdrawal - ATM - Value (in Rs'000),4.123902e+06,4.123902e+06,0.000000e+00
Debit Card - Card Payments - PoS - Volume (in actuals),9.109139e+07,9.109139e+07,0.000000e+00
Debit Card - Card Payments - PoS - Value (in Rs'000),2.599880e+08,2.599880e+08,1.192093e-07
Debit Card - Card Payments - Online (e-com) - Volume (in actuals),3.047025e+07,3.047025e+07,0.000000e+00
Debit Card - Card Payments - Online (e-com) - Value (in Rs'000),1.279346e+08,1.279346e+08,2.980232e-08
Debit Card - Card Payments - Others - Volume (in actuals),1.077820e+05,1.077820e+05,0.000000e+00
Debit Card - Card Payments - Others - Value (in Rs'000),1.711062e+06,1.711062e+06,0.000000e+00
Debit Card - Cash Withdrawal - ATM - Volume (in actuals),4.883532e+08,4.883532e+08,0.000000e+00
Debit Card - Cash Withdrawal - ATM - Value (in Rs'000),2.506461e+09,2.506461e+09,9.536743e-07
Debit Card - Cash Withdrawal - PoS - Volume (in actuals),2.432700e+04,2.432700e+04,0.000000e+00
Debit Card - Cash Withdrawal - PoS - Value (in Rs'000),2.767951e+04,2.767951e+04,0.000000e+00

In [65]:
print("Duplicate rows:", cleaned_atm.duplicated().sum())

Duplicate rows: 0

In [66]:
print("Infinite values:", np.isinf(cleaned_atm[numeric_columns]).sum().sum())

Infinite values: 0

In [67]:
print(cleaned_atm["Bank Category"].value_counts())
print(cleaned_atm["Month"].value_counts())
print(cleaned_atm["Quarter"].value_counts())

Bank Category
Private Sector Banks    252
Foreign Banks           168
Public Sector Banks     144
Small Finance Banks     132
Payment Banks            72
Name: count, dtype: int64
Month
January      64
February     64
March        64
April        64
May          64
June         64
July         64
August       64
September    64
October      64
November     64
December     64
Name: count, dtype: int64
Quarter
Q1    192
Q2    192
Q3    192
Q4    192
Name: count, dtype: int64

In [68]:
month_map = {
    "January": 1, "February": 2, "March": 3,
    "April": 4, "May": 5, "June": 6,
    "July": 7, "August": 8, "September": 9,
    "October": 10, "November": 11, "December": 12
}

cleaned_atm["Month_Num"] = cleaned_atm["Month"].map(month_map)

cleaned_atm["Date"] = pd.to_datetime(
    cleaned_atm["Year"].astype(str) + "-" +
    cleaned_atm["Month_Num"].astype(str) + "-01"
)

In [69]:
cleaned_atm.to_csv("cleaned_atm_2025.csv", index=False)