In [1]:
# =============================================================================
# NPCI RETAIL PAYMENTS STATISTICS
# STEP 1: RAW DATASET AUDIT
# =============================================================================

import pandas as pd
import numpy as np
import os
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 100)


# =============================================================================
# 1. INPUT FILE
# =============================================================================

INPUT_FILE = "NPCI-Retail-Payments-Statistics---Excel-Format.xlsx"

print("=" * 90)
print("STEP 1: RAW DATASET AUDIT")
print("=" * 90)

print("\nINPUT FILE")
print("-" * 90)
print("Input file :", INPUT_FILE)


# =============================================================================
# 2. FILE EXISTENCE CHECK
# =============================================================================

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}\n"
        "Place the Excel file in the current working directory."
    )

file_size = os.path.getsize(INPUT_FILE)

print("File size  :", f"{file_size:,}", "bytes")


# =============================================================================
# 3. LOAD WORKBOOK
# =============================================================================

xls = pd.ExcelFile(INPUT_FILE)

print("\n" + "=" * 90)
print("1. WORKBOOK INFORMATION")
print("=" * 90)

print("Number of sheets :", len(xls.sheet_names))
print("Sheet names      :", xls.sheet_names)


# =============================================================================
# 4. LOAD ALL SHEETS WITHOUT MODIFYING DATA
# =============================================================================

raw_sheets = {}

for sheet in xls.sheet_names:

    df = pd.read_excel(
        INPUT_FILE,
        sheet_name=sheet,
        header=None
    )

    raw_sheets[sheet] = df.copy()

    print("\n" + "-" * 90)
    print("SHEET:", sheet)
    print("-" * 90)

    print("Rows    :", df.shape[0])
    print("Columns :", df.shape[1])


# =============================================================================
# 5. SELECT PRIMARY SHEET
# =============================================================================

SHEET_NAME = xls.sheet_names[0]

raw_df = raw_sheets[SHEET_NAME].copy()

print("\n" + "=" * 90)
print("2. RAW SHEET STRUCTURE")
print("=" * 90)

print("Selected sheet :", SHEET_NAME)
print("Raw rows       :", raw_df.shape[0])
print("Raw columns    :", raw_df.shape[1])


# =============================================================================
# 6. FIRST 10 RAW ROWS
# =============================================================================

print("\n" + "=" * 90)
print("3. FIRST 10 RAW ROWS")
print("=" * 90)

display(raw_df.head(10))


# =============================================================================
# 7. LAST 10 RAW ROWS
# =============================================================================

print("\n" + "=" * 90)
print("4. LAST 10 RAW ROWS")
print("=" * 90)

display(raw_df.tail(10))


# =============================================================================
# 8. RAW COLUMN INFORMATION
# =============================================================================

print("\n" + "=" * 90)
print("5. RAW COLUMN INFORMATION")
print("=" * 90)

column_info = pd.DataFrame({
    "Column_Index": range(len(raw_df.columns)),
    "Column_Name": raw_df.columns.astype(str),
    "Non_Null_Count": raw_df.notna().sum().values,
    "Missing_Count": raw_df.isna().sum().values,
    "Unique_Count": [
        raw_df[col].nunique(dropna=True)
        for col in raw_df.columns
    ]
})

display(column_info)


# =============================================================================
# 9. CELL TYPE ANALYSIS
# =============================================================================

print("\n" + "=" * 90)
print("6. CELL TYPE ANALYSIS")
print("=" * 90)

numeric_count = 0
string_count = 0
datetime_count = 0
boolean_count = 0
other_count = 0
missing_count = 0

for col in raw_df.columns:

    for value in raw_df[col]:

        if pd.isna(value):
            missing_count += 1

        elif isinstance(value, (bool, np.bool_)):
            boolean_count += 1

        elif isinstance(value, (pd.Timestamp,)):
            datetime_count += 1

        elif isinstance(value, (int, float, np.integer, np.floating)):
            numeric_count += 1

        elif isinstance(value, str):
            string_count += 1

        else:
            other_count += 1


print("Numeric     :", numeric_count)
print("String      :", string_count)
print("Datetime    :", datetime_count)
print("Boolean     :", boolean_count)
print("Other       :", other_count)
print("Missing     :", missing_count)


# =============================================================================
# 10. DATASET-WIDE MISSINGNESS
# =============================================================================

print("\n" + "=" * 90)
print("7. DATASET-WIDE MISSINGNESS")
print("=" * 90)

total_cells = raw_df.size
total_missing = raw_df.isna().sum().sum()
total_present = total_cells - total_missing

print("Total cells     :", total_cells)
print("Missing cells   :", total_missing)
print("Present cells   :", total_present)
print(
    "Missing %       :",
    round((total_missing / total_cells) * 100, 4)
)


# =============================================================================
# 11. DATASET-WIDE ZERO COUNT
# =============================================================================

print("\n" + "=" * 90)
print("8. ZERO-VALUE ANALYSIS")
print("=" * 90)

numeric_raw = raw_df.apply(
    lambda col: pd.to_numeric(col, errors="coerce")
)

zero_mask = numeric_raw.eq(0)

zero_count = zero_mask.sum().sum()

print("Numeric zero cells :", int(zero_count))


# =============================================================================
# 12. COLUMN-WISE MISSINGNESS
# =============================================================================

print("\n" + "=" * 90)
print("9. COLUMN-WISE MISSINGNESS")
print("=" * 90)

missing_by_column = pd.DataFrame({
    "Column_Index": range(len(raw_df.columns)),
    "Column": raw_df.columns,
    "Missing_Count": raw_df.isna().sum().values,
    "Present_Count": raw_df.notna().sum().values,
    "Missing_Percentage": (
        raw_df.isna().mean().values * 100
    )
})

missing_by_column = missing_by_column.sort_values(
    "Missing_Count",
    ascending=False
)

display(missing_by_column)


# =============================================================================
# 13. ROW-WISE MISSINGNESS
# =============================================================================

print("\n" + "=" * 90)
print("10. ROW-WISE MISSINGNESS")
print("=" * 90)

row_missing = pd.DataFrame({
    "Row_Index": raw_df.index,
    "Missing_Count": raw_df.isna().sum(axis=1).values,
    "Present_Count": raw_df.notna().sum(axis=1).values,
    "Missing_Percentage": (
        raw_df.isna().mean(axis=1).values * 100
    )
})

display(row_missing)


# =============================================================================
# 14. COMPLETELY EMPTY ROWS
# =============================================================================

print("\n" + "=" * 90)
print("11. COMPLETELY EMPTY ROW CHECK")
print("=" * 90)

empty_rows = raw_df.isna().all(axis=1)

print("Completely empty rows :", int(empty_rows.sum()))

if empty_rows.sum() > 0:
    print("Empty row indices:")
    print(raw_df.index[empty_rows].tolist())


# =============================================================================
# 15. COMPLETELY EMPTY COLUMNS
# =============================================================================

print("\n" + "=" * 90)
print("12. COMPLETELY EMPTY COLUMN CHECK")
print("=" * 90)

empty_columns = raw_df.isna().all(axis=0)

print("Completely empty columns :", int(empty_columns.sum()))

if empty_columns.sum() > 0:
    print("Empty column indices:")
    print(raw_df.columns[empty_columns].tolist())


# =============================================================================
# 16. DUPLICATE ROW ANALYSIS
# =============================================================================

print("\n" + "=" * 90)
print("13. DUPLICATE ROW ANALYSIS")
print("=" * 90)

duplicate_mask = raw_df.duplicated(
    keep=False
)

duplicate_count = int(duplicate_mask.sum())

duplicate_groups = raw_df.duplicated(
    keep=False
).sum()

print("Duplicate row instances :", duplicate_count)

if duplicate_count > 0:

    print("\nDuplicate rows:")
    display(
        raw_df.loc[duplicate_mask]
    )

    print(
        "\nNumber of duplicate groups :",
        raw_df.loc[duplicate_mask].duplicated(
            keep=False
        )
    )


# =============================================================================
# 17. DATA TYPE REPORT
# =============================================================================

print("\n" + "=" * 90)
print("14. DATA TYPE REPORT")
print("=" * 90)

dtype_report = pd.DataFrame({
    "Column_Index": range(len(raw_df.columns)),
    "Column": raw_df.columns,
    "Data_Type": [
        str(dtype)
        for dtype in raw_df.dtypes
    ]
})

display(dtype_report)


# =============================================================================
# 18. UNIQUE VALUE INSPECTION
# =============================================================================

print("\n" + "=" * 90)
print("15. UNIQUE VALUE INSPECTION")
print("=" * 90)

for col in raw_df.columns:

    unique_values = raw_df[col].dropna().unique()

    print("\nColumn:", col)
    print("Unique values:", len(unique_values))

    # Display only a reasonable number
    if len(unique_values) <= 20:
        print(unique_values)
    else:
        print(unique_values[:20])
        print("...")


# =============================================================================
# 19. POSSIBLE TITLE / HEADER ROW INSPECTION
# =============================================================================

print("\n" + "=" * 90)
print("16. HEADER / STRUCTURAL ROW INSPECTION")
print("=" * 90)

for i in range(min(10, len(raw_df))):

    print("\nRow", i)
    print(
        raw_df.iloc[i]
        .dropna()
        .to_dict()
    )


# =============================================================================
# 20. RAW DATA SNAPSHOT
# =============================================================================

print("\n" + "=" * 90)
print("17. RAW DATA SNAPSHOT")
print("=" * 90)

raw_snapshot = raw_df.copy()

display(raw_snapshot)


# =============================================================================
# 21. CREATE BASELINE COPY
# =============================================================================

baseline_df = raw_df.copy(deep=True)


# =============================================================================
# 22. BASELINE METRICS
# =============================================================================

baseline_metrics = {
    "Input_File": INPUT_FILE,
    "Sheet": SHEET_NAME,
    "Raw_Rows": raw_df.shape[0],
    "Raw_Columns": raw_df.shape[1],
    "Total_Cells": raw_df.size,
    "Total_Missing_Cells": int(total_missing),
    "Total_Present_Cells": int(total_present),
    "Total_Numeric_Zero_Cells": int(zero_count),
    "Duplicate_Row_Instances": duplicate_count,
    "Completely_Empty_Rows": int(empty_rows.sum()),
    "Completely_Empty_Columns": int(empty_columns.sum()),
    "Numeric_Cells": numeric_count,
    "String_Cells": string_count,
    "Datetime_Cells": datetime_count,
    "Boolean_Cells": boolean_count,
    "Other_Cells": other_count
}

baseline_report = pd.DataFrame(
    [baseline_metrics]
)

print("\n" + "=" * 90)
print("18. RAW DATA BASELINE")
print("=" * 90)

display(baseline_report)


# =============================================================================
# 23. SAVE BASELINE REPORT
# =============================================================================

BASELINE_REPORT = "NPCI_Step1_Raw_Data_Audit_Report.xlsx"

with pd.ExcelWriter(
    BASELINE_REPORT,
    engine="openpyxl"
) as writer:

    baseline_report.to_excel(
        writer,
        sheet_name="Baseline",
        index=False
    )

    column_info.to_excel(
        writer,
        sheet_name="Column_Info",
        index=False
    )

    missing_by_column.to_excel(
        writer,
        sheet_name="Missing_By_Column",
        index=False
    )

    row_missing.to_excel(
        writer,
        sheet_name="Missing_By_Row",
        index=False
    )

    dtype_report.to_excel(
        writer,
        sheet_name="Data_Types",
        index=False
    )


# =============================================================================
# 24. FINAL STEP 1 VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("STEP 1 VALIDATION")
print("=" * 90)

assert raw_df.shape == baseline_df.shape

assert (
    raw_df.isna().sum().sum()
    ==
    baseline_df.isna().sum().sum()
)

assert (
    numeric_raw.eq(0).sum().sum()
    ==
    baseline_df.apply(
        lambda col: pd.to_numeric(
            col,
            errors="coerce"
        )
    ).eq(0).sum().sum()
)

print("✓ Original dataset loaded successfully")
print("✓ Raw dimensions recorded")
print("✓ Missing values measured")
print("✓ Zero values measured")
print("✓ Duplicate rows checked")
print("✓ Data types inspected")
print("✓ Unique values inspected")
print("✓ Baseline established")
print("✓ NO DATA WAS MODIFIED")
print("✓ NO VALUES WERE IMPUTED")
print("✓ NO NaN VALUES WERE REPLACED")
print("✓ NO ZERO VALUES WERE CHANGED")


# =============================================================================
# 25. FINAL REPORT
# =============================================================================

print("\n" + "=" * 90)
print("STEP 1 FINAL REPORT")
print("=" * 90)

display(baseline_report)

print("\n" + "=" * 90)
print("STEP 1 COMPLETE")
print("=" * 90)

print("\nOutput report:")
print(BASELINE_REPORT)

print("\nREADY FOR STEP 2.")

==========================================================================================
STEP 1: RAW DATASET AUDIT
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI-Retail-Payments-Statistics---Excel-Format.xlsx
File size  : 707,627 bytes

==========================================================================================
1. WORKBOOK INFORMATION
==========================================================================================
Number of sheets : 1
Sheet names      : ['Sheet1']

------------------------------------------------------------------------------------------
SHEET: Sheet1
------------------------------------------------------------------------------------------
Rows    : 50
Columns : 42

==========================================================================================
2. RAW SHEET STRUCTURE
==========================================================================================
Selected sheet : Sheet1
Raw rows       : 50
Raw columns    : 42

==========================================================================================
3. FIRST 10 RAW ROWS
==========================================================================================

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RETAIL PAYMENTS STATISTICS ON NPCI PLATFORMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sr. No.,NPCI Operated Systems,FY22-23 Q1,NaN,FY22-23 Q2,NaN,FY22-23 Q3,NaN,FY22-23 Q4,NaN,F.Y-2022-23,NaN,F.Y-2023-24 Q1,NaN,F.Y-2023-24 Q2,NaN,F.Y-2023-24 Q3,NaN,F.Y-2023-24 Q4,NaN,F.Y-2024-25 Q1,NaN,F.Y-2024-25 Q2,NaN,F.Y-2024-25 Q3,NaN,F.Y-2024-25 Q4,NaN,F.Y-2025-26 Q1,NaN,F.Y-2025-26 Q2,NaN,F.Y-2025-26 Q3,NaN,F.Y-2025-26 Q4,NaN,2026-04-01 00:00:00,NaN,2026-05-01 00:00:00,NaN,2026-06-01 00:00:00,NaN
4,NaN,Financial Txns:,Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn)
5,1,NFS - National Financial Switch,1013.772972,4239.737233,1000.45151,4063.901403,1015.517594,4202.804709,988.443205,4117.746292,4018.185281,16624.189636,998.149047,4257.621579,976.72966,4033.830614,985.759856,4168.783237,948.421058,4057.458564,924.526982,4029.910139,897.519953,3809.531659,903.171538,3958.733734,852.43,3820.92,804.835128,3641.815599,793.194452,3520.594486,799.725028,3653.187382,779.03,3652.92,250.74,1192.34,257.84,1208.58,246.624956,1127.487492
6,1.1,NFS - ATM Cash Withdrawal *,1013.194083,4233.880656,999.79525,4057.696968,1014.716752,4195.277034,987.380063,4108.43295,4015.086148,16595.287608,996.995667,4247.492945,975.460207,4023.037268,984.38525,4156.693693,947.015229,4044.760875,923.02043,4016.761614,895.966505,3795.897977,901.597363,3944.105241,850.71,3805.51,803.150913,3625.929087,791.348517,3505.867179,797.894925,3640.462796,777.57,3641.06,250.36,1188.8,257.46,1205.19,246.229058,1124.182163
7,NaN,ATM,965.583013,4057.281658,952.909465,3892.0861,968.193496,4025.487173,943.281486,3942.454156,3829.96746,15917.309086,950.71896,4072.218254,930.425103,3862.889547,939.116627,3989.796972,904.297644,3881.435562,886.84355,3886.092408,861.665272,3681.711944,868.18828,3829.415191,820.56,3698.65,773.712476,3520.443483,762.587166,3407.6769,769.88247,3541.378186,751.78,3543.83,241.88,1156.05,248.72,1171.59,238.178214,1094.502584
8,NaN,Micro-ATM (card+PIN),47.61107,176.598998,46.885785,165.610868,46.523256,169.789861,44.098577,165.978794,185.118688,677.978521,46.276707,175.274691,45.035104,160.147722,45.268623,166.896721,42.717585,163.325313,36.17688,130.669206,34.301233,114.196034,33.409083,114.69005,30.15,106.86,29.438437,105.485604,28.761351,98.190279,28.012455,99.08461,25.79,97.23,8.48,32.75,8.74,33.6,8.050844,29.67958
9,1.2,NFS - Cash deposit transactions,0.578889,5.856577,0.65626,6.204435,0.800842,7.527675,1.063142,9.313341,3.099133,28.902028,1.15338,10.128634,1.269453,10.793346,1.374606,12.089544,1.405829,12.697689,1.506552,13.148524,1.553448,13.633682,1.574175,14.628493,1.72,15.41,1.684215,15.886513,1.845935,14.727307,1.830103,12.724586,1.46,11.86,0.38,3.54,0.38,3.39,0.395898,3.305328

==========================================================================================
4. LAST 10 RAW ROWS
==========================================================================================

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
40,15,eKYC Verification (Successful Txn),69.835093,NaN,86.967733,NaN,86.797157,NaN,96.844405,NaN,340.444388,NaN,100.704858,NaN,126.924549,NaN,118.577173,NaN,121.448672,NaN,107.327961,NaN,123.730323,NaN,112.241133,NaN,117.159865,0,113.724253,NaN,149.507458,0,157.744611,0,158.72505,NaN,50.777543,NaN,55.579376,NaN,59.84,NaN
41,16,Demographic Queries(Authenticated UID),12.746205,NaN,14.425978,NaN,14.29914,NaN,15.882859,NaN,57.354182,NaN,15.464665,NaN,21.628752,NaN,25.279737,NaN,26.75621,NaN,24.75597,NaN,32.86906,NaN,35.310288,NaN,37.780667,0,44.766081,NaN,55.756078,0,38.960434,0,42.801985,NaN,14.683099,NaN,16.05199,NaN,25.41,NaN
42,17,AEPS Tokenization,31.214191,NaN,13.76488,NaN,18.519702,NaN,13.446107,NaN,76.94488,NaN,12.06288,NaN,16.163595,NaN,20.381377,NaN,20.33227,NaN,17.334209,NaN,17.22768,NaN,23.420626,NaN,30.157681,0,38.273793,NaN,67.19309,0,159.011319,0,28.733299,NaN,7.045122,NaN,5.135637,NaN,7.53,NaN
43,18,BBPS (Bill Fetch),1367.39056,NaN,1555.775234,NaN,1630.905386,NaN,1547.534496,NaN,6101.605676,NaN,1735.525411,NaN,2008.040955,NaN,2596.6,NaN,2719.36,NaN,3166.211425,NaN,3751.18,NaN,4063.52,NaN,4076.57,0,4459.85,NaN,4661.77,0,4383.26,0,4327.103473,NaN,1567.15,NaN,1537.99,NaN,1567.378046,NaN
44,26,QSAM,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,0,NaN,0,0,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Total Non Financial Txn (B),2570.044153,NaN,2747.331237,NaN,2843.598827,NaN,2781.632024,0,10942.606241,NaN,3025.066128,0,3482.589994,NaN,4073.789504,NaN,4203.443809,NaN,4635.385735,NaN,5334.684339,NaN,5669.559707,NaN,5693.503902,0,6031.727909,NaN,6404.674051,0,6133.195252,0,5920.994578,NaN,2068.52366,NaN,2048.234706,NaN,2129.237928,NaN
46,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,Total Financial + Non Financial (A+B),25559.87279,75382.917441,27898.625483,76343.637013,30882.282747,82907.074133,32807.864266,87733.386771,117148.645286,322367.015359,36251.455761,91869.44049,40469.473081,94436.483946,44713.784208,102491.806531,48252.077679,109778.171866,52105.626884,112929.045545,56038.363036,114604.770194,61008.499084,124295.397672,63707.147439,128028.549704,67485.370704,130812.391918,72242.795888,131382.095261,75521.889478,141847.86702,77112.013555,148125.533611,26477.348982,50637.102653,27287.223356,50747.182429,27012.54491,2920512.866412
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,* NFS - ATM Cash Withdrawal - includes card+PIN transactions on micro-ATMs and does not include ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

==========================================================================================
5. RAW COLUMN INFORMATION
==========================================================================================

    Column_Index Column_Name  Non_Null_Count  Missing_Count  Unique_Count
0              0           0              31             19            31
1              1           1              44              6            41
2              2           2              43              7            36
3              3           3              32             18            26
4              4           4              44              6            36
5              5           5              32             18            26
6              6           6              44              6            36
7              7           7              32             18            26
8              8           8              42              8            36
9              9           9              33             17            26
10            10          10              42              8            36
11            11          11              32             18            26
12            12          12              43              7            36
13            13          13              33             17            26
14            14          14              43              7            36
15            15          15              32             18            26
16            16          16              42              8            36
17            17          17              32             18            26
18            18          18              39             11            36
19            19          19              28             22            25
20            20          20              39             11            36
21            21          21              29             21            26
22            22          22              40             10            36
23            23          23              28             22            25
24            24          24              39             11            36
25            25          25              28             22            26
26            26          26              45              5            36
27            27          27              43              7            26
28            28          28              44              6            36
29            29          29              32             18            26
30            30          30              38             12            35
31            31          31              36             14            26
32            32          32              44              6            36
33            33          33              42              8            26
34            34          34              42              8            36
35            35          35              32             18            26
36            36          36              40             10            36
37            37          37              30             20            26
38            38          38              38             12            35
39            39          39              28             22            25
40            40          40              38             12            35
41            41          41              28             22            25

==========================================================================================
6. CELL TYPE ANALYSIS
==========================================================================================
Numeric     : 1380
String      : 160
Datetime    : 0
Boolean     : 0
Other       : 6
Missing     : 554

==========================================================================================
7. DATASET-WIDE MISSINGNESS
==========================================================================================
Total cells     : 2100
Missing cells   : 554
Present cells   : 1546
Missing %       : 26.381

==========================================================================================
8. ZERO-VALUE ANALYSIS
==========================================================================================
Numeric zero cells : 151

==========================================================================================
9. COLUMN-WISE MISSINGNESS
==========================================================================================

    Column_Index  Column  Missing_Count  Present_Count  Missing_Percentage
25            25      25             22             28                44.0
23            23      23             22             28                44.0
39            39      39             22             28                44.0
19            19      19             22             28                44.0
41            41      41             22             28                44.0
21            21      21             21             29                42.0
37            37      37             20             30                40.0
0              0       0             19             31                38.0
7              7       7             18             32                36.0
3              3       3             18             32                36.0
29            29      29             18             32                36.0
15            15      15             18             32                36.0
17            17      17             18             32                36.0
35            35      35             18             32                36.0
5              5       5             18             32                36.0
11            11      11             18             32                36.0
13            13      13             17             33                34.0
9              9       9             17             33                34.0
31            31      31             14             36                28.0
40            40      40             12             38                24.0
38            38      38             12             38                24.0
30            30      30             12             38                24.0
18            18      18             11             39                22.0
24            24      24             11             39                22.0
20            20      20             11             39                22.0
22            22      22             10             40                20.0
36            36      36             10             40                20.0
33            33      33              8             42                16.0
16            16      16              8             42                16.0
10            10      10              8             42                16.0
8              8       8              8             42                16.0
34            34      34              8             42                16.0
12            12      12              7             43                14.0
2              2       2              7             43                14.0
27            27      27              7             43                14.0
14            14      14              7             43                14.0
1              1       1              6             44                12.0
4              4       4              6             44                12.0
6              6       6              6             44                12.0
28            28      28              6             44                12.0
32            32      32              6             44                12.0
26            26      26              5             45                10.0

==========================================================================================
10. ROW-WISE MISSINGNESS
==========================================================================================

    Row_Index  Missing_Count  Present_Count  Missing_Percentage
0           0             42              0          100.000000
1           1             41              1           97.619048
2           2             42              0          100.000000
3           3             20             22           47.619048
4           4              1             41            2.380952
5           5              0             42            0.000000
6           6              0             42            0.000000
7           7              1             41            2.380952
8           8              1             41            2.380952
9           9              0             42            0.000000
10         10              1             41            2.380952
11         11             15             27           35.714286
12         12              0             42            0.000000
13         13              0             42            0.000000
14         14              0             42            0.000000
15         15              0             42            0.000000
16         16             14             28           33.333333
17         17             14             28           33.333333
18         18              0             42            0.000000
19         19              0             42            0.000000
20         20              0             42            0.000000
21         21              0             42            0.000000
22         22              0             42            0.000000
23         23              1             41            2.380952
24         24              1             41            2.380952
25         25              1             41            2.380952
26         26              0             42            0.000000
27         27              0             42            0.000000
28         28              0             42            0.000000
29         29              0             42            0.000000
30         30              0             42            0.000000
31         31             15             27           35.714286
32         32              0             42            0.000000
33         33              1             41            2.380952
34         34             39              3           92.857143
35         35             21             21           50.000000
36         36              2             40            4.761905
37         37             17             25           40.476190
38         38             17             25           40.476190
39         39             17             25           40.476190
40         40             17             25           40.476190
41         41             17             25           40.476190
42         42             17             25           40.476190
43         43             17             25           40.476190
44         44             27             15           64.285714
45         45             16             26           38.095238
46         46             35              7           83.333333
47         47              1             41            2.380952
48         48             42              0          100.000000
49         49             41              1           97.619048

==========================================================================================
11. COMPLETELY EMPTY ROW CHECK
==========================================================================================
Completely empty rows : 3
Empty row indices:
[0, 2, 48]

==========================================================================================
12. COMPLETELY EMPTY COLUMN CHECK
==========================================================================================
Completely empty columns : 0

==========================================================================================
13. DUPLICATE ROW ANALYSIS
==========================================================================================
Duplicate row instances : 3

Duplicate rows:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Number of duplicate groups : 0     True
2     True
48    True
dtype: bool

==========================================================================================
14. DATA TYPE REPORT
==========================================================================================

    Column_Index  Column Data_Type
0              0       0    object
1              1       1       str
2              2       2    object
3              3       3    object
4              4       4    object
5              5       5    object
6              6       6    object
7              7       7    object
8              8       8    object
9              9       9    object
10            10      10    object
11            11      11    object
12            12      12    object
13            13      13    object
14            14      14    object
15            15      15    object
16            16      16    object
17            17      17    object
18            18      18    object
19            19      19    object
20            20      20    object
21            21      21    object
22            22      22    object
23            23      23    object
24            24      24    object
25            25      25    object
26            26      26    object
27            27      27    object
28            28      28    object
29            29      29    object
30            30      30    object
31            31      31    object
32            32      32    object
33            33      33    object
34            34      34    object
35            35      35    object
36            36      36    object
37            37      37    object
38            38      38    object
39            39      39    object
40            40      40    object
41            41      41    object

==========================================================================================
15. UNIQUE VALUE INSPECTION
==========================================================================================

Column: 0
Unique values: 31
['RETAIL PAYMENTS STATISTICS ON NPCI PLATFORMS' 'Sr. No.' 1 1.1 1.2 2 2.1
 2.2 2.3 2.4 2.5 3 4 5 6 7 8 9 9.1 9.2]
...

Column: 1
Unique values: 41
<ArrowStringArray>
[                                                    'NPCI Operated Systems',                                                           'Financial Txns:',
                                           'NFS - National Financial Switch',                                               'NFS - ATM Cash Withdrawal *',
                                                                  '     ATM',                                                 '     Micro-ATM (card+PIN)',
                                           'NFS - Cash deposit transactions',                                   'NACH- National Automated Clearing House',
                        '     APBS Credit (Disbursement based on UIDAI No.)',                                                            '     ACH Debit',
                                                           '     ACH Credit',                                                          '     NACH Credit',
                                                           '     NACH Debit',                                    'CTS Cheque Clearing (Processed Volume)',
                                                                     'IMPS ',                                                 'RuPay Card usage at (POS)',
                                                'RuPay Card usage at (eCom)', 'AEPS (Inter Bank) Txn over Micro ATM (e.g. Cash withdrawal/ Cash Deposit)',
                                                         '     Cash Deposit',                                                      '     Cash Withdrawal']
Length: 20, dtype: str
...

Column: 2
Unique values: 36
['FY22-23 Q1' 'Volume (in Mn)' 1013.7729720000001 1013.1940830000001
 965.5830129999999 47.61107 0.578889 0 1228.712854 460.98037400000004
 306.29539500000004 461.437085 178.238833 1412.1408999999999 236.804551
 121.269135 330.28696900000006 0.16321899999999998 322.50230400000004
 7.621446]
...

Column: 3
Unique values: 26
['Value (in Bn)' 4239.737233063 4233.880655962999 4057.28165765
 176.598998313 5.8565771 0 6715.88383763017 751.42469027078
 2867.13916947963 3097.31997787976 18554.3119 13407.740082353 431.59018927
 196.33091176599999 913.305820452 0.562707005 889.6892568640001
 23.053856582999998 403.02161458700004]
...

Column: 4
Unique values: 36
['FY22-23 Q2' 'Volume (in Mn)' 1000.4515099999999 999.7952499999999
 952.909465 46.885785 0.6562600000000001 0 1233.523492 359.282137
 327.852331 546.3890240000001 176.152425 1390.4307860000001 219.541625
 104.98778300000001 318.79332100000005 0.174209 312.916176 5.702936]
...

Column: 5
Unique values: 26
['Value (in Bn)' 4063.901402761 4057.6969678610003 3892.086099721
 165.61086814 6.2044349 0 7053.52749681711 349.79597789974
 3072.42161895543 3631.3098999619397 17179.757544 13455.867464292001
 399.840394724 213.954035652 840.508824241 0.568061315 822.403373419
 17.537389507 487.53120235]
...

Column: 6
Unique values: 36
['FY22-23 Q3' 'Volume (in Mn)' 1015.517594 1014.716752 968.1934960000001
 46.523256 0.800842 0 1191.4535500000002 406.70350900000005 350.267541
 434.4825000000001 176.365409 1431.77177 211.714655 93.930481 308.543608
 0.142886 303.53677400000004 4.863948]
...

Column: 7
Unique values: 26
['Value (in Bn)' 4202.804708709 4195.277033509 4025.4871728 169.789860709
 7.5276752 0 8135.776399038001 555.918342846 3313.469966788 4266.388089404
 17561.944767 14073.125201908002 416.32406826400006 203.83770778399997
 831.425256667 0.494838884 814.872691143 16.05772664 499.15514583399994]
...

Column: 8
Unique values: 36
['FY22-23 Q4' 'Volume (in Mn)' 988.443205 987.3800630000001
 943.2814860000001 44.098577 1.063142 0 1405.7423359999998 556.431004
 365.849646 483.461686 176.948041 1419.381274 192.13095600000003 82.636995
 300.576223 0.16103800000000001 296.554573 3.860612]
...

Column: 9
Unique values: 26
['Value (in Bn)' 4117.746291683 4108.432950483 3942.4541562
 165.97879428299998 9.3133412 0 8787.99209923 818.2417534230001
 3549.156760651 4420.593585156001 18374.3816 14924.737416649
 384.97853955200003 198.99634072700002 832.393899206 0.552202571
 817.0121983280001 14.829498307000001 516.357813263]
...

Column: 10
Unique values: 36
['F.Y-2022-23' 'Volume (in Mn)' 4018.185281 4015.086148 3829.96746
 185.118688 3.099133 0 5059.432232 1783.397024 1350.264913
 1925.7702950000003 707.704708 5653.724730000001 860.191787
 402.82439400000004 1258.200121 0.6413519999999999 1235.509827 22.048942]
...

Column: 11
Unique values: 26
['Value (in Bn)' 16624.189636216 16595.287607815997 15917.309086371
 677.978521445 28.9020284 0 30693.17983271528 2475.38076443952
 12802.187515874059 15415.6115524017 71670.395811 55861.470165202
 1632.73319181 813.118995929 3417.633800566 2.177809775 3343.9775197540002
 71.47847103699999 1906.065776034]
...

Column: 12
Unique values: 36
['F.Y-2023-24 Q1' 'Volume (in Mn)' 998.149047 996.9956669999999 950.71896
 46.276707 1.1533799999999998 0 1214.139028 478.113599 382.821623
 353.203806 166.68179 1451.609084 186.61078700000002 72.855615 297.39037
 0.16662 292.424374 4.7993760000000005]
...

Column: 13
Unique values: 26
['Value (in Bn)' 4257.621579033999 4247.492945234 4072.21825395
 175.274691284 10.128633800000001 0 7992.754220524001 769.420572048
 3730.1991786520002 3493.134469824 18467.683430999998 15279.071175444
 395.07009611499996 187.05156570699998 842.12533996 0.57716443
 824.467073767 17.081101763 586.0318734570001]
...

Column: 14
Unique values: 36
['F.Y-2023-24 Q2' 'Volume (in Mn)' 976.72966 975.460207 930.425103
 45.035104000000004 1.269453 0 1499.1313930000001 645.578626
 407.30740999999995 446.245357 165.92000000000002 1451.774536 175.936996
 68.420925 317.245313 0.337129 312.572861 4.335323]
...

Column: 15
Unique values: 26
['Value (in Bn)' 4033.830614165 4023.037268465 3862.889546917
 160.147721548 10.7933457 0 8345.376904832381 834.05109823916
 4028.64079819583 3482.6850083973895 17556.53 15340.96180547 372.508014791
 202.991912144 829.5558582599999 1.2756372759999999 814.496864779
 13.783356205 709.122270673]
...

Column: 16
Unique values: 36
['F.Y-2023-24 Q3' 'Volume (in Mn)' 985.759856 984.3852499999999
 939.1166269999999 45.268623 1.374606 0 1464.6446230000001
 654.7325830000001 412.844386 397.06765400000006 163.266723 1464.056086
 171.153548 66.350849 304.932221 0.46299700000000005 299.56137 4.907854]
...

Column: 17
Unique values: 26
['Value (in Bn)' 4168.783236907 4156.693693007001 3989.7969721130003
 166.896720894 12.0895439 0 9284.44179407298 943.1527273800501
 4319.24092258809 4022.04814410484 17362.917074729638 16433.6625466959
 400.89108645760007 243.83765878792997 807.7525561509999
 1.7879513740000001 789.423933244 16.540671533 837.9100000000001]
...

Column: 18
Unique values: 36
['F.Y-2023-24 Q4' 'Volume (in Mn)' 948.4210579999999 947.015229 904.297644
 42.717585 1.4058290000000002 1675.740021 809.9064099999999
 390.47934599999996 475.362895 167.438501 1624.0645800000002 160.985256
 65.441451 277.48247 0.5388539999999999 271.147844 5.805772
 389.83000000000004]
...

Column: 19
Unique values: 25
['Value (in Bn)' 4057.458564105 4044.7608748049997 3881.4355619159996
 163.32531288899997 12.697689299999999 10321.812441345179
 1358.9168815471899 4449.10120563865 4513.79299815934 18750.28347100504
 17691.07531722945 383.14501520135 263.65466435976 730.599545646
 2.163410004 711.973282173 16.452853469 936.27 56473.06524986097]
...

Column: 20
Unique values: 36
['F.Y-2024-25 Q1' 'Volume (in Mn)' 924.526982 923.02043 886.84355 36.17688
 1.5065520000000001 0 1568.815412 776.021874 457.819124 334.974414
 153.458268 1624.8138210000002 160.018077 62.812966 284.133916 0.686569
 277.262615 6.184732]
...

Column: 21
Unique values: 26
['Value (in Bn)' 4029.9101388589997 4016.7616144589992 3886.092408382
 130.669206077 13.1485244 0 9814.279670509244 1181.3358932587678
 4952.844552095017 3680.0992251554608 18331.81059799433 17762.39640435809
 405.76632653151995 276.69969763374 737.109678204 2.764333452
 717.324004277 17.021340475000002 1233.44664766406]
...

Column: 22
Unique values: 36
['F.Y-2024-25 Q2' 'Volume (in Mn)' 897.519953 895.966505 861.665272
 34.301233 1.553448 1714.000065 760.704669 486.089567 467.205829
 152.438696 1373.5574139999999 167.171629 64.923203 296.240541 1.226781
 289.232656 5.791104 627.35]
...

Column: 23
Unique values: 25
['Value (in Bn)' 3809.5316593420002 3795.8979773420006 3681.7119438070004
 114.196033535 13.633682 10294.552225755451 994.3782873809905
 5313.453614574128 3986.720323800335 17229.19628241764 17362.97173782068
 399.10800581237993 331.76368730156 730.374454807 4.5620354039999995
 708.220344145 17.582075258 2388.96 61890.22672821378]
...

Column: 24
Unique values: 36
['F.Y-2024-25 Q3' 'Volume (in Mn)' 903.171538 901.5973630000001 868.18828
 33.409082999999995 1.574175 1812.3695980000002 872.42624
 518.1463940000001 421.796964 152.603435 1315.903284 180.58013799999998
 64.03639000000001 311.616738 1.7705230000000003 303.655978 6.190237
 715.87]
...

Column: 25
Unique values: 26
['Value (in Bn)' 3958.733733835 3944.1052410350003 3829.4151908619997
 114.690050173 14.6284928 11720.118800726454 1602.4607127995382
 5712.073524531202 4405.594563395713 17497.84890709685 17892.582664952548
 431.25900323287 369.40910418864996 803.564068482 7.035731942
 776.565704178 19.962632362 3136.5200000000004 68297.08763334136]
...

Column: 26
Unique values: 36
['F.Y-2024-25 Q4' 'Volume (in Mn)' 852.4300000000001 850.71 820.56 30.15
 1.7200000000000002 0 1871.371226 887.2900850000001 514.171778 469.909363
 151.036135 1310.690666 179.577167 59.459083 301.39608599999997 2.299571
 293.899464 5.197051]
...

Column: 27
Unique values: 26
['Value (in Bn)' 3820.92 3805.51 3698.6500000000005 106.86000000000001
 15.41 0 12406.876020573687 1762.175222939496 6014.898511485037
 4629.802286149156 18074.63171238009 18373.146560777 408.56391297748
 359.54201170177004 789.74530329092 9.232956942000001 764.1156384999999
 16.39670784892 3377.57]
...

Column: 28
Unique values: 36
['F.Y-2025-26 Q1' 'Volume (in Mn)' 804.8351279999999 803.150913
 773.7124759999999 29.438437 1.684215 0 1717.026209 823.8632620000001
 516.136366 377.03658099999996 142.41107 1361.016789 183.475663
 58.197506000000004 297.136215 2.5025830000000004 289.01665299999996
 5.596979]
...

Column: 29
Unique values: 26
['Value (in Bn)' 3641.815599292 3625.929086592 3520.443482616
 105.48560397600001 15.8865127 0 12063.19562301248 1567.9765247020916
 6132.713513479046 4362.505584831342 17914.93934719916 18688.89675379719
 412.53852732613996 360.35475987965003 819.3749158937701 10.570613686
 789.7603782890001 19.05392391877 3572.92]
...

Column: 30
Unique values: 35
['F.Y-2025-26 Q2' 'Volume (in Mn)' 793.194452 791.3485169999999 762.587166
 28.761350999999998 1.8459349999999999 1958.899451 906.497779 530.426363
 533.310795 140.548097 1353.830544 193.41616399999998 64.519556 337.243745
 3.001653 327.742559 6.499533 771.7700000000001]
...

Column: 31
Unique values: 26
['Value (in Bn)' 3520.594486042 3505.867178742 3407.6768998710004
 98.190278871 14.7273073 11856.80313359519 1502.5134372692596
 6532.971580423133 4606.657255881081 17179.94836619452 18258.07000886978
 400.24737696372995 428.7554762608801 862.9736547501001 12.396631828
 830.8672677100001 19.7097552121 3832.942621 74837.075325207]
...

Column: 32
Unique values: 36
['F.Y-2025-26 Q3' 'Volume (in Mn)' 799.7250280000001 797.8949250000001
 769.88247 28.012454999999996 1.8301030000000003 0 1865.257739 847.872431
 550.611799 466.773509 137.71248599999998 1152.454729 196.345754
 63.48420399999999 314.940986 3.2178699999999996 305.936969 5.786147]
...

Column: 33
Unique values: 26
['Value (in Bn)' 3653.18738182 3640.4627959200006 3541.378185942
 99.084609978 12.7245859 0 13816.517713197645 1940.596382144151
 6904.428126044633 4971.49320500886 17651.57752168837 19195.923592503044
 440.5478924752 406.76111426916 840.90797312395 13.659593488999999
 808.195578527 19.052801107949982 4061.13]
...

Column: 34
Unique values: 36
['F.Y-2025-26 Q4' 'Volume (in Mn)' 779.03 777.5699999999999 751.78 25.79
 1.46 0 1822.754293 807.187469 564.243373 451.323451 138.10953700000002
 1075.80216 195.984261 63.347204000000005 299.263397 3.718845 289.938392
 5.60616]
...

Column: 35
Unique values: 26
['Value (in Bn)' 3652.92 3641.0600000000004 3543.83 97.22999999999999
 11.86 0 14546.094930070614 2159.3226232915895 7304.489583283437
 5082.282723495588 18729.21492939938 20556.395486384998 428.23319501111
 411.97075557005996 836.0641784955001 16.175657862 798.614016495
 21.274504112499997 4040.626966269]
...

Column: 36
Unique values: 36
[datetime.datetime(2026, 4, 1, 0, 0) 'Volume (in Mn)' 250.73999999999998
 250.35999999999999 241.88 8.48 0.38 528.657497 237.204371 188.327758
 103.125368 0 45.429866 362.486443 67.6419 21.464967 93.7675 1.23446
 90.380973 2.152067]
...

Column: 37
Unique values: 26
['Value (in Bn)' 1192.34 1188.8 1156.05 32.75 3.54 4528.350756569172
 446.2522470642171 2406.869860277345 1675.2286492276096 0 6931.89626993367
 7009.091703002501 147.05955465065995 135.94248521628998 276.3261923062
 5.522322606 262.139834599 8.664035101200001 1312.99]
...

Column: 38
Unique values: 35
[datetime.datetime(2026, 5, 1, 0, 0) 'Volume (in Mn)' 257.84 257.46 248.72
 8.74 0.38 468.60747100000003 204.836701 189.722169 74.048601 41.939408
 358.09821 69.179107 22.650576 88.420414 1.201742 84.465719 2.752953
 270.750586]
...

Column: 39
Unique values: 25
['Value (in Bn)' 1208.58 1205.1899999999998 1171.59 33.6 3.39
 4626.120322850117 621.3610014865922 2458.491280363525 1546.268041
 5968.35298061909 6957.013261962269 143.11370473951 144.82312189976
 252.38796323484 5.274593823 237.293268712 9.82010069984 1466.273467801
 29904.242099654577]
...

Column: 40
Unique values: 35
[datetime.datetime(2026, 6, 1, 0, 0) 'Volume (in Mn)' 246.624956
 246.229058 238.178214 8.050844 0.395898 625.694103 315.163749 191.295707
 119.234647 42.552576 353.91650599999986 69.67383799999999
 21.812879000000002 97.31 1.24 92.82 3.25 263.143864]
...

Column: 41
Unique values: 25
['Value (in Bn)' 1127.4874915130001 1124.182163313 1094.502583784
 29.679579529 3.3053282 4921.6486382 626.5313452 2590.761284 1704.356009
 6078.433797 6765.429926442802 140.12780594412996 136.25577560601 260.47
 5.44 244.11 10.92 1422.648391286 2892138.668339435]
...

==========================================================================================
16. HEADER / STRUCTURAL ROW INSPECTION
==========================================================================================

Row 0
{}

Row 1
{0: 'RETAIL PAYMENTS STATISTICS ON NPCI PLATFORMS'}

Row 2
{}

Row 3
{0: 'Sr. No.', 1: 'NPCI Operated Systems', 2: 'FY22-23 Q1', 4: 'FY22-23 Q2', 6: 'FY22-23 Q3', 8: 'FY22-23 Q4', 10: 'F.Y-2022-23', 12: 'F.Y-2023-24 Q1', 14: 'F.Y-2023-24 Q2', 16: 'F.Y-2023-24 Q3', 18: 'F.Y-2023-24 Q4', 20: 'F.Y-2024-25 Q1', 22: 'F.Y-2024-25 Q2', 24: 'F.Y-2024-25 Q3', 26: 'F.Y-2024-25 Q4', 28: 'F.Y-2025-26 Q1', 30: 'F.Y-2025-26 Q2', 32: 'F.Y-2025-26 Q3', 34: 'F.Y-2025-26 Q4', 36: datetime.datetime(2026, 4, 1, 0, 0), 38: datetime.datetime(2026, 5, 1, 0, 0), 40: datetime.datetime(2026, 6, 1, 0, 0)}

Row 4
{1: 'Financial Txns:', 2: 'Volume (in Mn)', 3: 'Value (in Bn)', 4: 'Volume (in Mn)', 5: 'Value (in Bn)', 6: 'Volume (in Mn)', 7: 'Value (in Bn)', 8: 'Volume (in Mn)', 9: 'Value (in Bn)', 10: 'Volume (in Mn)', 11: 'Value (in Bn)', 12: 'Volume (in Mn)', 13: 'Value (in Bn)', 14: 'Volume (in Mn)', 15: 'Value (in Bn)', 16: 'Volume (in Mn)', 17: 'Value (in Bn)', 18: 'Volume (in Mn)', 19: 'Value (in Bn)', 20: 'Volume (in Mn)', 21: 'Value (in Bn)', 22: 'Volume (in Mn)', 23: 'Value (in Bn)', 24: 'Volume (in Mn)', 25: 'Value (in Bn)', 26: 'Volume (in Mn)', 27: 'Value (in Bn)', 28: 'Volume (in Mn)', 29: 'Value (in Bn)', 30: 'Volume (in Mn)', 31: 'Value (in Bn)', 32: 'Volume (in Mn)', 33: 'Value (in Bn)', 34: 'Volume (in Mn)', 35: 'Value (in Bn)', 36: 'Volume (in Mn)', 37: 'Value (in Bn)', 38: 'Volume (in Mn)', 39: 'Value (in Bn)', 40: 'Volume (in Mn)', 41: 'Value (in Bn)'}

Row 5
{0: 1, 1: 'NFS - National Financial Switch', 2: 1013.7729720000001, 3: 4239.737233063, 4: 1000.4515099999999, 5: 4063.901402761, 6: 1015.517594, 7: 4202.804708709, 8: 988.443205, 9: 4117.746291683, 10: 4018.185281, 11: 16624.189636216, 12: 998.149047, 13: 4257.621579033999, 14: 976.72966, 15: 4033.830614165, 16: 985.759856, 17: 4168.783236907, 18: 948.4210579999999, 19: 4057.458564105, 20: 924.526982, 21: 4029.9101388589997, 22: 897.519953, 23: 3809.5316593420002, 24: 903.171538, 25: 3958.733733835, 26: 852.4300000000001, 27: 3820.92, 28: 804.8351279999999, 29: 3641.815599292, 30: 793.194452, 31: 3520.594486042, 32: 799.7250280000001, 33: 3653.18738182, 34: 779.03, 35: 3652.92, 36: 250.73999999999998, 37: 1192.34, 38: 257.84, 39: 1208.58, 40: 246.624956, 41: 1127.4874915130001}

Row 6
{0: 1.1, 1: 'NFS - ATM Cash Withdrawal *', 2: 1013.1940830000001, 3: 4233.880655962999, 4: 999.7952499999999, 5: 4057.6969678610003, 6: 1014.716752, 7: 4195.277033509, 8: 987.3800630000001, 9: 4108.432950483, 10: 4015.086148, 11: 16595.287607815997, 12: 996.9956669999999, 13: 4247.492945234, 14: 975.460207, 15: 4023.037268465, 16: 984.3852499999999, 17: 4156.693693007001, 18: 947.015229, 19: 4044.7608748049997, 20: 923.02043, 21: 4016.7616144589992, 22: 895.966505, 23: 3795.8979773420006, 24: 901.5973630000001, 25: 3944.1052410350003, 26: 850.71, 27: 3805.51, 28: 803.150913, 29: 3625.929086592, 30: 791.3485169999999, 31: 3505.867178742, 32: 797.8949250000001, 33: 3640.4627959200006, 34: 777.5699999999999, 35: 3641.0600000000004, 36: 250.35999999999999, 37: 1188.8, 38: 257.46, 39: 1205.1899999999998, 40: 246.229058, 41: 1124.182163313}

Row 7
{1: '     ATM', 2: 965.5830129999999, 3: 4057.28165765, 4: 952.909465, 5: 3892.086099721, 6: 968.1934960000001, 7: 4025.4871728, 8: 943.2814860000001, 9: 3942.4541562, 10: 3829.96746, 11: 15917.309086371, 12: 950.71896, 13: 4072.21825395, 14: 930.425103, 15: 3862.889546917, 16: 939.1166269999999, 17: 3989.7969721130003, 18: 904.297644, 19: 3881.4355619159996, 20: 886.84355, 21: 3886.092408382, 22: 861.665272, 23: 3681.7119438070004, 24: 868.18828, 25: 3829.4151908619997, 26: 820.56, 27: 3698.6500000000005, 28: 773.7124759999999, 29: 3520.443482616, 30: 762.587166, 31: 3407.6768998710004, 32: 769.88247, 33: 3541.378185942, 34: 751.78, 35: 3543.83, 36: 241.88, 37: 1156.05, 38: 248.72, 39: 1171.59, 40: 238.178214, 41: 1094.502583784}

Row 8
{1: '     Micro-ATM (card+PIN)', 2: 47.61107, 3: 176.598998313, 4: 46.885785, 5: 165.61086814, 6: 46.523256, 7: 169.789860709, 8: 44.098577, 9: 165.97879428299998, 10: 185.118688, 11: 677.978521445, 12: 46.276707, 13: 175.274691284, 14: 45.035104000000004, 15: 160.147721548, 16: 45.268623, 17: 166.896720894, 18: 42.717585, 19: 163.32531288899997, 20: 36.17688, 21: 130.669206077, 22: 34.301233, 23: 114.196033535, 24: 33.409082999999995, 25: 114.690050173, 26: 30.15, 27: 106.86000000000001, 28: 29.438437, 29: 105.48560397600001, 30: 28.761350999999998, 31: 98.190278871, 32: 28.012454999999996, 33: 99.084609978, 34: 25.79, 35: 97.22999999999999, 36: 8.48, 37: 32.75, 38: 8.74, 39: 33.6, 40: 8.050844, 41: 29.679579529}

Row 9

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RETAIL PAYMENTS STATISTICS ON NPCI PLATFORMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sr. No.,NPCI Operated Systems,FY22-23 Q1,NaN,FY22-23 Q2,NaN,FY22-23 Q3,NaN,FY22-23 Q4,NaN,F.Y-2022-23,NaN,F.Y-2023-24 Q1,NaN,F.Y-2023-24 Q2,NaN,F.Y-2023-24 Q3,NaN,F.Y-2023-24 Q4,NaN,F.Y-2024-25 Q1,NaN,F.Y-2024-25 Q2,NaN,F.Y-2024-25 Q3,NaN,F.Y-2024-25 Q4,NaN,F.Y-2025-26 Q1,NaN,F.Y-2025-26 Q2,NaN,F.Y-2025-26 Q3,NaN,F.Y-2025-26 Q4,NaN,2026-04-01 00:00:00,NaN,2026-05-01 00:00:00,NaN,2026-06-01 00:00:00,NaN
4,NaN,Financial Txns:,Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn)
5,1,NFS - National Financial Switch,1013.772972,4239.737233,1000.45151,4063.901403,1015.517594,4202.804709,988.443205,4117.746292,4018.185281,16624.189636,998.149047,4257.621579,976.72966,4033.830614,985.759856,4168.783237,948.421058,4057.458564,924.526982,4029.910139,897.519953,3809.531659,903.171538,3958.733734,852.43,3820.92,804.835128,3641.815599,793.194452,3520.594486,799.725028,3653.187382,779.03,3652.92,250.74,1192.34,257.84,1208.58,246.624956,1127.487492
6,1.1,NFS - ATM Cash Withdrawal *,1013.194083,4233.880656,999.79525,4057.696968,1014.716752,4195.277034,987.380063,4108.43295,4015.086148,16595.287608,996.995667,4247.492945,975.460207,4023.037268,984.38525,4156.693693,947.015229,4044.760875,923.02043,4016.761614,895.966505,3795.897977,901.597363,3944.105241,850.71,3805.51,803.150913,3625.929087,791.348517,3505.867179,797.894925,3640.462796,777.57,3641.06,250.36,1188.8,257.46,1205.19,246.229058,1124.182163
7,NaN,ATM,965.583013,4057.281658,952.909465,3892.0861,968.193496,4025.487173,943.281486,3942.454156,3829.96746,15917.309086,950.71896,4072.218254,930.425103,3862.889547,939.116627,3989.796972,904.297644,3881.435562,886.84355,3886.092408,861.665272,3681.711944,868.18828,3829.415191,820.56,3698.65,773.712476,3520.443483,762.587166,3407.6769,769.88247,3541.378186,751.78,3543.83,241.88,1156.05,248.72,1171.59,238.178214,1094.502584
8,NaN,Micro-ATM (card+PIN),47.61107,176.598998,46.885785,165.610868,46.523256,169.789861,44.098577,165.978794,185.118688,677.978521,46.276707,175.274691,45.035104,160.147722,45.268623,166.896721,42.717585,163.325313,36.17688,130.669206,34.301233,114.196034,33.409083,114.69005,30.15,106.86,29.438437,105.485604,28.761351,98.190279,28.012455,99.08461,25.79,97.23,8.48,32.75,8.74,33.6,8.050844,29.67958
9,1.2,NFS - Cash deposit transactions,0.578889,5.856577,0.65626,6.204435,0.800842,7.527675,1.063142,9.313341,3.099133,28.902028,1.15338,10.128634,1.269453,10.793346,1.374606,12.089544,1.405829,12.697689,1.506552,13.148524,1.553448,13.633682,1.574175,14.628493,1.72,15.41,1.684215,15.886513,1.845935,14.727307,1.830103,12.724586,1.46,11.86,0.38,3.54,0.38,3.39,0.395898,3.305328
10,NaN,ATM,0.578889,5.856577,0.65626,6.204435,0.800842,7.527675,1.063142,9.313341,3.099133,28.902028,1.15338,10.128634,1.269453,10.793346,1.374606,12.089544,1.405829,12.697689,1.506552,13.148524,1.553448,13.633682,1.574175,14.628493,1.72,15.41,1.684215,15.886513,1.845935,14.727307,1.830103,12.724586,1.46,11.86,0.38,3.54,0.38,3.39,0.395898,3.305328
11,NaN,Micro-ATM (card+PIN),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
12,2,NACH- National Automated Clearing House,1228.712854,6715.883838,1233.523492,7053.527497,1191.45355,8135.776399,1405.742336,8787.992099,5059.432232,30693.179833,1214.139028,7992.754221,1499.131393,8345.376905,1464.644623,9284.441794,1675.740021,10321.812441,1568.815412,9814.279671,1714.000065,10294.552226,1812.369598,11720.118801,1871.371226,12406.876021,1717.026209,12063.195623,1958.899451,11856.803134,1865.257739,13816.517713,1822.754293,14546.09493,528.657497,4528.350757,468.607471,4626.120323,625.694103,4921.648638
13,2.1,APBS Credit (Disbursement based on UIDAI No.),460.980374,751.42469,359.282137,349.795978,406.703509,555.918343,556.431004,818.241753,1783.397024,2475.380764,478.113599,769.420572,645.578626,834.051098,654.732583,943.152727,809.90641,1358.916882,776.021874,1181.335893,760.704669,994.378287,872.42624,1602.460713,887.290085,1762.175223,823.863262,1567.976525,906.497779,1502.513437,847.872431,1940.596382,807.187469,2159.322623,237.204371,446.252247,204.836701,621.361001,315.163749,626.531345
14,2.2,ACH Debit,306.295395,2867.139169,327.852331,3072.421619,350.267541,3313.469967,365.849646,3549.156761,1350.264913,12802.187516,382.821623,3730.199179,407.30741,4028.640798,412.844386,4319.240923,390.479346,4449.101206,457.819124,4952.844552,486.089567,5313.453615,518.146394,5712.073525,514.171778,6014.898511,516.136366,6132.713513,530.426363,6532.97158,550.611799,6904.428126,564.243373,7304.489583,188.327758,2406.86986,189.722169,2458.49128,191.295707,2590.761284
15,2.3,ACH Credit,461.437085,3097.319978,546.389024,3631.3099,434.4825,4266.388089,483.461686,4420.593585,1925.770295,15415.611552,353.203806,3493.13447,446.245357,3482.685008,397.067654,4022.048144,475.362895,4513.792998,334.974414,3680.099225,467.205829,3986.720324,421.796964,4405.594563,469.909363,4629.802286,377.036581,4362.505585,533.310795,4606.657256,466.773509,4971.493205,451.323451,5082.282723,103.125368,1675.228649,74.048601,1546.268041,119.234647,1704.356009
16,2.4,NACH Credit,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN
17,2.5,NACH Debit,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,0,0,NaN,NaN,NaN,NaN
18,3,CTS Cheque Clearing (Processed Volume),178.238833,18554.3119,176.152425,17179.757544,176.365409,17561.944767,176.948041,18374.3816,707.704708,71670.395811,166.68179,18467.683431,165.92,17556.53,163.266723,17362.917075,167.438501,18750.283471,153.458268,18331.810598,152.438696,17229.196282,152.603435,17497.848907,151.036135,18074.631712,142.41107,17914.939347,140.548097,17179.948366,137.712486,17651.577522,138.109537,18729.214929,45.429866,6931.89627,41.939408,5968.352981,42.552576,6078.433797
19,4,IMPS,1412.1409,13407.740082,1390.430786,13455.867464,1431.77177,14073.125202,1419.381274,14924.737417,5653.72473,55861.470165,1451.609084,15279.071175,1451.774536,15340.961805,1464.056086,16433.662547,1624.06458,17691.075317,1624.813821,17762.396404,1373.557414,17362.971738,1315.903284,17892.582665,1310.690666,18373.146561,1361.016789,18688.896754,1353.830544,18258.070009,1152.454729,19195.923593,1075.80216,20556.395486,362.486443,7009.091703,358.09821,6957.013262,353.916506,6765.429926
20,5,RuPay Card usage at (POS),236.804551,431.590189,219.541625,399.840395,211.714655,416.324068,192.130956,384.97854,860.191787,1632.733192,186.610787,395.070096,175.936996,372.508015,171.153548,400.891086,160.985256,383.145015,160.018077,405.766327,167.171629,399.108006,180.580138,431.259003,179.577167,408.563913,183.475663,412.538527,193.416164,400.247377,196.345754,440.547892,195.984261,428.233195,67.6419,147.059555,69.179107,143.113705,69.673838,140.127806
21,6,RuPay Card usage at (eCom),121.269135,196.330912,104.987783,213.954036,93.930481,203.837708,82.636995,198.996341,402.824394,813.118996,72.855615,187.051566,68.420925,202.991912,66.350849,243.837659,65.441451,263.654664,62.812966,276.699698,64.923203,331.763687,64.03639,369.409104,59.459083,359.542012,58.197506,360.35476,64.519556,428.755476,63.484204,406.761114,63.347204,411.970756,21.464967,135.942485,22.650576,144.823122,21.812879,136.255776
22,7,AEPS (Inter Bank) Txn over Micro ATM (e.g. Cash withdrawal/ Cash Deposit),330.286969,913.30582,318.793321,840.508824,308.543608,831.425257,300.576223,832.393899,1258.200121,3417.633801,297.39037,842.12534,317.245313,829.555858,304.932221,807.752556,277.48247,730.599546,284.133916,737.109678,296.240541,730.374455,311.616738,803.564068,301.396086,789.745303,297.136215,819.374916,337.243745,862.973655,314.940986,840.907973,299.263397,836.064178,93.7675,276.326192,88.420414,252.387963,97.31,260.47
23,NaN,Cash Deposit,0.163219,0.562707,0.174209,0.568061,0.142886,0.494839,0.161038,0.552203,0.641352,2.17781,0.16662,0.577164,0.337129,1.275637,0.462997,1.787951,0.538854,2.16341,0.686569,2.764333,1.226781,4.562035,1.770523,7.035732,2.299571,9.232957,2.502583,10.570614,3.001653,12.396632,3.21787,13.659593,3.718845,16.175658,1.23446,5.522323,1.201742,5.274594,1.24,5.44
24,NaN,Cash Withdrawal,322.502304,889.689257,312.916176,822.403373,303.536774,814.872691,296.554573,817.012198,1235.509827,3343.97752,292.424374,824.467074,312.572861,814.496865,299.56137,789.423933,271.147844,711.973282,277.262615,717.324004,289.232656,708.220344,303.655978,776.565704,293.899464,764.115638,289.016653,789.760378,327.742559,830.867268,305.936969,808.195579,289.938392,798.614016,90.380973,262.139835,84.465719,237.293269,92.82,244.11
25,NaN,"Others - Funds Transfer, Bhim Aadhaar Pay",7.621446,23.053857,5.702936,17.53739,4.863948,16.057727,3.860612,14.829498,22.048942,71.478471,4.799376,17.081102,4.335323,13.783356,4.907854,16.540672,5.805772,16.452853,6.184732,17.02134,5.791104,17.582075,6.190237,19.962632,5.197051,16.396708,5.596979,19.053924,6.499533,19.709755,5.786147,19.052801,5.60616,21.274504,2.152067,8.664035,2.752953,9.820101,3.25,10.92
26,8,BBPS (Bill Payment passing through BBPCU),238.312139,403.021615,262.315357,487.531202,288.411949,499.155146,307.90183,516.357813,1096.941275,1906.065776,306.837454,586.031873,323.408035,709.122271,367.08,837.91,389.83,936.27,456.81372,1233.446648,627.35,2388.96,715.87,3136.52,740.65,3377.57,750.36,3572.92,771.77,3832.942621,787.148587,4061.13,790.876659,4040.626966,258.14,1312.99,270.750586,1466.273468,263.143864,1422.648391
27,9,UPI - Unified Payments Interface,17401.002975,30392.086723,19648.828359,32522.225419,22444.35938,36842.308972,24256.945184,39450.162568,83751.135898,139206.783683,27648.386639,43716.173163,31106.307424,46893.149376,34664.301927,52784.583831,37745.698423,56473.06525,41224.974778,60164.827486,44440.346333,61890.226728,48796.999624,68297.087633,51403.703174,70217.404183,54965.885852,73131.536984,59109.686886,74837.075325,62802.564453,81561.360472,64738.740746,84702.525701,22346.796247,29029.880524,23201.927624,29904.2421,22716.068278,2892138.668339
28,9.1,BHIM,74.573298,254.035051,74.165879,239.414776,75.498081,250.131659,71.373805,227.665351,295.611063,971.246837,69.283583,217.971461,72.910148,239.225501,72.783075,244.62419,115.651867,261.094592,76.627123,8476.877097,84.234878,261.175163,96.556536,281.947826,133.427521,281.918192,209.851946,344.192257,322.938542,472.903429,448.019193,597.066153,577.586467,693.896739,215.518702,253.16988,233.451301,261.474474,230.12559,25744.202748
29,9.2,USSD 2.0,0.284314,0.384822,0.471649,0.51609,0.496796,0.548478,0.480739,0.54496,1.733498,1.99435,0.556955,0.698888,0.789154,1.207505,0.738153,1.008637,0.534263,0.60742,0.454325,0.493186,0.414877,0.437975,0.476751,0.495716,0.378424,0.403098,0.179585,0.191749,0.239429,0.249201,0.221985,0.245082,0.346924,0.366925,0.115029,0.118953,0.128146,0.127771,0.127967,12.73741
30,9.3,UPI excluding BHIM & USSD,17326.145363,30137.66685,19574.190831,32282.294554,22368.364503,36591.628835,24185.09064,39221.952257,83453.791337,138233.542496,27578.546101,43497.502814,31032.608122,46652.71637,34590.780699,52538.951004,37629.512293,56211.363238,41147.89333,51687.457203,44355.696578,61628.613589,48699.966337,68118.682705,51269.897229,69935.082892,54755.854321,72787.152978,58786.508915,74363.922695,62354.323275,80964.049236,64160.807355,84008.262036,22131.162516,28776.591692,22968.348177,29642.639855,22485.814721,2866381.728181
31,10,USSD 1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,0,0,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
32,11,NETC,829.287309,128.90913,796.269588,126.523229,876.615524,140.371905,895.526198,145.640203,3397.698619,541.444467,883.729819,145.858046,902.008805,152.45719,988.448871,167.026746,993.53211,170.807597,1009.873209,172.798897,970.130863,168.085413,1085.788632,188.273756,1143.33,200.15,1173.298363,206.819408,1115.012942,204.684812,1269.06026,219.95336,1287.11072,221.487469,433.700902,73.225168,459.575254,76.275506,446.509982,7521.696246
33,NaN,Total Financial Txn (A),22989.828637,75382.917441,25151.294246,76343.637013,28038.68392,82907.074133,30026.232242,87733.386771,106206.039045,322367.015359,33226.389633,91869.44049,36986.883087,94436.483946,40639.994704,102491.806531,44048.63387,109778.171866,47470.241149,112929.045545,50703.678697,114604.770194,55338.939377,124295.397672,58013.643537,128028.549704,61453.642795,130812.391918,65838.121837,131382.095261,69388.694226,141847.86702,71191.018977,148125.533611,24408.825322,50637.102653,25238.98865,50747.182429,24883.306982,2920512.866412
34,NaN,Non Financial:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NPCI Operated Systems,FY22-23 Q1,NaN,FY22-23 Q2,NaN,FY22-23 Q3,NaN,FY22-23 Q4,NaN,F.Y-2022-23,NaN,F.Y-2023-24 Q1,NaN,F.Y-2023-24 Q2,NaN,F.Y-2023-24 Q3,NaN,F.Y-2023-24 Q4,NaN,F.Y-2024-25 Q1,NaN,F.Y-2024-25 Q2,NaN,F.Y-2024-25 Q3,NaN,F.Y-2024-25 Q4,NaN,F.Y-2025-26 Q1,NaN,F.Y-2025-26 Q2,NaN,F.Y-2025-26 Q3,NaN,F.Y-2025-26 Q4,NaN,2026-04-01 00:00:00,NaN,2026-05-01 00:00:00,NaN,2026-06-01 00:00:00,NaN
36,NaN,NaN,Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn),Volume (in Mn),Value (in Bn)
37,12,"NFS Txn over ATM (e.g. Balance inquiery, Pin change, Mini Statement, etc.)",194.336012,NaN,187.890591,NaN,195.491058,NaN,187.292236,NaN,765.009897,NaN,188.494569,NaN,187.984154,NaN,197.181443,NaN,190.186703,NaN,185.315664,NaN,173.344558,NaN,167.162723,NaN,154.51,0,144.14886,NaN,142.045638,0,145.787968,0,138.84,NaN,44.28,NaN,45.09,NaN,42.699882,NaN
38,13,AEPS (Inter Bank) Txn over Micro ATM (e.g. Balance inquiry/ Mini statement etc.),348.122674,NaN,332.197888,NaN,302.22607,NaN,302.915064,NaN,1285.461696,NaN,303.71394,NaN,341.544409,NaN,336.487845,NaN,299.630465,NaN,287.921666,NaN,300.083294,NaN,312.211306,NaN,308.054827,0,296.323332,NaN,342.598241,0,344.712341,0,304.631286,NaN,90.304684,NaN,90.586846,NaN,104.36,NaN
39,14,AEPS (Intra Bank) UIDAI Authentication over Micro ATM,546.399418,NaN,556.308933,NaN,595.360314,NaN,617.716857,NaN,2315.785522,NaN,669.099805,NaN,780.30358,NaN,779.281929,NaN,825.729489,NaN,846.51884,NaN,936.249424,NaN,955.693631,NaN,969.270862,0,934.64159,NaN,985.803546,0,903.718579,0,920.159485,NaN,294.283212,NaN,297.800857,NaN,322.02,NaN
40,15,eKYC Verification (Successful Txn),69.835093,NaN,86.967733,NaN,86.797157,NaN,96.844405,NaN,340.444388,NaN,100.704858,NaN,126.924549,NaN,118.577173,NaN,121.448672,NaN,107.327961,NaN,123.730323,NaN,112.241133,NaN,117.159865,0,113.724253,NaN,149.507458,0,157.744611,0,158.72505,NaN,50.777543,NaN,55.579376,NaN,59.84,NaN
41,16,Demographic Queries(Authenticated UID),12.746205,NaN,14.425978,NaN,14.29914,NaN,15.882859,NaN,57.354182,NaN,15.464665,NaN,21.628752,NaN,25.279737,NaN,26.75621,NaN,24.75597,NaN,32.86906,NaN,35.310288,NaN,37.780667,0,44.766081,NaN,55.756078,0,38.960434,0,42.801985,NaN,14.683099,NaN,16.05199,NaN,25.41,NaN
42,17,AEPS Tokenization,31.214191,NaN,13.76488,NaN,18.519702,NaN,13.446107,NaN,76.94488,NaN,12.06288,NaN,16.163595,NaN,20.381377,NaN,20.33227,NaN,17.334209,NaN,17.22768,NaN,23.420626,NaN,30.157681,0,38.273793,NaN,67.19309,0,159.011319,0,28.733299,NaN,7.045122,NaN,5.135637,NaN,7.53,NaN
43,18,BBPS (Bill Fetch),1367.39056,NaN,1555.775234,NaN,1630.905386,NaN,1547.534496,NaN,6101.605676,NaN,1735.525411,NaN,2008.040955,NaN,2596.6,NaN,2719.36,NaN,3166.211425,NaN,3751.18,NaN,4063.52,NaN,4076.57,0,4459.85,NaN,4661.77,0,4383.26,0,4327.103473,NaN,1567.15,NaN,1537.99,NaN,1567.378046,NaN
44,26,QSAM,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,0,NaN,0,0,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Total Non Financial Txn (B),2570.044153,NaN,2747.331237,NaN,2843.598827,NaN,2781.632024,0,10942.606241,NaN,3025.066128,0,3482.589994,NaN,4073.789504,NaN,4203.443809,NaN,4635.385735,NaN,5334.684339,NaN,5669.559707,NaN,5693.503902,0,6031.727909,NaN,6404.674051,0,6133.195252,0,5920.994578,NaN,2068.52366,NaN,2048.234706,NaN,2129.237928,NaN
46,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,Total Financial + Non Financial (A+B),25559.87279,75382.917441,27898.625483,76343.637013,30882.282747,82907.074133,32807.864266,87733.386771,117148.645286,322367.015359,36251.455761,91869.44049,40469.473081,94436.483946,44713.784208,102491.806531,48252.077679,109778.171866,52105.626884,112929.045545,56038.363036,114604.770194,61008.499084,124295.397672,63707.147439,128028.549704,67485.370704,130812.391918,72242.795888,131382.095261,75521.889478,141847.86702,77112.013555,148125.533611,26477.348982,50637.102653,27287.223356,50747.182429,27012.54491,2920512.866412
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,* NFS - ATM Cash Withdrawal - includes card+PIN transactions on micro-ATMs and does not include ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

==========================================================================================
18. RAW DATA BASELINE
==========================================================================================

,Input_File,Sheet,Raw_Rows,Raw_Columns,Total_Cells,Total_Missing_Cells,Total_Present_Cells,Total_Numeric_Zero_Cells,Duplicate_Row_Instances,Completely_Empty_Rows,Completely_Empty_Columns,Numeric_Cells,String_Cells,Datetime_Cells,Boolean_Cells,Other_Cells
0,NPCI-Retail-Payments-Statistics---Excel-Format.xlsx,Sheet1,50,42,2100,554,1546,151,3,3,0,1380,160,0,0,6

==========================================================================================
STEP 1 VALIDATION
==========================================================================================
✓ Original dataset loaded successfully
✓ Raw dimensions recorded
✓ Missing values measured
✓ Zero values measured
✓ Duplicate rows checked
✓ Data types inspected
✓ Unique values inspected
✓ Baseline established
✓ NO DATA WAS MODIFIED
✓ NO VALUES WERE IMPUTED
✓ NO NaN VALUES WERE REPLACED
✓ NO ZERO VALUES WERE CHANGED

==========================================================================================
STEP 1 FINAL REPORT
==========================================================================================

,Input_File,Sheet,Raw_Rows,Raw_Columns,Total_Cells,Total_Missing_Cells,Total_Present_Cells,Total_Numeric_Zero_Cells,Duplicate_Row_Instances,Completely_Empty_Rows,Completely_Empty_Columns,Numeric_Cells,String_Cells,Datetime_Cells,Boolean_Cells,Other_Cells
0,NPCI-Retail-Payments-Statistics---Excel-Format.xlsx,Sheet1,50,42,2100,554,1546,151,3,3,0,1380,160,0,0,6

==========================================================================================
STEP 1 COMPLETE
==========================================================================================

Output report:
NPCI_Step1_Raw_Data_Audit_Report.xlsx

READY FOR STEP 2.

In [4]:
# ============================================================================
# STEP 2: HEADER RECONSTRUCTION & DATA STRUCTURE
# Dataset: NPCI Retail Payments Statistics
# ============================================================================

import pandas as pd
import numpy as np
import re
from pathlib import Path

# ----------------------------------------------------------------------------
# 1. INPUT FILE
# ----------------------------------------------------------------------------

INPUT_FILE = "NPCI-Retail-Payments-Statistics---Excel-Format.xlsx"
OUTPUT_FILE = "NPCI_Step2_Structured.xlsx"

print("=" * 90)
print("STEP 2: HEADER RECONSTRUCTION & DATA STRUCTURE")
print("=" * 90)

print("\nINPUT FILE")
print("-" * 90)
print(f"Input file : {INPUT_FILE}")

# ----------------------------------------------------------------------------
# 2. LOAD RAW EXCEL WITHOUT ASSUMING A HEADER
# ----------------------------------------------------------------------------

raw = pd.read_excel(
    INPUT_FILE,
    header=None
)

print("\nRAW DATA RELOADED")
print("-" * 90)
print(f"Rows    : {raw.shape[0]}")
print(f"Columns : {raw.shape[1]}")

assert raw.shape == (50, 42), (
    f"Unexpected raw dimensions: {raw.shape}. "
    f"Expected (50, 42)."
)

print("✓ Raw dimensions validated")

# ----------------------------------------------------------------------------
# 3. STRUCTURAL ROW IDENTIFICATION
# ----------------------------------------------------------------------------

TITLE_ROW = 0

FIN_HEADER_1 = 2
FIN_HEADER_2 = 3

FIN_DATA_START = 4
FIN_DATA_END = 32

NONFIN_SECTION_ROW = 33
NONFIN_HEADER_1 = 34
NONFIN_HEADER_2 = 35

NONFIN_DATA_START = 36
NONFIN_DATA_END = 46

FOOTNOTE_ROW = 48

print("\nSTRUCTURAL ROW IDENTIFICATION")
print("-" * 90)

print(f"Title row                    : {TITLE_ROW + 1}")
print(f"Financial header row 1       : {FIN_HEADER_1 + 1}")
print(f"Financial header row 2       : {FIN_HEADER_2 + 1}")
print(
    f"Financial data rows          : "
    f"{FIN_DATA_START + 1} - {FIN_DATA_END + 1}"
)
print(f"Non-financial section row    : {NONFIN_SECTION_ROW + 1}")
print(f"Non-financial header row 1   : {NONFIN_HEADER_1 + 1}")
print(f"Non-financial header row 2   : {NONFIN_HEADER_2 + 1}")
print(
    f"Non-financial data rows      : "
    f"{NONFIN_DATA_START + 1} - {NONFIN_DATA_END + 1}"
)
print(f"Footnote row                 : {FOOTNOTE_ROW + 1}")

# ----------------------------------------------------------------------------
# 4. HELPER FUNCTIONS
# ----------------------------------------------------------------------------

def is_blank(value):
    """
    True for NaN / None / empty strings.
    """
    if pd.isna(value):
        return True

    if isinstance(value, str) and value.strip() == "":
        return True

    return False


def normalize_period(value):
    """
    Convert the raw period/header value into a standardized period label.
    """

    if is_blank(value):
        return None

    # Datetime values such as 2026-04-01
    if isinstance(value, (pd.Timestamp,)):
        return value.strftime("%Y_%m")

    # Python datetime
    if hasattr(value, "strftime") and not isinstance(value, str):
        try:
            return value.strftime("%Y_%m")
        except Exception:
            pass

    text = str(value).strip()

    # Normalize common variants
    text = text.replace("–", "-")
    text = text.replace("—", "-")
    text = text.replace(" ", "")

    # FY22-23 Q1
    m = re.match(
        r"FY(\d{2})-(\d{2})Q([1-4])$",
        text,
        flags=re.IGNORECASE
    )

    if m:
        y1, y2, q = m.groups()
        return f"FY_20{y1}_20{y2}_Q{q}"

    # F.Y-2022-23
    m = re.match(
        r"F\.?Y\.?-?(\d{4})-(\d{2})$",
        text,
        flags=re.IGNORECASE
    )

    if m:
        y1, y2 = m.groups()
        return f"FY_{y1}_20{y2}"

    # F.Y-2023-24 Q1
    m = re.match(
        r"F\.?Y\.?-?(\d{4})-(\d{2})Q([1-4])$",
        text,
        flags=re.IGNORECASE
    )

    if m:
        y1, y2, q = m.groups()
        return f"FY_{y1}_20{y2}_Q{q}"

    return text


def clean_header_text(value):
    """
    Clean Volume/Value header text.
    """

    if is_blank(value):
        return None

    text = str(value).strip()

    text = re.sub(r"\s+", " ", text)

    lower = text.lower()

    if "volume" in lower:
        return "Volume_in_Mn"

    if "value" in lower:
        return "Value_in_Bn"

    return None


# ----------------------------------------------------------------------------
# 5. READ THE TWO HEADER ROWS
# ----------------------------------------------------------------------------

header_row_1 = raw.iloc[FIN_HEADER_1]
header_row_2 = raw.iloc[FIN_HEADER_2]

print("\nPERIOD HEADER RECONSTRUCTION")
print("-" * 90)

# ----------------------------------------------------------------------------
# 6. FORWARD-FILL PERIOD HEADERS
# ----------------------------------------------------------------------------
#
# IMPORTANT:
# In the original Excel sheet, merged cells result in NaN in the following
# columns.
#
# Example:
#
# Q1 | Volume
#    | Value
#
# The Value column has no period in the raw sheet.
# Therefore, the Q1 period must be carried forward.
#
# ----------------------------------------------------------------------------

resolved_periods = []

current_period = None

for col_idx in range(raw.shape[1]):

    raw_period = header_row_1.iloc[col_idx]

    # If first header row contains a period, update current period.
    normalized = normalize_period(raw_period)

    if normalized is not None:
        current_period = normalized

    resolved_periods.append(current_period)

    sub_header = header_row_2.iloc[col_idx]

    print(
        f"Column {col_idx:02d} | "
        f"Period/Header = {repr(raw_period)} | "
        f"Sub-header = {repr(sub_header)} | "
        f"Resolved Period = {repr(current_period)}"
    )

# ----------------------------------------------------------------------------
# 7. SPECIAL CASE:
# THE UPLOADED SHEET MAY HAVE THE PERIOD INFORMATION IN HEADER ROW 2
# ----------------------------------------------------------------------------
#
# Your error output showed the period labels under "Sub-header".
# Therefore, if the first header row is entirely blank for transaction
# columns, detect the period from header row 2 and forward-fill from there.
#
# ----------------------------------------------------------------------------

transaction_start = 2

if all(
    is_blank(header_row_1.iloc[i])
    for i in range(transaction_start, raw.shape[1])
):
    print("\n⚠ Period labels detected in second header row.")
    print("✓ Reconstructing periods from the second header row.")

    resolved_periods = []
    current_period = None

    for col_idx in range(raw.shape[1]):

        candidate_1 = header_row_1.iloc[col_idx]
        candidate_2 = header_row_2.iloc[col_idx]

        period_candidate = normalize_period(candidate_1)

        if period_candidate is None:
            period_candidate = normalize_period(candidate_2)

        if period_candidate is not None:
            current_period = period_candidate

        resolved_periods.append(current_period)

# ----------------------------------------------------------------------------
# 8. DETERMINE VOLUME / VALUE
# ----------------------------------------------------------------------------

metric_labels = []

for col_idx in range(raw.shape[1]):

    h1 = clean_header_text(header_row_1.iloc[col_idx])
    h2 = clean_header_text(header_row_2.iloc[col_idx])

    metric = h1 if h1 is not None else h2

    metric_labels.append(metric)

# ----------------------------------------------------------------------------
# 9. HANDLE THE ACTUAL TWO-COLUMN PATTERN
# ----------------------------------------------------------------------------
#
# The dataset has:
#
# Period | Volume
#        | Value
#
# Therefore, if a transaction column does not explicitly contain Volume or
# Value, infer it from the alternating structure.
#
# Column 2 = Volume
# Column 3 = Value
# Column 4 = Volume
# Column 5 = Value
# ...
#
# This is structural reconstruction, NOT data modification.
# ----------------------------------------------------------------------------

for col_idx in range(2, raw.shape[1]):

    if metric_labels[col_idx] is None:

        if (col_idx - 2) % 2 == 0:
            metric_labels[col_idx] = "Volume_in_Mn"
        else:
            metric_labels[col_idx] = "Value_in_Bn"

# ----------------------------------------------------------------------------
# 10. VERIFY PERIODS AND METRICS
# ----------------------------------------------------------------------------

print("\nRECONSTRUCTED TRANSACTION HEADERS")
print("-" * 90)

for col_idx in range(2, raw.shape[1]):

    print(
        f"{col_idx:02d} | "
        f"Period = {resolved_periods[col_idx]} | "
        f"Metric = {metric_labels[col_idx]}"
    )

# ----------------------------------------------------------------------------
# 11. CREATE COLUMN NAMES
# ----------------------------------------------------------------------------

generated_columns = [
    "Sr_No",
    "NPCI_Operated_System"
]

for col_idx in range(2, raw.shape[1]):

    period = resolved_periods[col_idx]
    metric = metric_labels[col_idx]

    if period is None:
        period = f"Column_{col_idx:02d}_Unknown"

    if metric is None:
        metric = "Unknown"

    column_name = f"{period}_{metric}"

    generated_columns.append(column_name)

# ----------------------------------------------------------------------------
# 12. CLEAN COLUMN NAMES
# ----------------------------------------------------------------------------

def sanitize_column_name(name):

    name = str(name)

    name = name.replace(" ", "_")
    name = name.replace("-", "_")
    name = name.replace(".", "_")
    name = name.replace("/", "_")
    name = name.replace("(", "")
    name = name.replace(")", "")

    name = re.sub(r"_+", "_", name)

    return name.strip("_")


generated_columns = [
    sanitize_column_name(col)
    for col in generated_columns
]

# ----------------------------------------------------------------------------
# 13. DUPLICATE CHECK
# ----------------------------------------------------------------------------

duplicate_mask = pd.Series(generated_columns).duplicated(keep=False)

duplicate_columns = (
    pd.Series(generated_columns)[duplicate_mask]
    .unique()
    .tolist()
)

print("\nCOLUMN NAME VALIDATION")
print("-" * 90)

print(f"Total generated columns : {len(generated_columns)}")
print(f"Duplicate column names  : {len(duplicate_columns)}")

if duplicate_columns:

    print("\nDuplicate names detected:")
    for col in duplicate_columns:
        print(f"  {col}")

    raise ValueError(
        "Duplicate generated column names detected. "
        "Header reconstruction must be corrected."
    )

print("✓ Column names are unique")

# ----------------------------------------------------------------------------
# 14. PRINT GENERATED COLUMN NAMES
# ----------------------------------------------------------------------------

print("\nGENERATED COLUMN NAMES")
print("-" * 90)

for idx, col in enumerate(generated_columns):
    print(f"{idx:02d} | {col}")

# ----------------------------------------------------------------------------
# 15. EXTRACT FINANCIAL DATA
# ----------------------------------------------------------------------------

financial_data = raw.iloc[
    FIN_DATA_START:FIN_DATA_END + 1
].copy()

print("\nFINANCIAL SECTION")
print("-" * 90)

print(f"Rows    : {financial_data.shape[0]}")
print(f"Columns : {financial_data.shape[1]}")

# ----------------------------------------------------------------------------
# 16. EXTRACT NON-FINANCIAL DATA
# ----------------------------------------------------------------------------

nonfinancial_data = raw.iloc[
    NONFIN_DATA_START:NONFIN_DATA_END + 1
].copy()

print("\nNON-FINANCIAL SECTION")
print("-" * 90)

print(f"Rows    : {nonfinancial_data.shape[0]}")
print(f"Columns : {nonfinancial_data.shape[1]}")

# ----------------------------------------------------------------------------
# 17. COMBINE BOTH SECTIONS
# ----------------------------------------------------------------------------

structured = pd.concat(
    [
        financial_data,
        nonfinancial_data
    ],
    ignore_index=True
)

structured.columns = generated_columns

print("\nCOMBINED STRUCTURED DATA")
print("-" * 90)

print(f"Rows    : {structured.shape[0]}")
print(f"Columns : {structured.shape[1]}")

assert structured.shape == (40, 42)

# ----------------------------------------------------------------------------
# 18. COMPLETELY EMPTY ROW CHECK
# ----------------------------------------------------------------------------

empty_rows = structured.isna().all(axis=1).sum()

print("\nCOMPLETELY EMPTY ROW CHECK")
print("-" * 90)

print(f"Completely empty rows : {empty_rows}")

assert empty_rows == 0

print("✓ No completely empty structured rows")

# ----------------------------------------------------------------------------
# 19. TRANSACTION COLUMN IDENTIFICATION
# ----------------------------------------------------------------------------

transaction_columns = generated_columns[2:]

volume_columns = [
    col for col in transaction_columns
    if col.endswith("Volume_in_Mn")
]

value_columns = [
    col for col in transaction_columns
    if col.endswith("Value_in_Bn")
]

print("\nTRANSACTION COLUMN IDENTIFICATION")
print("-" * 90)

print(f"Transaction columns : {len(transaction_columns)}")
print(f"Volume columns      : {len(volume_columns)}")
print(f"Value columns       : {len(value_columns)}")

print("\nVolume columns:")

for col in volume_columns:
    print(f"  {col}")

print("\nValue columns:")

for col in value_columns:
    print(f"  {col}")

# ----------------------------------------------------------------------------
# 20. STRUCTURE VALIDATION
# ----------------------------------------------------------------------------

EXPECTED_TRANSACTION_COLUMNS = 40
EXPECTED_VOLUME_COLUMNS = 20
EXPECTED_VALUE_COLUMNS = 20

print("\nSTRUCTURE VALIDATION")
print("-" * 90)

print(
    f"Expected transaction columns : "
    f"{EXPECTED_TRANSACTION_COLUMNS}"
)

print(
    f"Actual transaction columns   : "
    f"{len(transaction_columns)}"
)

print(
    f"Expected volume columns      : "
    f"{EXPECTED_VOLUME_COLUMNS}"
)

print(
    f"Actual volume columns        : "
    f"{len(volume_columns)}"
)

print(
    f"Expected value columns       : "
    f"{EXPECTED_VALUE_COLUMNS}"
)

print(
    f"Actual value columns         : "
    f"{len(value_columns)}"
)

assert len(transaction_columns) == EXPECTED_TRANSACTION_COLUMNS
assert len(volume_columns) == EXPECTED_VOLUME_COLUMNS
assert len(value_columns) == EXPECTED_VALUE_COLUMNS

print("✓ Transaction column structure validated")

# ----------------------------------------------------------------------------
# 21. SAVE STRUCTURED DATA
# ----------------------------------------------------------------------------

structured.to_excel(
    OUTPUT_FILE,
    index=False
)

print("\nOUTPUT CHECKPOINT")
print("-" * 90)

print(f"Output file : {OUTPUT_FILE}")

# ----------------------------------------------------------------------------
# 22. FINAL REPORT
# ----------------------------------------------------------------------------

print("\n" + "=" * 90)
print("STEP 2 FINAL REPORT")
print("=" * 90)

print(
    f"""
Raw rows                         : {raw.shape[0]}
Raw columns                      : {raw.shape[1]}

Structured rows                 : {structured.shape[0]}
Structured columns              : {structured.shape[1]}

Transaction columns             : {len(transaction_columns)}
Volume columns                  : {len(volume_columns)}
Value columns                   : {len(value_columns)}

Completely empty rows           : {empty_rows}

Data values modified            : False
Missing values imputed          : False
NaN converted to zero           : False
Duplicate rows removed          : False
"""
)

print("=" * 90)
print("STEP 2 COMPLETE")
print("=" * 90)

print("✓ Header structure reconstructed")
print("✓ Merged period headers forward-filled")
print("✓ Financial section identified")
print("✓ Non-financial section identified")
print("✓ Period labels standardized")
print("✓ Volume columns identified")
print("✓ Value columns identified")
print("✓ Transaction columns identified")
print("✓ Column names validated")
print("✓ No data values modified")
print("✓ No missing values imputed")
print("✓ Existing zeros preserved")
print("✓ No rows deleted")
print("✓ No duplicate rows removed")
print("✓ Checkpoint saved")

print(f"\nOutput file: {OUTPUT_FILE}")
print("\nREADY FOR STEP 3.")

==========================================================================================
STEP 2: HEADER RECONSTRUCTION & DATA STRUCTURE
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI-Retail-Payments-Statistics---Excel-Format.xlsx

RAW DATA RELOADED
------------------------------------------------------------------------------------------
Rows    : 50
Columns : 42
✓ Raw dimensions validated

STRUCTURAL ROW IDENTIFICATION
------------------------------------------------------------------------------------------
Title row                    : 1
Financial header row 1       : 3
Financial header row 2       : 4
Financial data rows          : 5 - 33
Non-financial section row    : 34
Non-financial header row 1   : 35
Non-financial header row 2   : 36
Non-financial data rows      : 37 - 47
Footnote row                 : 49

PERIOD HEADER RECONSTRUCTION
------------------------------------------------------------------------------------------
Column 00 | Period/Header = nan | Sub-header = 'Sr. No.' | Resolved Period = None
Column 01 | Period/Header = nan | Sub-header = 'NPCI Operated Systems' | Resolved Period = None
Column 02 | Period/Header = nan | Sub-header = 'FY22-23 Q1' | Resolved Period = None
Column 03 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 04 | Period/Header = nan | Sub-header = 'FY22-23 Q2' | Resolved Period = None
Column 05 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 06 | Period/Header = nan | Sub-header = 'FY22-23 Q3' | Resolved Period = None
Column 07 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 08 | Period/Header = nan | Sub-header = 'FY22-23 Q4' | Resolved Period = None
Column 09 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 10 | Period/Header = nan | Sub-header = 'F.Y-2022-23' | Resolved Period = None
Column 11 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 12 | Period/Header = nan | Sub-header = 'F.Y-2023-24 Q1' | Resolved Period = None
Column 13 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 14 | Period/Header = nan | Sub-header = 'F.Y-2023-24 Q2' | Resolved Period = None
Column 15 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 16 | Period/Header = nan | Sub-header = 'F.Y-2023-24 Q3' | Resolved Period = None
Column 17 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 18 | Period/Header = nan | Sub-header = 'F.Y-2023-24 Q4' | Resolved Period = None
Column 19 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 20 | Period/Header = nan | Sub-header = 'F.Y-2024-25 Q1' | Resolved Period = None
Column 21 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 22 | Period/Header = nan | Sub-header = 'F.Y-2024-25 Q2' | Resolved Period = None
Column 23 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 24 | Period/Header = nan | Sub-header = 'F.Y-2024-25 Q3' | Resolved Period = None
Column 25 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 26 | Period/Header = nan | Sub-header = 'F.Y-2024-25 Q4' | Resolved Period = None
Column 27 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 28 | Period/Header = nan | Sub-header = 'F.Y-2025-26 Q1' | Resolved Period = None
Column 29 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 30 | Period/Header = nan | Sub-header = 'F.Y-2025-26 Q2' | Resolved Period = None
Column 31 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 32 | Period/Header = nan | Sub-header = 'F.Y-2025-26 Q3' | Resolved Period = None
Column 33 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 34 | Period/Header = nan | Sub-header = 'F.Y-2025-26 Q4' | Resolved Period = None
Column 35 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 36 | Period/Header = nan | Sub-header = datetime.datetime(2026, 4, 1, 0, 0) | Resolved Period = None
Column 37 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 38 | Period/Header = nan | Sub-header = datetime.datetime(2026, 5, 1, 0, 0) | Resolved Period = None
Column 39 | Period/Header = nan | Sub-header = nan | Resolved Period = None
Column 40 | Period/Header = nan | Sub-header = datetime.datetime(2026, 6, 1, 0, 0) | Resolved Period = None
Column 41 | Period/Header = nan | Sub-header = nan | Resolved Period = None

⚠ Period labels detected in second header row.
✓ Reconstructing periods from the second header row.

RECONSTRUCTED TRANSACTION HEADERS
------------------------------------------------------------------------------------------
02 | Period = FY_2022_2023_Q1 | Metric = Volume_in_Mn
03 | Period = FY_2022_2023_Q1 | Metric = Value_in_Bn
04 | Period = FY_2022_2023_Q2 | Metric = Volume_in_Mn
05 | Period = FY_2022_2023_Q2 | Metric = Value_in_Bn
06 | Period = FY_2022_2023_Q3 | Metric = Volume_in_Mn
07 | Period = FY_2022_2023_Q3 | Metric = Value_in_Bn
08 | Period = FY_2022_2023_Q4 | Metric = Volume_in_Mn
09 | Period = FY_2022_2023_Q4 | Metric = Value_in_Bn
10 | Period = FY_2022_2023 | Metric = Volume_in_Mn
11 | Period = FY_2022_2023 | Metric = Value_in_Bn
12 | Period = FY_2023_2024_Q1 | Metric = Volume_in_Mn
13 | Period = FY_2023_2024_Q1 | Metric = Value_in_Bn
14 | Period = FY_2023_2024_Q2 | Metric = Volume_in_Mn
15 | Period = FY_2023_2024_Q2 | Metric = Value_in_Bn
16 | Period = FY_2023_2024_Q3 | Metric = Volume_in_Mn
17 | Period = FY_2023_2024_Q3 | Metric = Value_in_Bn
18 | Period = FY_2023_2024_Q4 | Metric = Volume_in_Mn
19 | Period = FY_2023_2024_Q4 | Metric = Value_in_Bn
20 | Period = FY_2024_2025_Q1 | Metric = Volume_in_Mn
21 | Period = FY_2024_2025_Q1 | Metric = Value_in_Bn
22 | Period = FY_2024_2025_Q2 | Metric = Volume_in_Mn
23 | Period = FY_2024_2025_Q2 | Metric = Value_in_Bn
24 | Period = FY_2024_2025_Q3 | Metric = Volume_in_Mn
25 | Period = FY_2024_2025_Q3 | Metric = Value_in_Bn
26 | Period = FY_2024_2025_Q4 | Metric = Volume_in_Mn
27 | Period = FY_2024_2025_Q4 | Metric = Value_in_Bn
28 | Period = FY_2025_2026_Q1 | Metric = Volume_in_Mn
29 | Period = FY_2025_2026_Q1 | Metric = Value_in_Bn
30 | Period = FY_2025_2026_Q2 | Metric = Volume_in_Mn
31 | Period = FY_2025_2026_Q2 | Metric = Value_in_Bn
32 | Period = FY_2025_2026_Q3 | Metric = Volume_in_Mn
33 | Period = FY_2025_2026_Q3 | Metric = Value_in_Bn
34 | Period = FY_2025_2026_Q4 | Metric = Volume_in_Mn
35 | Period = FY_2025_2026_Q4 | Metric = Value_in_Bn
36 | Period = 2026_04 | Metric = Volume_in_Mn
37 | Period = 2026_04 | Metric = Value_in_Bn
38 | Period = 2026_05 | Metric = Volume_in_Mn
39 | Period = 2026_05 | Metric = Value_in_Bn
40 | Period = 2026_06 | Metric = Volume_in_Mn
41 | Period = 2026_06 | Metric = Value_in_Bn

COLUMN NAME VALIDATION
------------------------------------------------------------------------------------------
Total generated columns : 42
Duplicate column names  : 0
✓ Column names are unique

GENERATED COLUMN NAMES
------------------------------------------------------------------------------------------
00 | Sr_No
01 | NPCI_Operated_System
02 | FY_2022_2023_Q1_Volume_in_Mn
03 | FY_2022_2023_Q1_Value_in_Bn
04 | FY_2022_2023_Q2_Volume_in_Mn
05 | FY_2022_2023_Q2_Value_in_Bn
06 | FY_2022_2023_Q3_Volume_in_Mn
07 | FY_2022_2023_Q3_Value_in_Bn
08 | FY_2022_2023_Q4_Volume_in_Mn
09 | FY_2022_2023_Q4_Value_in_Bn
10 | FY_2022_2023_Volume_in_Mn
11 | FY_2022_2023_Value_in_Bn
12 | FY_2023_2024_Q1_Volume_in_Mn
13 | FY_2023_2024_Q1_Value_in_Bn
14 | FY_2023_2024_Q2_Volume_in_Mn
15 | FY_2023_2024_Q2_Value_in_Bn
16 | FY_2023_2024_Q3_Volume_in_Mn
17 | FY_2023_2024_Q3_Value_in_Bn
18 | FY_2023_2024_Q4_Volume_in_Mn
19 | FY_2023_2024_Q4_Value_in_Bn
20 | FY_2024_2025_Q1_Volume_in_Mn
21 | FY_2024_2025_Q1_Value_in_Bn
22 | FY_2024_2025_Q2_Volume_in_Mn
23 | FY_2024_2025_Q2_Value_in_Bn
24 | FY_2024_2025_Q3_Volume_in_Mn
25 | FY_2024_2025_Q3_Value_in_Bn
26 | FY_2024_2025_Q4_Volume_in_Mn
27 | FY_2024_2025_Q4_Value_in_Bn
28 | FY_2025_2026_Q1_Volume_in_Mn
29 | FY_2025_2026_Q1_Value_in_Bn
30 | FY_2025_2026_Q2_Volume_in_Mn
31 | FY_2025_2026_Q2_Value_in_Bn
32 | FY_2025_2026_Q3_Volume_in_Mn
33 | FY_2025_2026_Q3_Value_in_Bn
34 | FY_2025_2026_Q4_Volume_in_Mn
35 | FY_2025_2026_Q4_Value_in_Bn
36 | 2026_04_Volume_in_Mn
37 | 2026_04_Value_in_Bn
38 | 2026_05_Volume_in_Mn
39 | 2026_05_Value_in_Bn
40 | 2026_06_Volume_in_Mn
41 | 2026_06_Value_in_Bn

FINANCIAL SECTION
------------------------------------------------------------------------------------------
Rows    : 29
Columns : 42

NON-FINANCIAL SECTION
------------------------------------------------------------------------------------------
Rows    : 11
Columns : 42

COMBINED STRUCTURED DATA
------------------------------------------------------------------------------------------
Rows    : 40
Columns : 42

COMPLETELY EMPTY ROW CHECK
------------------------------------------------------------------------------------------
Completely empty rows : 0
✓ No completely empty structured rows

TRANSACTION COLUMN IDENTIFICATION
------------------------------------------------------------------------------------------
Transaction columns : 40
Volume columns      : 20
Value columns       : 20

Volume columns:
  FY_2022_2023_Q1_Volume_in_Mn
  FY_2022_2023_Q2_Volume_in_Mn
  FY_2022_2023_Q3_Volume_in_Mn
  FY_2022_2023_Q4_Volume_in_Mn
  FY_2022_2023_Volume_in_Mn
  FY_2023_2024_Q1_Volume_in_Mn
  FY_2023_2024_Q2_Volume_in_Mn
  FY_2023_2024_Q3_Volume_in_Mn
  FY_2023_2024_Q4_Volume_in_Mn
  FY_2024_2025_Q1_Volume_in_Mn
  FY_2024_2025_Q2_Volume_in_Mn
  FY_2024_2025_Q3_Volume_in_Mn
  FY_2024_2025_Q4_Volume_in_Mn
  FY_2025_2026_Q1_Volume_in_Mn
  FY_2025_2026_Q2_Volume_in_Mn
  FY_2025_2026_Q3_Volume_in_Mn
  FY_2025_2026_Q4_Volume_in_Mn
  2026_04_Volume_in_Mn
  2026_05_Volume_in_Mn
  2026_06_Volume_in_Mn

Value columns:
  FY_2022_2023_Q1_Value_in_Bn
  FY_2022_2023_Q2_Value_in_Bn
  FY_2022_2023_Q3_Value_in_Bn
  FY_2022_2023_Q4_Value_in_Bn
  FY_2022_2023_Value_in_Bn
  FY_2023_2024_Q1_Value_in_Bn
  FY_2023_2024_Q2_Value_in_Bn
  FY_2023_2024_Q3_Value_in_Bn
  FY_2023_2024_Q4_Value_in_Bn
  FY_2024_2025_Q1_Value_in_Bn
  FY_2024_2025_Q2_Value_in_Bn
  FY_2024_2025_Q3_Value_in_Bn
  FY_2024_2025_Q4_Value_in_Bn
  FY_2025_2026_Q1_Value_in_Bn
  FY_2025_2026_Q2_Value_in_Bn
  FY_2025_2026_Q3_Value_in_Bn
  FY_2025_2026_Q4_Value_in_Bn
  2026_04_Value_in_Bn
  2026_05_Value_in_Bn
  2026_06_Value_in_Bn

STRUCTURE VALIDATION
------------------------------------------------------------------------------------------
Expected transaction columns : 40
Actual transaction columns   : 40
Expected volume columns      : 20
Actual volume columns        : 20
Expected value columns       : 20
Actual value columns         : 20
✓ Transaction column structure validated

OUTPUT CHECKPOINT
------------------------------------------------------------------------------------------
Output file : NPCI_Step2_Structured.xlsx

==========================================================================================
STEP 2 FINAL REPORT
==========================================================================================

Raw rows                         : 50
Raw columns                      : 42

Structured rows                 : 40
Structured columns              : 42

Transaction columns             : 40
Volume columns                  : 20
Value columns                   : 20

Completely empty rows           : 0

Data values modified            : False
Missing values imputed          : False
NaN converted to zero           : False
Duplicate rows removed          : False

==========================================================================================
STEP 2 COMPLETE
==========================================================================================
✓ Header structure reconstructed
✓ Merged period headers forward-filled
✓ Financial section identified
✓ Non-financial section identified
✓ Period labels standardized
✓ Volume columns identified
✓ Value columns identified
✓ Transaction columns identified
✓ Column names validated
✓ No data values modified
✓ No missing values imputed
✓ Existing zeros preserved
✓ No rows deleted
✓ No duplicate rows removed
✓ Checkpoint saved

Output file: NPCI_Step2_Structured.xlsx

READY FOR STEP 3.

In [12]:
# ============================================================
# STEP 3: DATA TYPE & FORMAT CLEANING
# ============================================================
#
# INPUT:
#     NPCI_Step2_Structured.xlsx
#
# OUTPUT:
#     NPCI_Step3_Cleaned.xlsx
#
# PURPOSE:
#     - Convert genuine transaction data to numeric dtype
#     - Preserve structural/header rows
#     - Preserve missing values
#     - Preserve existing zeros
#     - Preserve all transaction values
#     - Do NOT impute missing values
#     - Do NOT convert NaN to zero
#     - Do NOT delete rows
#     - Do NOT remove duplicates
#
# ============================================================

import pandas as pd
import numpy as np
import os


# ============================================================
# CONFIGURATION
# ============================================================

INPUT_FILE = "NPCI_Step2_Structured.xlsx"
OUTPUT_FILE = "NPCI_Step3_Cleaned.xlsx"


# ============================================================
# STEP 1 — LOAD INPUT FILE
# ============================================================

print("=" * 90)
print("STEP 3: DATA TYPE & FORMAT CLEANING")
print("=" * 90)

print("\nINPUT FILE")
print("-" * 90)
print(f"Input file : {INPUT_FILE}")

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}"
    )

df = pd.read_excel(INPUT_FILE)

print(f"Rows       : {df.shape[0]}")
print(f"Columns    : {df.shape[1]}")


# ============================================================
# STEP 2 — VALIDATE INPUT DIMENSIONS
# ============================================================

assert df.shape == (40, 42), (
    f"Unexpected input dimensions: {df.shape}. "
    f"Expected (40, 42)."
)

print("\n✓ Input dimensions validated")


# ============================================================
# STEP 3 — MAKE DEEP COPY OF ORIGINAL DATA
# ============================================================

original_df = df.copy(deep=True)


# ============================================================
# STEP 4 — IDENTIFY TRANSACTION COLUMNS
# ============================================================

transaction_columns = [
    col
    for col in df.columns
    if "_Volume_in_Mn" in str(col)
    or "_Value_in_Bn" in str(col)
]

volume_columns = [
    col
    for col in transaction_columns
    if "_Volume_in_Mn" in str(col)
]

value_columns = [
    col
    for col in transaction_columns
    if "_Value_in_Bn" in str(col)
]


print("\nTRANSACTION COLUMN IDENTIFICATION")
print("-" * 90)

print(f"Transaction columns : {len(transaction_columns)}")
print(f"Volume columns      : {len(volume_columns)}")
print(f"Value columns       : {len(value_columns)}")


# ============================================================
# VALIDATE TRANSACTION STRUCTURE
# ============================================================

assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

print("✓ Transaction column structure validated")


# ============================================================
# STEP 5 — IDENTIFY SYSTEM NAME COLUMN
# ============================================================

system_col = "NPCI_Operated_System"

assert system_col in df.columns

print("\nTEXT FORMAT CHECK")
print("-" * 90)

print(
    f"NPCI_Operated_System column present : "
    f"{system_col in df.columns}"
)


# ============================================================
# STEP 6 — IDENTIFY STRUCTURAL ROWS
# ============================================================
#
# There are two types of structural rows:
#
# 1. Rows with no system name
# 2. Rows containing embedded headers such as:
#       Volume (in Mn)
#       Value (in Bn)
#
# These rows MUST NOT be passed through numeric conversion.
#
# ============================================================

# ------------------------------------------------------------
# 6A. Rows without system name
# ------------------------------------------------------------

empty_system_mask = (
    df[system_col].isna()
    |
    df[system_col].astype(str).str.strip().eq("")
)

empty_system_rows = df.index[
    empty_system_mask
].tolist()


# ------------------------------------------------------------
# 6B. Rows containing embedded header labels
# ------------------------------------------------------------

header_labels = {
    "Volume (in Mn)",
    "Value (in Bn)",
    "Volume",
    "Value",
    "Volume (in Mn.)",
    "Value (in Bn.)"
}

header_row_mask = pd.Series(
    False,
    index=df.index
)

header_row_matches = {}

for idx in df.index:

    row_matches = []

    for col in transaction_columns:

        value = df.at[idx, col]

        if pd.isna(value):
            continue

        value_string = str(value).strip()

        if value_string in header_labels:

            header_row_mask.loc[idx] = True

            row_matches.append(
                (col, value_string)
            )

    if row_matches:
        header_row_matches[idx] = row_matches


header_label_rows = df.index[
    header_row_mask
].tolist()


# ------------------------------------------------------------
# 6C. Combine structural rows
# ------------------------------------------------------------

structural_rows = sorted(
    set(
        empty_system_rows
        +
        header_label_rows
    )
)


# ------------------------------------------------------------
# 6D. Genuine transaction rows
# ------------------------------------------------------------

transaction_rows = [
    idx
    for idx in df.index
    if idx not in structural_rows
]


print("\nSTRUCTURAL ROW IDENTIFICATION")
print("-" * 90)

print(
    f"Rows without system name : "
    f"{len(empty_system_rows)}"
)

print(
    f"Empty-system row indices : "
    f"{empty_system_rows}"
)

print(
    f"Embedded header rows     : "
    f"{len(header_label_rows)}"
)

print(
    f"Header row indices       : "
    f"{header_label_rows}"
)

print(
    f"Total structural rows    : "
    f"{len(structural_rows)}"
)

print(
    f"Structural row indices   : "
    f"{structural_rows}"
)

print(
    f"Transaction data rows    : "
    f"{len(transaction_rows)}"
)


# ============================================================
# STEP 7 — SHOW EMBEDDED HEADER ROWS
# ============================================================

if header_row_matches:

    print("\nEMBEDDED HEADER CONTENT DETECTED")
    print("-" * 90)

    for idx, matches in header_row_matches.items():

        print(
            f"Row {idx} : {matches}"
        )

else:

    print("\nEMBEDDED HEADER CONTENT DETECTED")
    print("-" * 90)

    print("None")


# ============================================================
# STEP 8 — CAPTURE ORIGINAL COUNTS
# ============================================================

# IMPORTANT:
# These counts are taken BEFORE any modification.

missing_before = (
    original_df[
        transaction_columns
    ]
    .isna()
    .sum()
    .sum()
)


zero_before = (
    original_df[
        transaction_columns
    ]
    .eq(0)
    .sum()
    .sum()
)


print("\nORIGINAL DATA STATE")
print("-" * 90)

print(
    f"Missing transaction cells : "
    f"{missing_before}"
)

print(
    f"Zero transaction cells    : "
    f"{zero_before}"
)


# ============================================================
# STEP 9 — SAVE ORIGINAL TRANSACTION DATA
# ============================================================
#
# Only genuine transaction rows are compared for exact
# value preservation.
#
# Structural rows are separately checked.
#
# ============================================================

original_transaction_data = original_df.loc[
    transaction_rows,
    transaction_columns
].copy(deep=True)


original_structural_data = original_df.loc[
    structural_rows,
    transaction_columns
].copy(deep=True)


# ============================================================
# STEP 10 — CHECK NON-NUMERIC VALUES BEFORE CONVERSION
# ============================================================
#
# A value is considered invalid only when:
#
#     - it is in a genuine transaction row
#     - it is not missing
#     - it cannot be interpreted as a number
#
# Structural/header rows are excluded.
#
# ============================================================

non_numeric_before = {}

for col in transaction_columns:

    series = df.loc[
        transaction_rows,
        col
    ]

    numeric_test = pd.to_numeric(
        series,
        errors="coerce"
    )

    invalid_mask = (
        series.notna()
        &
        numeric_test.isna()
    )

    count_invalid = int(
        invalid_mask.sum()
    )

    if count_invalid > 0:

        non_numeric_before[col] = count_invalid


print("\nNON-NUMERIC TRANSACTION VALUE CHECK")
print("-" * 90)

if non_numeric_before:

    print(
        "⚠ Non-numeric values detected in genuine "
        "transaction rows:"
    )

    for col, count in non_numeric_before.items():

        print(
            f"  {col} : {count}"
        )

else:

    print(
        "✓ No non-numeric values detected in "
        "genuine transaction rows."
    )


# ============================================================
# STEP 11 — DISPLAY EXACT INVALID VALUES IF ANY
# ============================================================

if non_numeric_before:

    print("\nINVALID VALUE DETAILS")
    print("-" * 90)

    for col in non_numeric_before:

        series = df.loc[
            transaction_rows,
            col
        ]

        numeric_test = pd.to_numeric(
            series,
            errors="coerce"
        )

        invalid_mask = (
            series.notna()
            &
            numeric_test.isna()
        )

        invalid_rows = series[
            invalid_mask
        ]

        for idx, value in invalid_rows.items():

            print(
                f"Row {idx} | "
                f"Column {col} | "
                f"Value = {repr(value)}"
            )


# ============================================================
# STEP 12 — STOP IF REAL INVALID DATA EXISTS
# ============================================================
#
# We do NOT use errors="coerce" for conversion because that
# would silently turn bad strings into NaN.
#
# ============================================================

if non_numeric_before:

    raise ValueError(
        "\nReal non-numeric transaction values exist "
        "inside genuine transaction rows.\n"
        "The data has NOT been modified.\n"
        "Inspect the INVALID VALUE DETAILS above."
    )


# ============================================================
# STEP 13 — NUMERIC DATA TYPE CONVERSION
# ============================================================

print("\nNUMERIC DATA TYPE CONVERSION")
print("-" * 90)

for col in transaction_columns:

    # --------------------------------------------------------
    # Convert ONLY genuine transaction rows.
    #
    # Structural rows are completely untouched.
    #
    # errors='raise' guarantees that unexpected bad data
    # cannot silently become NaN.
    # --------------------------------------------------------

    converted = pd.to_numeric(
        df.loc[
            transaction_rows,
            col
        ],
        errors="raise"
    )

    df.loc[
        transaction_rows,
        col
    ] = converted


print("✓ Numeric transaction data converted safely.")
print("✓ Structural rows preserved.")
print("✓ Structural row transaction cells preserved.")


# ============================================================
# STEP 14 — VALIDATE STRUCTURAL ROWS
# ============================================================

structural_rows_match = original_structural_data.equals(
    df.loc[
        structural_rows,
        transaction_columns
    ]
)


assert structural_rows_match

print(
    "✓ Structural row values unchanged."
)


# ============================================================
# STEP 15 — VALIDATE TRANSACTION DATA TYPES
# ============================================================

numeric_transaction_cells = 0
non_numeric_transaction_cells = 0

for col in transaction_columns:

    series = df.loc[
        transaction_rows,
        col
    ]

    numeric_mask = pd.to_numeric(
        series,
        errors="coerce"
    ).notna()

    missing_mask = series.isna()

    valid_mask = (
        numeric_mask
        |
        missing_mask
    )

    non_numeric_transaction_cells += int(
        (~valid_mask).sum()
    )

    numeric_transaction_cells += int(
        numeric_mask.sum()
    )


print("\nTRANSACTION DATA TYPE VALIDATION")
print("-" * 90)

print(
    f"Transaction columns checked       : "
    f"{len(transaction_columns)}"
)

print(
    f"Numeric transaction data cells    : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells     : "
    f"{non_numeric_transaction_cells}"
)


assert non_numeric_transaction_cells == 0

print(
    "✓ All actual transaction data cells "
    "are numeric or missing."
)


# ============================================================
# STEP 16 — SR_NO VALIDATION
# ============================================================

print("\nSr_No CHECK")
print("-" * 90)

print(
    f"Sr_No dtype : "
    f"{df['Sr_No'].dtype}"
)

# We intentionally DO NOT convert Sr_No.
assert (
    df["Sr_No"].dtype
    ==
    original_df["Sr_No"].dtype
)

print(
    "✓ Sr_No structure preserved."
)


# ============================================================
# STEP 17 — NEGATIVE VALUE CHECK
# ============================================================

negative_volume_cells = (
    df.loc[
        transaction_rows,
        volume_columns
    ]
    .lt(0)
    .sum()
    .sum()
)

negative_value_cells = (
    df.loc[
        transaction_rows,
        value_columns
    ]
    .lt(0)
    .sum()
    .sum()
)


print("\nNEGATIVE VALUE CHECK")
print("-" * 90)

print(
    f"Negative volume cells : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells  : "
    f"{negative_value_cells}"
)


assert negative_volume_cells == 0
assert negative_value_cells == 0

print(
    "✓ No negative transaction values detected."
)


# ============================================================
# STEP 18 — INFINITY CHECK
# ============================================================

positive_infinity_cells = 0
negative_infinity_cells = 0

for col in transaction_columns:

    series = df.loc[
        transaction_rows,
        col
    ]

    numeric_series = pd.to_numeric(
        series,
        errors="coerce"
    )

    positive_infinity_cells += int(
        np.isposinf(
            numeric_series
        ).sum()
    )

    negative_infinity_cells += int(
        np.isneginf(
            numeric_series
        ).sum()
    )


print("\nINFINITY CHECK")
print("-" * 90)

print(
    f"Positive infinity cells : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells : "
    f"{negative_infinity_cells}"
)


assert positive_infinity_cells == 0
assert negative_infinity_cells == 0


# ============================================================
# STEP 19 — MISSINGNESS VALIDATION
# ============================================================

missing_after = (
    df[
        transaction_columns
    ]
    .isna()
    .sum()
    .sum()
)


missingness_preserved = (
    missing_before
    ==
    missing_after
)


# ============================================================
# STEP 20 — ZERO VALIDATION
# ============================================================

zero_after = (
    df[
        transaction_columns
    ]
    .eq(0)
    .sum()
    .sum()
)


zero_count_preserved = (
    zero_before
    ==
    zero_after
)


# ============================================================
# STEP 21 — EXACT TRANSACTION VALUE COMPARISON
# ============================================================
#
# Numeric conversion should NOT change the actual values.
#
# NaN == NaN normally evaluates False, so pandas .equals()
# is used because it treats corresponding missing values
# correctly.
#
# ============================================================

after_transaction_data = df.loc[
    transaction_rows,
    transaction_columns
].copy(deep=True)


transaction_values_match = (
    original_transaction_data.equals(
        after_transaction_data
    )
)


# ============================================================
# STEP 22 — DATA MODIFICATION FLAG
# ============================================================

data_values_modified = (
    not transaction_values_match
)


# ============================================================
# STEP 23 — IMPUTATION FLAG
# ============================================================
#
# Step 3 NEVER imputes.
#
# ============================================================

imputation_performed = False

nan_converted_to_zero = False


# ============================================================
# STEP 24 — DATA TYPE REPORT
# ============================================================

before_dtypes = original_df.dtypes
after_dtypes = df.dtypes

dtype_report = pd.DataFrame({
    "Column": df.columns,
    "Before_Data_Type": [
        str(before_dtypes[col])
        for col in df.columns
    ],
    "After_Data_Type": [
        str(after_dtypes[col])
        for col in df.columns
    ]
})


print("\nDATA TYPE REPORT")
print("-" * 90)

print(
    dtype_report.to_string(
        index=False
    )
)


# ============================================================
# STEP 25 — FINAL VALIDATION
# ============================================================

print("\n" + "=" * 90)
print("STEP 3 VALIDATION")
print("=" * 90)

print(
    f"Missing cells before       : "
    f"{missing_before}"
)

print(
    f"Missing cells after        : "
    f"{missing_after}"
)

print(
    f"Missingness preserved      : "
    f"{missingness_preserved}"
)

print()

print(
    f"Zero cells before          : "
    f"{zero_before}"
)

print(
    f"Zero cells after           : "
    f"{zero_after}"
)

print(
    f"Zero count preserved      : "
    f"{zero_count_preserved}"
)

print()

if transaction_values_match:

    print(
        "Transaction value mismatches : 0"
    )

else:

    print(
        "Transaction value mismatches : DETECTED"
    )

print(
    f"Data values modified         : "
    f"{data_values_modified}"
)

print(
    f"Imputation performed         : "
    f"{imputation_performed}"
)

print(
    f"NaN converted to zero        : "
    f"{nan_converted_to_zero}"
)


# ============================================================
# STEP 26 — HARD ASSERTIONS
# ============================================================

# Structure
assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

# Actual transaction data
assert non_numeric_transaction_cells == 0

# Missingness
assert missingness_preserved

# Existing zeros
assert zero_count_preserved

# Exact values
assert transaction_values_match

# No imputation
assert imputation_performed is False

# No NaN → zero conversion
assert nan_converted_to_zero is False

# No negatives
assert negative_volume_cells == 0
assert negative_value_cells == 0

# No infinity
assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

# Structural rows
assert structural_rows_match


# ============================================================
# STEP 27 — SAVE OUTPUT
# ============================================================

df.to_excel(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# STEP 28 — VERIFY OUTPUT FILE
# ============================================================

assert os.path.exists(
    OUTPUT_FILE
)


# Reload saved output and verify dimensions
saved_df = pd.read_excel(
    OUTPUT_FILE
)

assert saved_df.shape == (
    40,
    42
)


# ============================================================
# STEP 29 — FINAL REPORT
# ============================================================

print("\n" + "=" * 90)
print("STEP 3 FINAL REPORT")
print("=" * 90)

print(
    f"Input file                      : "
    f"{INPUT_FILE}"
)

print(
    f"Output file                     : "
    f"{OUTPUT_FILE}"
)

print()

print(
    f"Rows                            : "
    f"{df.shape[0]}"
)

print(
    f"Columns                         : "
    f"{df.shape[1]}"
)

print()

print(
    f"Transaction columns             : "
    f"{len(transaction_columns)}"
)

print(
    f"Volume columns                  : "
    f"{len(volume_columns)}"
)

print(
    f"Value columns                   : "
    f"{len(value_columns)}"
)

print()

print(
    f"Structural rows                 : "
    f"{len(structural_rows)}"
)

print(
    f"Transaction data rows           : "
    f"{len(transaction_rows)}"
)

print()

print(
    f"Missing cells before            : "
    f"{missing_before}"
)

print(
    f"Missing cells after             : "
    f"{missing_after}"
)

print(
    f"Missingness preserved            : "
    f"{missingness_preserved}"
)

print()

print(
    f"Zero cells before               : "
    f"{zero_before}"
)

print(
    f"Zero cells after                : "
    f"{zero_after}"
)

print(
    f"Zero count preserved            : "
    f"{zero_count_preserved}"
)

print()

print(
    f"Numeric transaction cells       : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells   : "
    f"{non_numeric_transaction_cells}"
)

print()

print(
    f"Transaction values unchanged    : "
    f"{transaction_values_match}"
)

print(
    f"Data values modified            : "
    f"{data_values_modified}"
)

print(
    f"Imputation performed            : "
    f"{imputation_performed}"
)

print(
    f"NaN converted to zero           : "
    f"{nan_converted_to_zero}"
)

print()

print(
    f"Negative volume cells           : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells            : "
    f"{negative_value_cells}"
)

print(
    f"Positive infinity cells        : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells        : "
    f"{negative_infinity_cells}"
)

print()

print("=" * 90)
print("STEP 3 COMPLETE")
print("=" * 90)

print("✓ Input dimensions validated")
print("✓ Transaction columns identified")
print("✓ Structural rows identified")
print("✓ Embedded header rows identified")
print("✓ Structural rows preserved")
print("✓ Numeric transaction data converted")
print("✓ Missing values preserved")
print("✓ Existing zeros preserved")
print("✓ No values imputed")
print("✓ No NaN converted to zero")
print("✓ No negative transaction values")
print("✓ No infinity values")
print("✓ Transaction values unchanged")
print("✓ Validation passed")
print("✓ Checkpoint saved")

print()
print(
    f"Output file: {OUTPUT_FILE}"
)

print("=" * 90)

==========================================================================================
STEP 3: DATA TYPE & FORMAT CLEANING
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI_Step2_Structured.xlsx
Rows       : 40
Columns    : 42

✓ Input dimensions validated

TRANSACTION COLUMN IDENTIFICATION
------------------------------------------------------------------------------------------
Transaction columns : 40
Volume columns      : 20
Value columns       : 20
✓ Transaction column structure validated

TEXT FORMAT CHECK
------------------------------------------------------------------------------------------
NPCI_Operated_System column present : True

STRUCTURAL ROW IDENTIFICATION
------------------------------------------------------------------------------------------
Rows without system name : 2
Empty-system row indices : [29, 39]
Embedded header rows     : 2
Header row indices       : [0, 29]
Total structural rows    : 3
Structural row indices   : [0, 29, 39]
Transaction data rows    : 37

EMBEDDED HEADER CONTENT DETECTED
------------------------------------------------------------------------------------------
Row 0 : [('FY_2022_2023_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q4_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q4_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q4_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q4_Value_in_Bn', 'Value (in Bn)'), ('2026_04_Volume_in_Mn', 'Volume (in Mn)'), ('2026_04_Value_in_Bn', 'Value (in Bn)'), ('2026_05_Volume_in_Mn', 'Volume (in Mn)'), ('2026_05_Value_in_Bn', 'Value (in Bn)'), ('2026_06_Volume_in_Mn', 'Volume (in Mn)'), ('2026_06_Value_in_Bn', 'Value (in Bn)')]
Row 29 : [('FY_2022_2023_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Q4_Value_in_Bn', 'Value (in Bn)'), ('FY_2022_2023_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2022_2023_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2023_2024_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2023_2024_Q4_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2024_2025_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2024_2025_Q4_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q1_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q1_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q2_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q2_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q3_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q3_Value_in_Bn', 'Value (in Bn)'), ('FY_2025_2026_Q4_Volume_in_Mn', 'Volume (in Mn)'), ('FY_2025_2026_Q4_Value_in_Bn', 'Value (in Bn)'), ('2026_04_Volume_in_Mn', 'Volume (in Mn)'), ('2026_04_Value_in_Bn', 'Value (in Bn)'), ('2026_05_Volume_in_Mn', 'Volume (in Mn)'), ('2026_05_Value_in_Bn', 'Value (in Bn)'), ('2026_06_Volume_in_Mn', 'Volume (in Mn)'), ('2026_06_Value_in_Bn', 'Value (in Bn)')]

ORIGINAL DATA STATE
------------------------------------------------------------------------------------------
Missing transaction cells : 251
Zero transaction cells    : 149

NON-NUMERIC TRANSACTION VALUE CHECK
------------------------------------------------------------------------------------------
✓ No non-numeric values detected in genuine transaction rows.

NUMERIC DATA TYPE CONVERSION
------------------------------------------------------------------------------------------
✓ Numeric transaction data converted safely.
✓ Structural rows preserved.
✓ Structural row transaction cells preserved.
✓ Structural row values unchanged.

TRANSACTION DATA TYPE VALIDATION
------------------------------------------------------------------------------------------
Transaction columns checked       : 40
Numeric transaction data cells    : 1262
Non-numeric transaction cells     : 0
✓ All actual transaction data cells are numeric or missing.

Sr_No CHECK
------------------------------------------------------------------------------------------
Sr_No dtype : float64
✓ Sr_No structure preserved.

NEGATIVE VALUE CHECK
------------------------------------------------------------------------------------------
Negative volume cells : 0
Negative value cells  : 0
✓ No negative transaction values detected.

INFINITY CHECK
------------------------------------------------------------------------------------------
Positive infinity cells : 0
Negative infinity cells : 0

DATA TYPE REPORT
------------------------------------------------------------------------------------------
                      Column Before_Data_Type After_Data_Type
                       Sr_No          float64         float64
        NPCI_Operated_System              str             str
FY_2022_2023_Q1_Volume_in_Mn           object          object
 FY_2022_2023_Q1_Value_in_Bn           object          object
FY_2022_2023_Q2_Volume_in_Mn           object          object
 FY_2022_2023_Q2_Value_in_Bn           object          object
FY_2022_2023_Q3_Volume_in_Mn           object          object
 FY_2022_2023_Q3_Value_in_Bn           object          object
FY_2022_2023_Q4_Volume_in_Mn           object          object
 FY_2022_2023_Q4_Value_in_Bn           object          object
   FY_2022_2023_Volume_in_Mn           object          object
    FY_2022_2023_Value_in_Bn           object          object
FY_2023_2024_Q1_Volume_in_Mn           object          object
 FY_2023_2024_Q1_Value_in_Bn           object          object
FY_2023_2024_Q2_Volume_in_Mn           object          object
 FY_2023_2024_Q2_Value_in_Bn           object          object
FY_2023_2024_Q3_Volume_in_Mn           object          object
 FY_2023_2024_Q3_Value_in_Bn           object          object
FY_2023_2024_Q4_Volume_in_Mn           object          object
 FY_2023_2024_Q4_Value_in_Bn           object          object
FY_2024_2025_Q1_Volume_in_Mn           object          object
 FY_2024_2025_Q1_Value_in_Bn           object          object
FY_2024_2025_Q2_Volume_in_Mn           object          object
 FY_2024_2025_Q2_Value_in_Bn           object          object
FY_2024_2025_Q3_Volume_in_Mn           object          object
 FY_2024_2025_Q3_Value_in_Bn           object          object
FY_2024_2025_Q4_Volume_in_Mn           object          object
 FY_2024_2025_Q4_Value_in_Bn           object          object
FY_2025_2026_Q1_Volume_in_Mn           object          object
 FY_2025_2026_Q1_Value_in_Bn           object          object
FY_2025_2026_Q2_Volume_in_Mn           object          object
 FY_2025_2026_Q2_Value_in_Bn           object          object
FY_2025_2026_Q3_Volume_in_Mn           object          object
 FY_2025_2026_Q3_Value_in_Bn           object          object
FY_2025_2026_Q4_Volume_in_Mn           object          object
 FY_2025_2026_Q4_Value_in_Bn           object          object
        2026_04_Volume_in_Mn           object          object
         2026_04_Value_in_Bn           object          object
        2026_05_Volume_in_Mn           object          object
         2026_05_Value_in_Bn           object          object
        2026_06_Volume_in_Mn           object          object
         2026_06_Value_in_Bn           object          object

==========================================================================================
STEP 3 VALIDATION
==========================================================================================
Missing cells before       : 251
Missing cells after        : 251
Missingness preserved      : True

Zero cells before          : 149
Zero cells after           : 149
Zero count preserved      : True

Transaction value mismatches : 0
Data values modified         : False
Imputation performed         : False
NaN converted to zero        : False

==========================================================================================
STEP 3 FINAL REPORT
==========================================================================================
Input file                      : NPCI_Step2_Structured.xlsx
Output file                     : NPCI_Step3_Cleaned.xlsx

Rows                            : 40
Columns                         : 42

Transaction columns             : 40
Volume columns                  : 20
Value columns                   : 20

Structural rows                 : 3
Transaction data rows           : 37

Missing cells before            : 251
Missing cells after             : 251
Missingness preserved            : True

Zero cells before               : 149
Zero cells after                : 149
Zero count preserved            : True

Numeric transaction cells       : 1262
Non-numeric transaction cells   : 0

Transaction values unchanged    : True
Data values modified            : False
Imputation performed            : False
NaN converted to zero           : False

Negative volume cells           : 0
Negative value cells            : 0
Positive infinity cells        : 0
Negative infinity cells        : 0

==========================================================================================
STEP 3 COMPLETE
==========================================================================================
✓ Input dimensions validated
✓ Transaction columns identified
✓ Structural rows identified
✓ Embedded header rows identified
✓ Structural rows preserved
✓ Numeric transaction data converted
✓ Missing values preserved
✓ Existing zeros preserved
✓ No values imputed
✓ No NaN converted to zero
✓ No negative transaction values
✓ No infinity values
✓ Transaction values unchanged
✓ Validation passed
✓ Checkpoint saved

Output file: NPCI_Step3_Cleaned.xlsx
==========================================================================================

In [13]:
# =============================================================================
# STEP 4: MISSING VALUE ANALYSIS & CONTROLLED CLEANING
# =============================================================================
#
# INPUT :
#     NPCI_Step3_Cleaned.xlsx
#
# OUTPUT:
#     NPCI_Step4_MissingValue_Handled.xlsx
#
# PRINCIPLES:
#     1. Preserve all structural / embedded-header rows.
#     2. Never convert missing values to zero automatically.
#     3. Never modify existing transaction values.
#     4. Never modify existing zeros.
#     5. Identify missing values separately from genuine zeros.
#     6. Do not perform statistical imputation at this stage.
#     7. Preserve the original row/column structure.
#
# =============================================================================


import pandas as pd
import numpy as np
import os
import re
from datetime import datetime


# =============================================================================
# CONFIGURATION
# =============================================================================

INPUT_FILE = "NPCI_Step3_Cleaned.xlsx"
OUTPUT_FILE = "NPCI_Step4_MissingValue_Handled.xlsx"


# =============================================================================
# HEADER
# =============================================================================

print("=" * 90)
print("STEP 4: MISSING VALUE ANALYSIS & CONTROLLED CLEANING")
print("=" * 90)


# =============================================================================
# INPUT VALIDATION
# =============================================================================

print("\nINPUT FILE")
print("-" * 90)
print(f"Input file : {INPUT_FILE}")

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}"
    )

df = pd.read_excel(INPUT_FILE)

print(f"Rows       : {df.shape[0]}")
print(f"Columns    : {df.shape[1]}")


# =============================================================================
# EXPECTED DIMENSIONS
# =============================================================================

assert df.shape == (40, 42), (
    f"Unexpected input dimensions: {df.shape}. "
    f"Expected (40, 42)."
)

print("✓ Input dimensions validated")


# =============================================================================
# EXPECTED CORE COLUMNS
# =============================================================================

required_columns = [
    "Sr_No",
    "NPCI_Operated_System"
]

for col in required_columns:
    assert col in df.columns, f"Required column missing: {col}"

print("\nCORE COLUMN VALIDATION")
print("-" * 90)
print("✓ Sr_No present")
print("✓ NPCI_Operated_System present")


# =============================================================================
# TRANSACTION COLUMN IDENTIFICATION
# =============================================================================

transaction_columns = [
    col for col in df.columns
    if (
        "_Volume_in_Mn" in str(col)
        or "_Value_in_Bn" in str(col)
    )
]

volume_columns = [
    col for col in transaction_columns
    if "_Volume_in_Mn" in str(col)
]

value_columns = [
    col for col in transaction_columns
    if "_Value_in_Bn" in str(col)
]


print("\nTRANSACTION COLUMN IDENTIFICATION")
print("-" * 90)
print(f"Transaction columns : {len(transaction_columns)}")
print(f"Volume columns      : {len(volume_columns)}")
print(f"Value columns       : {len(value_columns)}")


assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

print("✓ Transaction column structure validated")


# =============================================================================
# CREATE ORIGINAL COPY
# =============================================================================
#
# This copy is used for all before/after integrity checks.
#

df_original = df.copy(deep=True)


# =============================================================================
# STRUCTURAL ROW IDENTIFICATION
# =============================================================================
#
# There are two kinds of structural rows:
#
#   A. Embedded header rows:
#      contain "Volume (in Mn)" / "Value (in Bn)"
#
#   B. Rows without a system name:
#      blank NPCI_Operated_System
#
# These rows must NEVER be treated as transaction records.
# =============================================================================


system_series = df["NPCI_Operated_System"]


# Detect embedded headers
embedded_header_rows = []

for idx in df.index:

    row_values = df.loc[idx, transaction_columns]

    row_text = " ".join(
        str(x).strip()
        for x in row_values
        if pd.notna(x)
    ).lower()

    if (
        "volume (in mn)" in row_text
        or "value (in bn)" in row_text
    ):
        embedded_header_rows.append(idx)


# Detect rows without system name
empty_system_rows = []

for idx in df.index:

    value = df.loc[idx, "NPCI_Operated_System"]

    if pd.isna(value) or str(value).strip() == "":
        empty_system_rows.append(idx)


# Combined structural rows
structural_rows = sorted(
    set(embedded_header_rows + empty_system_rows)
)

transaction_rows = [
    idx for idx in df.index
    if idx not in structural_rows
]


print("\nSTRUCTURAL ROW IDENTIFICATION")
print("-" * 90)
print(f"Embedded header rows : {len(embedded_header_rows)}")
print(f"Embedded headers    : {embedded_header_rows}")

print(f"Empty-system rows    : {len(empty_system_rows)}")
print(f"Empty-system indices : {empty_system_rows}")

print(f"Structural rows      : {len(structural_rows)}")
print(f"Structural indices   : {structural_rows}")

print(f"Transaction rows     : {len(transaction_rows)}")

assert len(embedded_header_rows) == 2
assert len(empty_system_rows) == 2
assert len(structural_rows) == 3
assert len(transaction_rows) == 37

print("✓ Structural rows identified correctly")


# =============================================================================
# ORIGINAL MISSINGNESS ANALYSIS
# =============================================================================

print("\nORIGINAL MISSING VALUE ANALYSIS")
print("-" * 90)


# Missing transaction cells ONLY in genuine transaction rows
missing_transaction_before = (
    df_original.loc[
        transaction_rows,
        transaction_columns
    ].isna().sum().sum()
)


# Existing zero transaction cells
zero_transaction_before = (
    (
        df_original.loc[
            transaction_rows,
            transaction_columns
        ] == 0
    )
    .sum()
    .sum()
)


# Total missing cells in complete dataframe
missing_total_before = int(
    df_original.isna().sum().sum()
)


print(
    f"Missing transaction cells : "
    f"{missing_transaction_before}"
)

print(
    f"Zero transaction cells    : "
    f"{zero_transaction_before}"
)

print(
    f"Total missing cells       : "
    f"{missing_total_before}"
)


# =============================================================================
# MISSING VALUES BY COLUMN
# =============================================================================

missing_by_column_before = (
    df_original.loc[
        transaction_rows,
        transaction_columns
    ]
    .isna()
    .sum()
)


print("\nMISSING VALUES BY TRANSACTION COLUMN")
print("-" * 90)

for col, count in missing_by_column_before.items():

    if count > 0:
        print(f"{col:<55} : {int(count)}")


# =============================================================================
# MISSING VALUES BY TRANSACTION ROW
# =============================================================================

missing_by_row_before = (
    df_original.loc[
        transaction_rows,
        transaction_columns
    ]
    .isna()
    .sum(axis=1)
)


print("\nMISSING VALUES BY TRANSACTION ROW")
print("-" * 90)

rows_with_missing = (
    missing_by_row_before[
        missing_by_row_before > 0
    ]
)

print(
    f"Transaction rows containing missing values : "
    f"{len(rows_with_missing)}"
)


# =============================================================================
# MISSING VALUE PATTERN ANALYSIS
# =============================================================================

print("\nMISSING VALUE PATTERN ANALYSIS")
print("-" * 90)


# Count rows with all transaction values missing
all_missing_rows = []

# Count rows with partially missing transaction values
partial_missing_rows = []

# Count complete rows
complete_transaction_rows = []

for idx in transaction_rows:

    row = df_original.loc[idx, transaction_columns]

    missing_count = row.isna().sum()

    if missing_count == len(transaction_columns):

        all_missing_rows.append(idx)

    elif missing_count > 0:

        partial_missing_rows.append(idx)

    else:

        complete_transaction_rows.append(idx)


print(
    f"Rows with all transaction values missing : "
    f"{len(all_missing_rows)}"
)

print(
    f"Rows with partial missing values          : "
    f"{len(partial_missing_rows)}"
)

print(
    f"Rows with complete transaction data       : "
    f"{len(complete_transaction_rows)}"
)


# =============================================================================
# DECISION
# =============================================================================
#
# IMPORTANT:
#
# No automatic imputation is performed.
#
# Reasons:
#
#   - A missing transaction value is not necessarily zero.
#   - Forward fill could incorrectly copy values between payment systems.
#   - Mean/median imputation would create artificial financial data.
#   - Zero replacement would change the meaning of the source data.
#
# Therefore Step 4 records and validates missingness but preserves it.
# =============================================================================


print("\nMISSING VALUE HANDLING DECISION")
print("-" * 90)

print("✓ Missing values identified.")
print("✓ Missing values are NOT imputed.")
print("✓ Missing values are NOT converted to zero.")
print("✓ Existing zeros are preserved.")
print("✓ Structural rows are preserved.")
print("✓ Original transaction values are preserved.")


# =============================================================================
# NO DATA MODIFICATION
# =============================================================================
#
# Make a deep copy and intentionally leave missing values unchanged.
#

df_cleaned = df_original.copy(deep=True)


# =============================================================================
# DATA TYPE VALIDATION
# =============================================================================

print("\nTRANSACTION DATA VALIDATION")
print("-" * 90)


non_numeric_cells = 0
numeric_cells = 0

for col in transaction_columns:

    values = df_cleaned.loc[
        transaction_rows,
        col
    ]

    numeric_values = pd.to_numeric(
        values,
        errors="coerce"
    )

    # Values that are neither numeric nor missing
    invalid_mask = (
        values.notna()
        & numeric_values.isna()
    )

    invalid_count = int(invalid_mask.sum())

    non_numeric_cells += invalid_count

    numeric_cells += int(
        numeric_values.notna().sum()
    )


print(
    f"Numeric transaction cells    : "
    f"{numeric_cells}"
)

print(
    f"Non-numeric transaction cells : "
    f"{non_numeric_cells}"
)

assert non_numeric_cells == 0

print(
    "✓ All genuine transaction cells are "
    "numeric or missing."
)


# =============================================================================
# NEGATIVE VALUE CHECK
# =============================================================================

print("\nNEGATIVE VALUE CHECK")
print("-" * 90)


negative_volume_cells = 0
negative_value_cells = 0


for col in volume_columns:

    values = pd.to_numeric(
        df_cleaned.loc[
            transaction_rows,
            col
        ],
        errors="coerce"
    )

    negative_volume_cells += int(
        (values < 0).sum()
    )


for col in value_columns:

    values = pd.to_numeric(
        df_cleaned.loc[
            transaction_rows,
            col
        ],
        errors="coerce"
    )

    negative_value_cells += int(
        (values < 0).sum()
    )


print(
    f"Negative volume cells : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells  : "
    f"{negative_value_cells}"
)

assert negative_volume_cells == 0
assert negative_value_cells == 0

print("✓ No negative transaction values detected.")


# =============================================================================
# INFINITY CHECK
# =============================================================================

print("\nINFINITY CHECK")
print("-" * 90)


positive_infinity_cells = 0
negative_infinity_cells = 0


for col in transaction_columns:

    values = pd.to_numeric(
        df_cleaned.loc[
            transaction_rows,
            col
        ],
        errors="coerce"
    )

    positive_infinity_cells += int(
        np.isposinf(values).sum()
    )

    negative_infinity_cells += int(
        np.isneginf(values).sum()
    )


print(
    f"Positive infinity cells : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells : "
    f"{negative_infinity_cells}"
)

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

print("✓ No infinity values detected.")


# =============================================================================
# STRUCTURAL ROW INTEGRITY CHECK
# =============================================================================

print("\nSTRUCTURAL ROW INTEGRITY CHECK")
print("-" * 90)


structural_values_match = True

for idx in structural_rows:

    original_row = df_original.loc[
        idx,
        transaction_columns
    ]

    cleaned_row = df_cleaned.loc[
        idx,
        transaction_columns
    ]

    if not original_row.equals(cleaned_row):
        structural_values_match = False
        print(
            f"⚠ Structural row changed: {idx}"
        )


assert structural_values_match

print("✓ Structural transaction cells unchanged.")


# =============================================================================
# TRANSACTION VALUE INTEGRITY CHECK
# =============================================================================

print("\nTRANSACTION VALUE INTEGRITY CHECK")
print("-" * 90)


transaction_value_mismatches = 0


for idx in transaction_rows:

    for col in transaction_columns:

        original_value = df_original.loc[idx, col]
        cleaned_value = df_cleaned.loc[idx, col]

        # Both missing
        if pd.isna(original_value) and pd.isna(cleaned_value):
            continue

        # One missing and one non-missing
        if pd.isna(original_value) != pd.isna(cleaned_value):
            transaction_value_mismatches += 1
            continue

        # Numeric comparison
        try:

            original_numeric = float(original_value)
            cleaned_numeric = float(cleaned_value)

            if not np.isclose(
                original_numeric,
                cleaned_numeric,
                equal_nan=True
            ):
                transaction_value_mismatches += 1

        except (ValueError, TypeError):

            if original_value != cleaned_value:
                transaction_value_mismatches += 1


print(
    f"Transaction value mismatches : "
    f"{transaction_value_mismatches}"
)

assert transaction_value_mismatches == 0

print("✓ All transaction values unchanged.")


# =============================================================================
# MISSINGNESS AFTER CLEANING
# =============================================================================

missing_transaction_after = (
    df_cleaned.loc[
        transaction_rows,
        transaction_columns
    ].isna().sum().sum()
)


zero_transaction_after = (
    (
        df_cleaned.loc[
            transaction_rows,
            transaction_columns
        ] == 0
    )
    .sum()
    .sum()
)


missing_total_after = int(
    df_cleaned.isna().sum().sum()
)


# =============================================================================
# VALIDATION FLAGS
# =============================================================================

missingness_preserved = (
    missing_transaction_before
    == missing_transaction_after
)

zero_count_preserved = (
    zero_transaction_before
    == zero_transaction_after
)

transaction_values_match = (
    transaction_value_mismatches == 0
)

row_count_preserved = (
    df_original.shape[0]
    == df_cleaned.shape[0]
)

column_count_preserved = (
    df_original.shape[1]
    == df_cleaned.shape[1]
)


# =============================================================================
# FINAL VALIDATION
# =============================================================================

print("\n" + "=" * 90)
print("STEP 4 VALIDATION")
print("=" * 90)

print(
    f"Missing transaction cells before : "
    f"{missing_transaction_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_transaction_after}"
)

print(
    f"Missingness preserved             : "
    f"{missingness_preserved}"
)

print()

print(
    f"Zero transaction cells before     : "
    f"{zero_transaction_before}"
)

print(
    f"Zero transaction cells after      : "
    f"{zero_transaction_after}"
)

print(
    f"Zero count preserved              : "
    f"{zero_count_preserved}"
)

print()

print(
    f"Transaction value mismatches      : "
    f"{transaction_value_mismatches}"
)

print(
    f"Transaction values unchanged      : "
    f"{transaction_values_match}"
)

print(
    f"Rows preserved                    : "
    f"{row_count_preserved}"
)

print(
    f"Columns preserved                 : "
    f"{column_count_preserved}"
)


# =============================================================================
# ASSERTIONS
# =============================================================================

assert row_count_preserved
assert column_count_preserved

assert missingness_preserved
assert zero_count_preserved

assert transaction_values_match

assert structural_values_match

assert non_numeric_cells == 0

assert negative_volume_cells == 0
assert negative_value_cells == 0

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0


# =============================================================================
# SAVE CHECKPOINT
# =============================================================================

df_cleaned.to_excel(
    OUTPUT_FILE,
    index=False
)


# =============================================================================
# VERIFY SAVED FILE
# =============================================================================

if not os.path.exists(OUTPUT_FILE):
    raise IOError(
        f"Output file was not created: {OUTPUT_FILE}"
    )


# Reload output for final checkpoint verification
df_saved = pd.read_excel(OUTPUT_FILE)


assert df_saved.shape == df_original.shape


# Verify transaction values after Excel round-trip
saved_transaction_mismatches = 0

for idx in transaction_rows:

    for col in transaction_columns:

        original_value = df_original.loc[idx, col]
        saved_value = df_saved.loc[idx, col]

        if pd.isna(original_value) and pd.isna(saved_value):
            continue

        if pd.isna(original_value) != pd.isna(saved_value):
            saved_transaction_mismatches += 1
            continue

        try:

            if not np.isclose(
                float(original_value),
                float(saved_value),
                equal_nan=True
            ):
                saved_transaction_mismatches += 1

        except (ValueError, TypeError):

            if original_value != saved_value:
                saved_transaction_mismatches += 1


assert saved_transaction_mismatches == 0


# =============================================================================
# FINAL REPORT
# =============================================================================

print("\n" + "=" * 90)
print("STEP 4 FINAL REPORT")
print("=" * 90)

print(
    f"Input file                       : "
    f"{INPUT_FILE}"
)

print(
    f"Output file                      : "
    f"{OUTPUT_FILE}"
)

print()

print(
    f"Rows                             : "
    f"{df_cleaned.shape[0]}"
)

print(
    f"Columns                          : "
    f"{df_cleaned.shape[1]}"
)

print()

print(
    f"Transaction columns              : "
    f"{len(transaction_columns)}"
)

print(
    f"Volume columns                   : "
    f"{len(volume_columns)}"
)

print(
    f"Value columns                    : "
    f"{len(value_columns)}"
)

print()

print(
    f"Structural rows                  : "
    f"{len(structural_rows)}"
)

print(
    f"Transaction data rows            : "
    f"{len(transaction_rows)}"
)

print()

print(
    f"Missing transaction cells before : "
    f"{missing_transaction_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_transaction_after}"
)

print(
    f"Missingness preserved             : "
    f"{missingness_preserved}"
)

print()

print(
    f"Zero transaction cells before    : "
    f"{zero_transaction_before}"
)

print(
    f"Zero transaction cells after     : "
    f"{zero_transaction_after}"
)

print(
    f"Zero count preserved              : "
    f"{zero_count_preserved}"
)

print()

print(
    f"Numeric transaction cells        : "
    f"{numeric_cells}"
)

print(
    f"Non-numeric transaction cells    : "
    f"{non_numeric_cells}"
)

print()

print(
    f"Transaction value mismatches     : "
    f"{transaction_value_mismatches}"
)

print(
    f"Saved-file mismatches             : "
    f"{saved_transaction_mismatches}"
)

print()

print(
    f"Missing values imputed            : False"
)

print(
    f"NaN converted to zero             : False"
)

print(
    f"Data values modified              : False"
)

print(
    f"Negative volume cells             : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells              : "
    f"{negative_value_cells}"
)

print(
    f"Positive infinity cells          : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells          : "
    f"{negative_infinity_cells}"
)


# =============================================================================
# SUCCESS
# =============================================================================

print("\n" + "=" * 90)
print("STEP 4 COMPLETE")
print("=" * 90)

print("✓ Input dimensions validated")
print("✓ Transaction columns identified")
print("✓ Structural rows preserved")
print("✓ Embedded header rows preserved")
print("✓ Missing values identified")
print("✓ Missing values preserved")
print("✓ Existing zeros preserved")
print("✓ No missing-value imputation performed")
print("✓ No NaN converted to zero")
print("✓ No transaction values modified")
print("✓ No negative transaction values")
print("✓ No infinity values")
print("✓ Transaction values validated")
print("✓ Saved-file integrity validated")
print("✓ All assertions passed")
print("✓ Checkpoint saved")

print()
print(f"Output file: {OUTPUT_FILE}")
print("=" * 90)

==========================================================================================
STEP 4: MISSING VALUE ANALYSIS & CONTROLLED CLEANING
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI_Step3_Cleaned.xlsx
Rows       : 40
Columns    : 42
✓ Input dimensions validated

CORE COLUMN VALIDATION
------------------------------------------------------------------------------------------
✓ Sr_No present
✓ NPCI_Operated_System present

TRANSACTION COLUMN IDENTIFICATION
------------------------------------------------------------------------------------------
Transaction columns : 40
Volume columns      : 20
Value columns       : 20
✓ Transaction column structure validated

STRUCTURAL ROW IDENTIFICATION
------------------------------------------------------------------------------------------
Embedded header rows : 2
Embedded headers    : [0, 29]
Empty-system rows    : 2
Empty-system indices : [29, 39]
Structural rows      : 3
Structural indices   : [0, 29, 39]
Transaction rows     : 37
✓ Structural rows identified correctly

ORIGINAL MISSING VALUE ANALYSIS
------------------------------------------------------------------------------------------
Missing transaction cells : 218
Zero transaction cells    : 142
Total missing cells       : 264

MISSING VALUES BY TRANSACTION COLUMN
------------------------------------------------------------------------------------------
FY_2022_2023_Q1_Value_in_Bn                             : 9
FY_2022_2023_Q2_Value_in_Bn                             : 9
FY_2022_2023_Q3_Value_in_Bn                             : 9
FY_2022_2023_Q4_Volume_in_Mn                            : 1
FY_2022_2023_Q4_Value_in_Bn                             : 8
FY_2022_2023_Volume_in_Mn                               : 1
FY_2022_2023_Value_in_Bn                                : 9
FY_2023_2024_Q1_Value_in_Bn                             : 8
FY_2023_2024_Q2_Value_in_Bn                             : 9
FY_2023_2024_Q3_Volume_in_Mn                            : 1
FY_2023_2024_Q3_Value_in_Bn                             : 9
FY_2023_2024_Q4_Volume_in_Mn                            : 4
FY_2023_2024_Q4_Value_in_Bn                             : 13
FY_2024_2025_Q1_Volume_in_Mn                            : 4
FY_2024_2025_Q1_Value_in_Bn                             : 12
FY_2024_2025_Q2_Volume_in_Mn                            : 3
FY_2024_2025_Q2_Value_in_Bn                             : 13
FY_2024_2025_Q3_Volume_in_Mn                            : 4
FY_2024_2025_Q3_Value_in_Bn                             : 13
FY_2025_2026_Q1_Value_in_Bn                             : 9
FY_2025_2026_Q2_Volume_in_Mn                            : 5
FY_2025_2026_Q2_Value_in_Bn                             : 5
FY_2025_2026_Q4_Volume_in_Mn                            : 1
FY_2025_2026_Q4_Value_in_Bn                             : 9
2026_04_Volume_in_Mn                                    : 3
2026_04_Value_in_Bn                                     : 11
2026_05_Volume_in_Mn                                    : 5
2026_05_Value_in_Bn                                     : 13
2026_06_Volume_in_Mn                                    : 5
2026_06_Value_in_Bn                                     : 13

MISSING VALUES BY TRANSACTION ROW
------------------------------------------------------------------------------------------
Transaction rows containing missing values : 13

MISSING VALUE PATTERN ANALYSIS
------------------------------------------------------------------------------------------
Rows with all transaction values missing : 0
Rows with partial missing values          : 13
Rows with complete transaction data       : 24

MISSING VALUE HANDLING DECISION
------------------------------------------------------------------------------------------
✓ Missing values identified.
✓ Missing values are NOT imputed.
✓ Missing values are NOT converted to zero.
✓ Existing zeros are preserved.
✓ Structural rows are preserved.
✓ Original transaction values are preserved.

TRANSACTION DATA VALIDATION
------------------------------------------------------------------------------------------
Numeric transaction cells    : 1262
Non-numeric transaction cells : 0
✓ All genuine transaction cells are numeric or missing.

NEGATIVE VALUE CHECK
------------------------------------------------------------------------------------------
Negative volume cells : 0
Negative value cells  : 0
✓ No negative transaction values detected.

INFINITY CHECK
------------------------------------------------------------------------------------------
Positive infinity cells : 0
Negative infinity cells : 0
✓ No infinity values detected.

STRUCTURAL ROW INTEGRITY CHECK
------------------------------------------------------------------------------------------
✓ Structural transaction cells unchanged.

TRANSACTION VALUE INTEGRITY CHECK
------------------------------------------------------------------------------------------
Transaction value mismatches : 0
✓ All transaction values unchanged.

==========================================================================================
STEP 4 VALIDATION
==========================================================================================
Missing transaction cells before : 218
Missing transaction cells after  : 218
Missingness preserved             : True

Zero transaction cells before     : 142
Zero transaction cells after      : 142
Zero count preserved              : True

Transaction value mismatches      : 0
Transaction values unchanged      : True
Rows preserved                    : True
Columns preserved                 : True

==========================================================================================
STEP 4 FINAL REPORT
==========================================================================================
Input file                       : NPCI_Step3_Cleaned.xlsx
Output file                      : NPCI_Step4_MissingValue_Handled.xlsx

Rows                             : 40
Columns                          : 42

Transaction columns              : 40
Volume columns                   : 20
Value columns                    : 20

Structural rows                  : 3
Transaction data rows            : 37

Missing transaction cells before : 218
Missing transaction cells after  : 218
Missingness preserved             : True

Zero transaction cells before    : 142
Zero transaction cells after     : 142
Zero count preserved              : True

Numeric transaction cells        : 1262
Non-numeric transaction cells    : 0

Transaction value mismatches     : 0
Saved-file mismatches             : 0

Missing values imputed            : False
NaN converted to zero             : False
Data values modified              : False
Negative volume cells             : 0
Negative value cells              : 0
Positive infinity cells          : 0
Negative infinity cells          : 0

==========================================================================================
STEP 4 COMPLETE
==========================================================================================
✓ Input dimensions validated
✓ Transaction columns identified
✓ Structural rows preserved
✓ Embedded header rows preserved
✓ Missing values identified
✓ Missing values preserved
✓ Existing zeros preserved
✓ No missing-value imputation performed
✓ No NaN converted to zero
✓ No transaction values modified
✓ No negative transaction values
✓ No infinity values
✓ Transaction values validated
✓ Saved-file integrity validated
✓ All assertions passed
✓ Checkpoint saved

Output file: NPCI_Step4_MissingValue_Handled.xlsx
==========================================================================================

In [14]:
# ============================================================================
# STEP 5: DUPLICATE RECORD ANALYSIS & CONTROLLED CLEANING
# ============================================================================
#
# INPUT:
#     NPCI_Step4_MissingValue_Handled.xlsx
#
# OUTPUT:
#     NPCI_Step5_Duplicate_Handled.xlsx
#
# PURPOSE:
#     1. Validate the Step 4 checkpoint
#     2. Identify structural rows
#     3. Detect exact duplicate transaction records
#     4. Remove only exact duplicate transaction rows
#     5. Preserve structural/header rows
#     6. Preserve all transaction values
#     7. Validate the saved output
#
# IMPORTANT:
#     - No missing-value imputation
#     - No NaN-to-zero conversion
#     - No numerical transformations
#     - No negative-value correction
#     - No modification of genuine transaction values
# ============================================================================

import os
import re
import numpy as np
import pandas as pd


# ============================================================================
# CONFIGURATION
# ============================================================================

INPUT_FILE = "NPCI_Step4_MissingValue_Handled.xlsx"
OUTPUT_FILE = "NPCI_Step5_Duplicate_Handled.xlsx"

EXPECTED_ROWS = 40
EXPECTED_COLUMNS = 42
EXPECTED_TRANSACTION_COLUMNS = 40
EXPECTED_VOLUME_COLUMNS = 20
EXPECTED_VALUE_COLUMNS = 20


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def is_blank(value):
    """Return True for NaN/None/empty/whitespace-only values."""
    if pd.isna(value):
        return True
    return str(value).strip() == ""


def is_embedded_header_row(row, transaction_columns):
    """
    Detect embedded header rows such as:
        Volume (in Mn)
        Value (in Bn)
    """
    header_values = 0

    for col in transaction_columns:
        value = row[col]

        if pd.isna(value):
            continue

        text = str(value).strip().lower()

        if text in {
            "volume (in mn)",
            "value (in bn)"
        }:
            header_values += 1

    return header_values >= max(2, len(transaction_columns) // 4)


# ============================================================================
# STEP 5 HEADER
# ============================================================================

print("=" * 90)
print("STEP 5: DUPLICATE RECORD ANALYSIS & CONTROLLED CLEANING")
print("=" * 90)


# ============================================================================
# LOAD INPUT
# ============================================================================

print("\nINPUT FILE")
print("-" * 90)
print(f"Input file : {INPUT_FILE}")

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}"
    )

df_original = pd.read_excel(INPUT_FILE)

df = df_original.copy(deep=True)

print(f"Rows       : {df.shape[0]}")
print(f"Columns    : {df.shape[1]}")


# ============================================================================
# INPUT DIMENSION VALIDATION
# ============================================================================

assert df.shape[0] == EXPECTED_ROWS, (
    f"Expected {EXPECTED_ROWS} rows, found {df.shape[0]}"
)

assert df.shape[1] == EXPECTED_COLUMNS, (
    f"Expected {EXPECTED_COLUMNS} columns, found {df.shape[1]}"
)

print("✓ Input dimensions validated")


# ============================================================================
# CORE COLUMN VALIDATION
# ============================================================================

print("\nCORE COLUMN VALIDATION")
print("-" * 90)

assert "Sr_No" in df.columns
assert "NPCI_Operated_System" in df.columns

print("✓ Sr_No present")
print("✓ NPCI_Operated_System present")


# ============================================================================
# TRANSACTION COLUMN IDENTIFICATION
# ============================================================================

transaction_columns = [
    col for col in df.columns
    if re.search(r"_(Volume|Value)_in_", str(col))
]

volume_columns = [
    col for col in transaction_columns
    if "_Volume_in_" in str(col)
]

value_columns = [
    col for col in transaction_columns
    if "_Value_in_" in str(col)
]

print("\nTRANSACTION COLUMN IDENTIFICATION")
print("-" * 90)

print(f"Transaction columns : {len(transaction_columns)}")
print(f"Volume columns      : {len(volume_columns)}")
print(f"Value columns       : {len(value_columns)}")

assert len(transaction_columns) == EXPECTED_TRANSACTION_COLUMNS
assert len(volume_columns) == EXPECTED_VOLUME_COLUMNS
assert len(value_columns) == EXPECTED_VALUE_COLUMNS

print("✓ Transaction column structure validated")


# ============================================================================
# ORIGINAL DATA SNAPSHOT
# ============================================================================

df_before = df.copy(deep=True)


# ============================================================================
# STRUCTURAL ROW IDENTIFICATION
# ============================================================================

print("\nSTRUCTURAL ROW IDENTIFICATION")
print("-" * 90)

system_col = "NPCI_Operated_System"

empty_system_indices = [
    idx
    for idx in df.index
    if is_blank(df.loc[idx, system_col])
]

embedded_header_indices = [
    idx
    for idx in df.index
    if is_embedded_header_row(
        df.loc[idx],
        transaction_columns
    )
]

structural_indices = sorted(
    set(empty_system_indices) |
    set(embedded_header_indices)
)

transaction_indices = [
    idx
    for idx in df.index
    if idx not in structural_indices
]

print(f"Embedded header rows : {len(embedded_header_indices)}")
print(f"Embedded headers    : {embedded_header_indices}")

print(f"Empty-system rows    : {len(empty_system_indices)}")
print(f"Empty-system indices : {empty_system_indices}")

print(f"Structural rows      : {len(structural_indices)}")
print(f"Structural indices   : {structural_indices}")

print(f"Transaction rows     : {len(transaction_indices)}")

assert len(transaction_indices) + len(structural_indices) == len(df)

print("✓ Structural rows identified correctly")


# ============================================================================
# STRUCTURAL ROW SNAPSHOT
# ============================================================================

structural_before = (
    df_before.loc[structural_indices].copy(deep=True)
)


# ============================================================================
# TRANSACTION VALUE SNAPSHOT
# ============================================================================

transaction_before = (
    df_before.loc[transaction_indices, transaction_columns]
    .copy(deep=True)
)


# ============================================================================
# MISSING / ZERO COUNTS BEFORE
# ============================================================================

missing_before = int(
    df_before.loc[
        transaction_indices,
        transaction_columns
    ].isna().sum().sum()
)

zero_before = int(
    (
        df_before.loc[
            transaction_indices,
            transaction_columns
        ] == 0
    ).sum().sum()
)

print("\nORIGINAL TRANSACTION STATE")
print("-" * 90)

print(f"Missing transaction cells : {missing_before}")
print(f"Zero transaction cells    : {zero_before}")


# ============================================================================
# DUPLICATE ANALYSIS
# ============================================================================

print("\nDUPLICATE RECORD ANALYSIS")
print("-" * 90)

transaction_df = df.loc[
    transaction_indices
].copy(deep=True)

# Exact duplicate means every column in the transaction row is identical.
duplicate_mask = transaction_df.duplicated(
    keep="first"
)

duplicate_indices = transaction_df.index[
    duplicate_mask
].tolist()

duplicate_count = len(duplicate_indices)

print(f"Exact duplicate transaction rows : {duplicate_count}")

if duplicate_count > 0:
    print(f"Duplicate row indices             : {duplicate_indices}")
else:
    print("✓ No exact duplicate transaction rows detected.")


# ============================================================================
# DUPLICATE KEY ANALYSIS
# ============================================================================
#
# A second check based on the complete row is performed independently.
# This confirms the duplicate detection result.
# ============================================================================

duplicate_key_mask = (
    transaction_df
    .astype(object)
    .apply(
        lambda row: tuple(
            "__NA__" if pd.isna(x) else x
            for x in row
        ),
        axis=1
    )
    .duplicated(keep="first")
)

duplicate_key_indices = transaction_df.index[
    duplicate_key_mask
].tolist()

assert duplicate_indices == duplicate_key_indices

print("✓ Independent duplicate-key validation passed")


# ============================================================================
# CONTROLLED CLEANING
# ============================================================================

print("\nCONTROLLED DUPLICATE HANDLING")
print("-" * 90)

if duplicate_count > 0:

    # Remove ONLY duplicate transaction rows.
    df_cleaned = df.drop(
        index=duplicate_indices
    ).copy(deep=True)

    print(
        f"✓ Removed {duplicate_count} exact duplicate "
        f"transaction row(s)."
    )

else:

    # No duplicate rows: preserve the dataframe exactly.
    df_cleaned = df.copy(deep=True)

    print("✓ No rows removed.")
    print("✓ Input data preserved exactly.")


# ============================================================================
# STRUCTURAL ROW VALIDATION AFTER CLEANING
# ============================================================================

remaining_structural_indices = [
    idx for idx in structural_indices
    if idx in df_cleaned.index
]

assert len(remaining_structural_indices) == len(structural_indices)

structural_after = (
    df_cleaned.loc[
        remaining_structural_indices
    ].copy(deep=True)
)

# Compare structural rows using their original indices.
pd.testing.assert_frame_equal(
    structural_before,
    structural_after,
    check_dtype=False
)

print("✓ Structural rows preserved")


# ============================================================================
# TRANSACTION ROWS AFTER CLEANING
# ============================================================================

remaining_transaction_indices = [
    idx for idx in transaction_indices
    if idx in df_cleaned.index
]

transaction_after = (
    df_cleaned.loc[
        remaining_transaction_indices,
        transaction_columns
    ].copy(deep=True)
)


# ============================================================================
# VALUE INTEGRITY
# ============================================================================
#
# Every remaining transaction row must have exactly the same values as
# before Step 5.
# ============================================================================

original_remaining = (
    transaction_before.loc[
        remaining_transaction_indices
    ]
)

pd.testing.assert_frame_equal(
    original_remaining,
    transaction_after,
    check_dtype=False
)

print("✓ All retained transaction values unchanged")


# ============================================================================
# MISSING VALUE VALIDATION
# ============================================================================

missing_after = int(
    df_cleaned.loc[
        remaining_transaction_indices,
        transaction_columns
    ].isna().sum().sum()
)

zero_after = int(
    (
        df_cleaned.loc[
            remaining_transaction_indices,
            transaction_columns
        ] == 0
    ).sum().sum()
)

print("\nMISSING / ZERO VALIDATION")
print("-" * 90)

print(f"Missing transaction cells before : {missing_before}")
print(f"Missing transaction cells after  : {missing_after}")

print(f"Zero transaction cells before    : {zero_before}")
print(f"Zero transaction cells after     : {zero_after}")

# Duplicate removal should not change values in retained rows.
# Therefore, missing/zero counts are allowed to decrease only if a removed
# duplicate itself contained missing/zero cells.
#
# We validate this explicitly rather than incorrectly demanding equality.

removed_transaction = transaction_before.loc[
    duplicate_indices
]

removed_missing = int(
    removed_transaction.isna().sum().sum()
)

removed_zero = int(
    (removed_transaction == 0).sum().sum()
)

expected_missing_after = missing_before - removed_missing
expected_zero_after = zero_before - removed_zero

assert missing_after == expected_missing_after
assert zero_after == expected_zero_after

print("✓ Missing-value accounting validated")
print("✓ Zero-value accounting validated")


# ============================================================================
# NUMERIC DATA VALIDATION
# ============================================================================

print("\nTRANSACTION DATA TYPE VALIDATION")
print("-" * 90)

transaction_data = df_cleaned.loc[
    remaining_transaction_indices,
    transaction_columns
]

numeric_mask = transaction_data.apply(
    lambda col: pd.to_numeric(
        col,
        errors="coerce"
    ).notna() | col.isna()
)

non_numeric_transaction_cells = int(
    (~numeric_mask).sum().sum()
)

numeric_transaction_cells = int(
    transaction_data.size -
    transaction_data.isna().sum().sum() -
    non_numeric_transaction_cells
)

print(
    f"Numeric transaction data cells    : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells     : "
    f"{non_numeric_transaction_cells}"
)

assert non_numeric_transaction_cells == 0

print("✓ All genuine transaction cells are numeric or missing")


# ============================================================================
# NEGATIVE VALUE CHECK
# ============================================================================

print("\nNEGATIVE VALUE CHECK")
print("-" * 90)

volume_data = transaction_data[volume_columns]
value_data = transaction_data[value_columns]

negative_volume_cells = int(
    (volume_data < 0).sum().sum()
)

negative_value_cells = int(
    (value_data < 0).sum().sum()
)

print(f"Negative volume cells : {negative_volume_cells}")
print(f"Negative value cells  : {negative_value_cells}")

assert negative_volume_cells == 0
assert negative_value_cells == 0

print("✓ No negative transaction values detected")


# ============================================================================
# INFINITY CHECK
# ============================================================================

print("\nINFINITY CHECK")
print("-" * 90)

numeric_transaction_data = transaction_data.apply(
    pd.to_numeric,
    errors="coerce"
)

positive_infinity_cells = int(
    np.isposinf(
        numeric_transaction_data.to_numpy(
            dtype=float
        )
    ).sum()
)

negative_infinity_cells = int(
    np.isneginf(
        numeric_transaction_data.to_numpy(
            dtype=float
        )
    ).sum()
)

print(
    f"Positive infinity cells : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells : "
    f"{negative_infinity_cells}"
)

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

print("✓ No infinity values detected")


# ============================================================================
# DUPLICATE VALIDATION AFTER CLEANING
# ============================================================================

print("\nDUPLICATE VALIDATION AFTER CLEANING")
print("-" * 90)

clean_transaction_df = df_cleaned.loc[
    remaining_transaction_indices
]

remaining_duplicates = int(
    clean_transaction_df.duplicated(
        keep=False
    ).sum()
)

# Since all exact duplicates were removed, none should remain.
assert remaining_duplicates == 0

print("✓ No exact duplicate transaction records remain")


# ============================================================================
# ROW / COLUMN STRUCTURE VALIDATION
# ============================================================================

print("\nSTRUCTURAL VALIDATION")
print("-" * 90)

assert df_cleaned.shape[1] == EXPECTED_COLUMNS

assert set(df_cleaned.columns) == set(
    df_original.columns
)

print("✓ Column structure preserved")

expected_rows_after = (
    EXPECTED_ROWS - duplicate_count
)

assert df_cleaned.shape[0] == expected_rows_after

print(
    f"✓ Row count validated: "
    f"{df_cleaned.shape[0]}"
)


# ============================================================================
# SAVE OUTPUT
# ============================================================================

print("\nSAVING STEP 5 CHECKPOINT")
print("-" * 90)

df_cleaned.to_excel(
    OUTPUT_FILE,
    index=False
)

assert os.path.exists(OUTPUT_FILE)

print(f"✓ Checkpoint saved: {OUTPUT_FILE}")


# ============================================================================
# RELOAD SAVED FILE
# ============================================================================

df_saved = pd.read_excel(
    OUTPUT_FILE
)


# ============================================================================
# SAVED FILE VALIDATION
# ============================================================================

print("\nSAVED-FILE INTEGRITY VALIDATION")
print("-" * 90)

assert df_saved.shape == df_cleaned.shape

assert list(df_saved.columns) == list(
    df_cleaned.columns
)

print("✓ Saved dimensions validated")
print("✓ Saved column structure validated")


# ============================================================================
# SAVED TRANSACTION VALUE VALIDATION
# ============================================================================

saved_transaction_data = df_saved.loc[
    df_cleaned.index,
    transaction_columns
]

# Because Excel reload can change dtype representations, compare values
# after normalizing numerically where applicable.

for idx in df_cleaned.index:

    for col in transaction_columns:

        original_value = df_cleaned.loc[idx, col]
        saved_value = df_saved.loc[idx, col]

        if pd.isna(original_value) and pd.isna(saved_value):
            continue

        if isinstance(original_value, (int, float, np.number)):
            assert np.isclose(
                float(original_value),
                float(saved_value),
                equal_nan=True
            )
        else:
            assert str(original_value) == str(saved_value)


print("✓ Saved-file transaction values validated")


# ============================================================================
# FINAL COUNTS FROM SAVED FILE
# ============================================================================

saved_transaction_indices = [
    idx
    for idx in df_saved.index
    if not is_blank(
        df_saved.loc[idx, system_col]
    )
    and not is_embedded_header_row(
        df_saved.loc[idx],
        transaction_columns
    )
]

saved_transaction_data = df_saved.loc[
    saved_transaction_indices,
    transaction_columns
]

saved_missing = int(
    saved_transaction_data.isna().sum().sum()
)

saved_zero = int(
    (saved_transaction_data == 0).sum().sum()
)

saved_numeric_mask = saved_transaction_data.apply(
    lambda col: pd.to_numeric(
        col,
        errors="coerce"
    ).notna() | col.isna()
)

saved_non_numeric_cells = int(
    (~saved_numeric_mask).sum().sum()
)


# ============================================================================
# STEP 5 VALIDATION
# ============================================================================

print("\n" + "=" * 90)
print("STEP 5 VALIDATION")
print("=" * 90)

print(
    f"Duplicate transaction rows detected : "
    f"{duplicate_count}"
)

print(
    f"Duplicate transaction rows removed  : "
    f"{duplicate_count}"
)

print(
    f"Rows before                        : "
    f"{df_original.shape[0]}"
)

print(
    f"Rows after                         : "
    f"{df_cleaned.shape[0]}"
)

print(
    f"Columns before                     : "
    f"{df_original.shape[1]}"
)

print(
    f"Columns after                      : "
    f"{df_cleaned.shape[1]}"
)

print(
    f"Missing transaction cells before   : "
    f"{missing_before}"
)

print(
    f"Missing transaction cells after    : "
    f"{missing_after}"
)

print(
    f"Zero transaction cells before      : "
    f"{zero_before}"
)

print(
    f"Zero transaction cells after       : "
    f"{zero_after}"
)

print(
    f"Non-numeric transaction cells      : "
    f"{non_numeric_transaction_cells}"
)

print(
    f"Remaining duplicate rows           : "
    f"{remaining_duplicates}"
)

print(
    f"Negative volume cells              : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells               : "
    f"{negative_value_cells}"
)

print(
    f"Positive infinity cells            : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells            : "
    f"{negative_infinity_cells}"
)

print("✓ Structural rows preserved")
print("✓ Retained transaction values unchanged")
print("✓ Missing-value accounting validated")
print("✓ Existing zero-value accounting validated")
print("✓ No negative transaction values")
print("✓ No infinity values")
print("✓ No exact duplicate transaction records remain")
print("✓ Saved-file integrity validated")


# ============================================================================
# FINAL REPORT
# ============================================================================

print("\n" + "=" * 90)
print("STEP 5 FINAL REPORT")
print("=" * 90)

print(f"Input file                       : {INPUT_FILE}")
print(f"Output file                      : {OUTPUT_FILE}")

print(f"\nRows before                      : {df_original.shape[0]}")
print(f"Rows after                       : {df_cleaned.shape[0]}")
print(f"Columns                          : {df_cleaned.shape[1]}")

print(
    f"\nTransaction columns              : "
    f"{len(transaction_columns)}"
)

print(
    f"Volume columns                   : "
    f"{len(volume_columns)}"
)

print(
    f"Value columns                    : "
    f"{len(value_columns)}"
)

print(
    f"\nStructural rows                  : "
    f"{len(structural_indices)}"
)

print(
    f"Transaction rows before          : "
    f"{len(transaction_indices)}"
)

print(
    f"Transaction rows after           : "
    f"{len(remaining_transaction_indices)}"
)

print(
    f"\nExact duplicate rows detected    : "
    f"{duplicate_count}"
)

print(
    f"Exact duplicate rows removed     : "
    f"{duplicate_count}"
)

print(
    f"\nMissing transaction cells before : "
    f"{missing_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_after}"
)

print(
    f"Zero transaction cells before    : "
    f"{zero_before}"
)

print(
    f"Zero transaction cells after     : "
    f"{zero_after}"
)

print(
    f"\nNon-numeric transaction cells    : "
    f"{non_numeric_transaction_cells}"
)

print(
    f"Negative volume cells             : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells              : "
    f"{negative_value_cells}"
)

print(
    f"Positive infinity cells           : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells           : "
    f"{negative_infinity_cells}"
)

print(
    "\nTransaction values modified       : False"
)

print(
    "Missing values imputed             : False"
)

print(
    "NaN converted to zero              : False"
)

print(
    "Structural rows modified           : False"
)

print(
    "Saved-file mismatches              : 0"
)


# ============================================================================
# FINAL ASSERTIONS
# ============================================================================

assert df_cleaned.shape[1] == EXPECTED_COLUMNS
assert len(transaction_columns) == EXPECTED_TRANSACTION_COLUMNS
assert len(volume_columns) == EXPECTED_VOLUME_COLUMNS
assert len(value_columns) == EXPECTED_VALUE_COLUMNS

assert non_numeric_transaction_cells == 0

assert negative_volume_cells == 0
assert negative_value_cells == 0

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

assert remaining_duplicates == 0

assert df_saved.shape == df_cleaned.shape

assert list(df_saved.columns) == list(
    df_cleaned.columns
)

assert saved_missing == missing_after
assert saved_zero == zero_after

assert saved_non_numeric_cells == 0


# ============================================================================
# COMPLETE
# ============================================================================

print("\n" + "=" * 90)
print("STEP 5 COMPLETE")
print("=" * 90)

print("✓ Input dimensions validated")
print("✓ Transaction columns identified")
print("✓ Structural rows identified")
print("✓ Embedded header rows preserved")
print("✓ Duplicate records analyzed")
print("✓ Exact duplicate transaction rows handled")
print("✓ Structural rows preserved")
print("✓ Retained transaction values unchanged")
print("✓ Missing values not imputed")
print("✓ No NaN converted to zero")
print("✓ Existing zero values preserved")
print("✓ No negative transaction values")
print("✓ No infinity values")
print("✓ No duplicate transaction records remain")
print("✓ Saved-file integrity validated")
print("✓ All assertions passed")
print("✓ Checkpoint saved")

print(f"\nOutput file: {OUTPUT_FILE}")

print("=" * 90)

==========================================================================================
STEP 5: DUPLICATE RECORD ANALYSIS & CONTROLLED CLEANING
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI_Step4_MissingValue_Handled.xlsx
Rows       : 40
Columns    : 42
✓ Input dimensions validated

CORE COLUMN VALIDATION
------------------------------------------------------------------------------------------
✓ Sr_No present
✓ NPCI_Operated_System present

TRANSACTION COLUMN IDENTIFICATION
------------------------------------------------------------------------------------------
Transaction columns : 40
Volume columns      : 20
Value columns       : 20
✓ Transaction column structure validated

STRUCTURAL ROW IDENTIFICATION
------------------------------------------------------------------------------------------
Embedded header rows : 2
Embedded headers    : [0, 29]
Empty-system rows    : 2
Empty-system indices : [29, 39]
Structural rows      : 3
Structural indices   : [0, 29, 39]
Transaction rows     : 37
✓ Structural rows identified correctly

ORIGINAL TRANSACTION STATE
------------------------------------------------------------------------------------------
Missing transaction cells : 218
Zero transaction cells    : 142

DUPLICATE RECORD ANALYSIS
------------------------------------------------------------------------------------------
Exact duplicate transaction rows : 0
✓ No exact duplicate transaction rows detected.
✓ Independent duplicate-key validation passed

CONTROLLED DUPLICATE HANDLING
------------------------------------------------------------------------------------------
✓ No rows removed.
✓ Input data preserved exactly.
✓ Structural rows preserved
✓ All retained transaction values unchanged

MISSING / ZERO VALIDATION
------------------------------------------------------------------------------------------
Missing transaction cells before : 218
Missing transaction cells after  : 218
Zero transaction cells before    : 142
Zero transaction cells after     : 142
✓ Missing-value accounting validated
✓ Zero-value accounting validated

TRANSACTION DATA TYPE VALIDATION
------------------------------------------------------------------------------------------
Numeric transaction data cells    : 1262
Non-numeric transaction cells     : 0
✓ All genuine transaction cells are numeric or missing

NEGATIVE VALUE CHECK
------------------------------------------------------------------------------------------
Negative volume cells : 0
Negative value cells  : 0
✓ No negative transaction values detected

INFINITY CHECK
------------------------------------------------------------------------------------------
Positive infinity cells : 0
Negative infinity cells : 0
✓ No infinity values detected

DUPLICATE VALIDATION AFTER CLEANING
------------------------------------------------------------------------------------------
✓ No exact duplicate transaction records remain

STRUCTURAL VALIDATION
------------------------------------------------------------------------------------------
✓ Column structure preserved
✓ Row count validated: 40

SAVING STEP 5 CHECKPOINT
------------------------------------------------------------------------------------------
✓ Checkpoint saved: NPCI_Step5_Duplicate_Handled.xlsx

SAVED-FILE INTEGRITY VALIDATION
------------------------------------------------------------------------------------------
✓ Saved dimensions validated
✓ Saved column structure validated
✓ Saved-file transaction values validated

==========================================================================================
STEP 5 VALIDATION
==========================================================================================
Duplicate transaction rows detected : 0
Duplicate transaction rows removed  : 0
Rows before                        : 40
Rows after                         : 40
Columns before                     : 42
Columns after                      : 42
Missing transaction cells before   : 218
Missing transaction cells after    : 218
Zero transaction cells before      : 142
Zero transaction cells after       : 142
Non-numeric transaction cells      : 0
Remaining duplicate rows           : 0
Negative volume cells              : 0
Negative value cells               : 0
Positive infinity cells            : 0
Negative infinity cells            : 0
✓ Structural rows preserved
✓ Retained transaction values unchanged
✓ Missing-value accounting validated
✓ Existing zero-value accounting validated
✓ No negative transaction values
✓ No infinity values
✓ No exact duplicate transaction records remain
✓ Saved-file integrity validated

==========================================================================================
STEP 5 FINAL REPORT
==========================================================================================
Input file                       : NPCI_Step4_MissingValue_Handled.xlsx
Output file                      : NPCI_Step5_Duplicate_Handled.xlsx

Rows before                      : 40
Rows after                       : 40
Columns                          : 42

Transaction columns              : 40
Volume columns                   : 20
Value columns                    : 20

Structural rows                  : 3
Transaction rows before          : 37
Transaction rows after           : 37

Exact duplicate rows detected    : 0
Exact duplicate rows removed     : 0

Missing transaction cells before : 218
Missing transaction cells after  : 218
Zero transaction cells before    : 142
Zero transaction cells after     : 142

Non-numeric transaction cells    : 0
Negative volume cells             : 0
Negative value cells              : 0
Positive infinity cells           : 0
Negative infinity cells           : 0

Transaction values modified       : False
Missing values imputed             : False
NaN converted to zero              : False
Structural rows modified           : False
Saved-file mismatches              : 0

==========================================================================================
STEP 5 COMPLETE
==========================================================================================
✓ Input dimensions validated
✓ Transaction columns identified
✓ Structural rows identified
✓ Embedded header rows preserved
✓ Duplicate records analyzed
✓ Exact duplicate transaction rows handled
✓ Structural rows preserved
✓ Retained transaction values unchanged
✓ Missing values not imputed
✓ No NaN converted to zero
✓ Existing zero values preserved
✓ No negative transaction values
✓ No infinity values
✓ No duplicate transaction records remain
✓ Saved-file integrity validated
✓ All assertions passed
✓ Checkpoint saved

Output file: NPCI_Step5_Duplicate_Handled.xlsx
==========================================================================================

In [15]:
# =============================================================================
# STEP 6: DATA CONSISTENCY & INTEGRITY CLEANING
# =============================================================================

import pandas as pd
import numpy as np
import os

# =============================================================================
# CONFIGURATION
# =============================================================================

INPUT_FILE = "NPCI_Step5_Duplicate_Handled.xlsx"
OUTPUT_FILE = "NPCI_Step6_Consistency_Cleaned.xlsx"

EXPECTED_ROWS = 40
EXPECTED_COLUMNS = 42

SYSTEM_COL = "NPCI_Operated_System"
SR_NO_COL = "Sr_No"

# =============================================================================
# STEP 6 HEADER
# =============================================================================

print("=" * 90)
print("STEP 6: DATA CONSISTENCY & INTEGRITY CLEANING")
print("=" * 90)

# =============================================================================
# LOAD INPUT FILE
# =============================================================================

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}"
    )

df = pd.read_excel(INPUT_FILE)

# Keep an untouched copy for validation
df_original = df.copy(deep=True)

# =============================================================================
# INPUT FILE VALIDATION
# =============================================================================

print("\nINPUT FILE")
print("-" * 90)

print(f"Input file : {INPUT_FILE}")
print(f"Rows       : {df.shape[0]}")
print(f"Columns    : {df.shape[1]}")

assert df.shape[0] == EXPECTED_ROWS
assert df.shape[1] == EXPECTED_COLUMNS

print("✓ Input dimensions validated")

# =============================================================================
# CORE COLUMN VALIDATION
# =============================================================================

print("\nCORE COLUMN VALIDATION")
print("-" * 90)

assert SR_NO_COL in df.columns
print("✓ Sr_No present")

assert SYSTEM_COL in df.columns
print("✓ NPCI_Operated_System present")

# =============================================================================
# TRANSACTION COLUMN IDENTIFICATION
# =============================================================================

transaction_columns = [
    col for col in df.columns
    if col.endswith("_Volume_in_Mn")
    or col.endswith("_Value_in_Bn")
]

volume_columns = [
    col for col in transaction_columns
    if col.endswith("_Volume_in_Mn")
]

value_columns = [
    col for col in transaction_columns
    if col.endswith("_Value_in_Bn")
]

print("\nTRANSACTION COLUMN IDENTIFICATION")
print("-" * 90)

print(f"Transaction columns : {len(transaction_columns)}")
print(f"Volume columns      : {len(volume_columns)}")
print(f"Value columns       : {len(value_columns)}")

assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

print("✓ Transaction column structure validated")

# =============================================================================
# STRUCTURAL ROW IDENTIFICATION
# =============================================================================

embedded_header_rows = []

for idx in df.index:

    row_values = df.loc[idx, transaction_columns]

    header_count = row_values.astype(str).isin(
        ["Volume (in Mn)", "Value (in Bn)"]
    ).sum()

    if header_count >= 2:
        embedded_header_rows.append(idx)


empty_system_rows = []

for idx in df.index:

    system_value = df.loc[idx, SYSTEM_COL]

    if pd.isna(system_value):
        empty_system_rows.append(idx)

    elif str(system_value).strip() == "":
        empty_system_rows.append(idx)


structural_rows = sorted(
    set(embedded_header_rows + empty_system_rows)
)

transaction_rows = [
    idx for idx in df.index
    if idx not in structural_rows
]

print("\nSTRUCTURAL ROW IDENTIFICATION")
print("-" * 90)

print(f"Embedded header rows : {len(embedded_header_rows)}")
print(f"Embedded headers     : {embedded_header_rows}")

print(f"Empty-system rows    : {len(empty_system_rows)}")
print(f"Empty-system indices : {empty_system_rows}")

print(f"Structural rows      : {len(structural_rows)}")
print(f"Structural indices   : {structural_rows}")

print(f"Transaction rows     : {len(transaction_rows)}")

assert embedded_header_rows == [0, 29]
assert empty_system_rows == [29, 39]
assert structural_rows == [0, 29, 39]
assert len(transaction_rows) == 37

print("✓ Structural rows identified correctly")

# =============================================================================
# ORIGINAL STATE
# =============================================================================

original_transaction = df.loc[
    transaction_rows,
    transaction_columns
].copy(deep=True)

original_system = df[SYSTEM_COL].copy(deep=True)

original_sr_no = df[SR_NO_COL].copy(deep=True)

missing_before = int(
    original_transaction.isna().sum().sum()
)

zero_before = int(
    (original_transaction == 0).sum().sum()
)

print("\nORIGINAL DATA STATE")
print("-" * 90)

print(f"Missing transaction cells : {missing_before}")
print(f"Zero transaction cells    : {zero_before}")

# =============================================================================
# TEXT CONSISTENCY CHECK
# =============================================================================

print("\nTEXT CONSISTENCY CHECK")
print("-" * 90)

system_whitespace_before = 0

for idx in transaction_rows:

    value = df.loc[idx, SYSTEM_COL]

    if pd.notna(value):

        text_value = str(value)

        if text_value != text_value.strip():
            system_whitespace_before += 1

print(
    f"System names with leading/trailing spaces : "
    f"{system_whitespace_before}"
)

# =============================================================================
# CONTROLLED TEXT CLEANING
# =============================================================================
#
# Only genuine transaction-row system names are cleaned.
#
# Structural rows are NOT modified.
#
# Cleaning performed:
#   1. Remove leading whitespace
#   2. Remove trailing whitespace
#
# Internal spaces and spelling/capitalization are NOT changed because
# automatically changing them could alter legitimate system names.
# =============================================================================

print("\nCONTROLLED TEXT CONSISTENCY CLEANING")
print("-" * 90)

text_changes = 0

for idx in transaction_rows:

    value = df.loc[idx, SYSTEM_COL]

    if pd.notna(value):

        original_value = str(value)
        cleaned_value = original_value.strip()

        if original_value != cleaned_value:

            df.loc[idx, SYSTEM_COL] = cleaned_value
            text_changes += 1

print(
    f"System-name formatting changes : "
    f"{text_changes}"
)

print("✓ Leading/trailing whitespace cleaned where present")
print("✓ Internal text content preserved")
print("✓ Structural rows preserved")

# =============================================================================
# SR_NO CONSISTENCY CHECK
# =============================================================================

print("\nSr_No CONSISTENCY CHECK")
print("-" * 90)

print(f"Sr_No dtype : {df[SR_NO_COL].dtype}")

# Do NOT force Sr_No to integer.
# Preserve its existing representation.

assert df[SR_NO_COL].dtype == df_original[SR_NO_COL].dtype

print("✓ Sr_No dtype preserved")

# =============================================================================
# TRANSACTION NUMERIC VALIDATION
# =============================================================================

print("\nTRANSACTION NUMERIC VALIDATION")
print("-" * 90)

numeric_transaction_cells = 0
non_numeric_transaction_cells = 0

for col in transaction_columns:

    series = df.loc[transaction_rows, col]

    numeric_series = pd.to_numeric(
        series,
        errors="coerce"
    )

    invalid_mask = (
        series.notna()
        & numeric_series.isna()
    )

    invalid_count = int(
        invalid_mask.sum()
    )

    non_numeric_transaction_cells += invalid_count

    numeric_transaction_cells += int(
        numeric_series.notna().sum()
    )

print(
    f"Numeric transaction cells     : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells : "
    f"{non_numeric_transaction_cells}"
)

assert non_numeric_transaction_cells == 0

print("✓ All genuine transaction cells are numeric or missing")

# =============================================================================
# NUMERIC VALUE FORMAT CONSISTENCY
# =============================================================================
#
# Verify that transaction values remain numerically interpretable.
#
# No rounding is performed.
# No scaling is performed.
# No unit conversion is performed.
# =============================================================================

print("\nNUMERIC VALUE FORMAT VALIDATION")
print("-" * 90)

conversion_failures = 0

for col in transaction_columns:

    original_series = df.loc[
        transaction_rows,
        col
    ]

    converted_series = pd.to_numeric(
        original_series,
        errors="coerce"
    )

    invalid = (
        original_series.notna()
        & converted_series.isna()
    )

    conversion_failures += int(
        invalid.sum()
    )

assert conversion_failures == 0

print("✓ All transaction values have valid numeric format")

# =============================================================================
# NEGATIVE VALUE CHECK
# =============================================================================

print("\nNEGATIVE VALUE CHECK")
print("-" * 90)

negative_volume_cells = 0
negative_value_cells = 0

for col in volume_columns:

    numeric_series = pd.to_numeric(
        df.loc[transaction_rows, col],
        errors="coerce"
    )

    negative_volume_cells += int(
        (numeric_series < 0).sum()
    )


for col in value_columns:

    numeric_series = pd.to_numeric(
        df.loc[transaction_rows, col],
        errors="coerce"
    )

    negative_value_cells += int(
        (numeric_series < 0).sum()
    )

print(f"Negative volume cells : {negative_volume_cells}")
print(f"Negative value cells  : {negative_value_cells}")

assert negative_volume_cells == 0
assert negative_value_cells == 0

print("✓ No negative transaction values detected")

# =============================================================================
# INFINITY CHECK
# =============================================================================

print("\nINFINITY CHECK")
print("-" * 90)

positive_infinity_cells = 0
negative_infinity_cells = 0

for col in transaction_columns:

    numeric_series = pd.to_numeric(
        df.loc[transaction_rows, col],
        errors="coerce"
    )

    positive_infinity_cells += int(
        np.isposinf(numeric_series).sum()
    )

    negative_infinity_cells += int(
        np.isneginf(numeric_series).sum()
    )

print(
    f"Positive infinity cells : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells : "
    f"{negative_infinity_cells}"
)

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

print("✓ No infinity values detected")

# =============================================================================
# MISSING VALUE VALIDATION
# =============================================================================

print("\nMISSING VALUE VALIDATION")
print("-" * 90)

missing_after = int(
    df.loc[
        transaction_rows,
        transaction_columns
    ].isna().sum().sum()
)

zero_after = int(
    (
        df.loc[
            transaction_rows,
            transaction_columns
        ] == 0
    ).sum().sum()
)

print(
    f"Missing transaction cells before : "
    f"{missing_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_after}"
)

print(
    f"Zero transaction cells before    : "
    f"{zero_before}"
)

print(
    f"Zero transaction cells after     : "
    f"{zero_after}"
)

missingness_preserved = (
    missing_before == missing_after
)

zero_count_preserved = (
    zero_before == zero_after
)

assert missingness_preserved
assert zero_count_preserved

print("✓ Missing values preserved")
print("✓ Existing zeros preserved")

# =============================================================================
# TRANSACTION VALUE INTEGRITY
# =============================================================================
#
# IMPORTANT:
# Text formatting may have changed, but transaction values MUST NOT change.
# =============================================================================

transaction_after = df.loc[
    transaction_rows,
    transaction_columns
]

transaction_values_match = (
    original_transaction.equals(
        transaction_after
    )
)

print("\nTRANSACTION VALUE INTEGRITY CHECK")
print("-" * 90)

print(
    f"Transaction values unchanged : "
    f"{transaction_values_match}"
)

assert transaction_values_match

print("✓ All transaction values unchanged")

# =============================================================================
# STRUCTURAL ROW INTEGRITY
# =============================================================================

structural_original = df_original.loc[
    structural_rows
].copy(deep=True)

structural_after = df.loc[
    structural_rows
].copy(deep=True)

structural_rows_unchanged = (
    structural_original.equals(
        structural_after
    )
)

print("\nSTRUCTURAL ROW INTEGRITY CHECK")
print("-" * 90)

assert structural_rows_unchanged

print("✓ Structural rows completely unchanged")

# =============================================================================
# COLUMN STRUCTURE VALIDATION
# =============================================================================

print("\nCOLUMN STRUCTURE VALIDATION")
print("-" * 90)

assert list(df.columns) == list(
    df_original.columns
)

assert df.shape == df_original.shape

print("✓ Column order preserved")
print("✓ Column names preserved")
print("✓ Row count preserved")
print("✓ Column count preserved")

# =============================================================================
# SYSTEM NAME VALIDATION
# =============================================================================

print("\nSYSTEM NAME VALIDATION")
print("-" * 90)

empty_system_after = 0

for idx in transaction_rows:

    value = df.loc[idx, SYSTEM_COL]

    if pd.isna(value):
        empty_system_after += 1

    elif str(value).strip() == "":
        empty_system_after += 1

print(
    f"Empty system names in transaction rows : "
    f"{empty_system_after}"
)

# We do NOT impute missing system names.
# Existing missing values remain missing.

assert empty_system_after == 0

print("✓ All genuine transaction rows have system names")

# =============================================================================
# STRUCTURAL SYSTEM NAME VALIDATION
# =============================================================================

structural_system_before = (
    df_original.loc[
        structural_rows,
        SYSTEM_COL
    ]
)

structural_system_after = (
    df.loc[
        structural_rows,
        SYSTEM_COL
    ]
)

assert structural_system_before.equals(
    structural_system_after
)

print("✓ Structural system-name values preserved")

# =============================================================================
# DATA MODIFICATION SUMMARY
# =============================================================================

print("\nDATA MODIFICATION SUMMARY")
print("-" * 90)

# Transaction data must not change.
transaction_modified = not transaction_values_match

# Structural data must not change.
structural_modified = not structural_rows_unchanged

# Dataset dimensions must not change.
dimensions_modified = (
    df.shape != df_original.shape
)

print(
    f"Transaction data modified : "
    f"{transaction_modified}"
)

print(
    f"Structural rows modified  : "
    f"{structural_modified}"
)

print(
    f"Dimensions modified       : "
    f"{dimensions_modified}"
)

assert transaction_modified is False
assert structural_modified is False
assert dimensions_modified is False

# =============================================================================
# SAVE STEP 6 CHECKPOINT
# =============================================================================

print("\nSAVING STEP 6 CHECKPOINT")
print("-" * 90)

df.to_excel(
    OUTPUT_FILE,
    index=False
)

print(
    f"✓ Checkpoint saved: "
    f"{OUTPUT_FILE}"
)

# =============================================================================
# SAVED FILE VALIDATION
# =============================================================================

print("\nSAVED-FILE INTEGRITY VALIDATION")
print("-" * 90)

saved_df = pd.read_excel(
    OUTPUT_FILE
)

# Dimensions
assert saved_df.shape == df.shape

print("✓ Saved dimensions validated")

# Columns
assert list(saved_df.columns) == list(
    df.columns
)

print("✓ Saved column structure validated")

# Transaction data
saved_transaction = saved_df.loc[
    transaction_rows,
    transaction_columns
]

saved_transaction_match = (
    transaction_after.equals(
        saved_transaction
    )
)

assert saved_transaction_match

print("✓ Saved-file transaction values validated")

# Missing values
saved_missing = int(
    saved_transaction.isna().sum().sum()
)

assert saved_missing == missing_after

print("✓ Saved-file missing values validated")

# Zero values
saved_zero = int(
    (saved_transaction == 0).sum().sum()
)

assert saved_zero == zero_after

print("✓ Saved-file zero values validated")

# Structural rows
saved_structural = saved_df.loc[
    structural_rows
]

assert saved_structural.equals(
    df.loc[structural_rows]
)

print("✓ Saved structural rows validated")

# =============================================================================
# FINAL ASSERTIONS
# =============================================================================

assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

assert len(structural_rows) == 3
assert len(transaction_rows) == 37

assert non_numeric_transaction_cells == 0

assert negative_volume_cells == 0
assert negative_value_cells == 0

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

assert missingness_preserved
assert zero_count_preserved

assert transaction_values_match
assert structural_rows_unchanged

assert df.shape == df_original.shape
assert list(df.columns) == list(
    df_original.columns
)

assert transaction_modified is False
assert structural_modified is False
assert dimensions_modified is False

assert saved_transaction_match
assert saved_missing == missing_after
assert saved_zero == zero_after

# =============================================================================
# STEP 6 FINAL REPORT
# =============================================================================

print("\n" + "=" * 90)
print("STEP 6 VALIDATION")
print("=" * 90)

print(
    f"Rows before                       : "
    f"{df_original.shape[0]}"
)

print(
    f"Rows after                        : "
    f"{df.shape[0]}"
)

print(
    f"Columns before                    : "
    f"{df_original.shape[1]}"
)

print(
    f"Columns after                     : "
    f"{df.shape[1]}"
)

print(
    f"Transaction columns              : "
    f"{len(transaction_columns)}"
)

print(
    f"Volume columns                   : "
    f"{len(volume_columns)}"
)

print(
    f"Value columns                    : "
    f"{len(value_columns)}"
)

print(
    f"Structural rows                  : "
    f"{len(structural_rows)}"
)

print(
    f"Transaction data rows            : "
    f"{len(transaction_rows)}"
)

print(
    f"System-name formatting changes   : "
    f"{text_changes}"
)

print(
    f"Missing transaction cells before : "
    f"{missing_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_after}"
)

print(
    f"Zero transaction cells before    : "
    f"{zero_before}"
)

print(
    f"Zero transaction cells after     : "
    f"{zero_after}"
)

print(
    f"Numeric transaction cells        : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells    : "
    f"{non_numeric_transaction_cells}"
)

print(
    f"Negative volume cells             : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells              : "
    f"{negative_value_cells}"
)

print(
    f"Positive infinity cells           : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells           : "
    f"{negative_infinity_cells}"
)

print(
    f"Transaction values modified       : "
    f"{transaction_modified}"
)

print(
    f"Structural rows modified          : "
    f"{structural_modified}"
)

print(
    f"Missing values imputed             : "
    f"False"
)

print(
    f"NaN converted to zero              : "
    f"False"
)

print(
    f"Saved-file mismatches              : "
    f"{not saved_transaction_match}"
)

# =============================================================================
# FINAL COMPLETION MESSAGE
# =============================================================================

print("\n" + "=" * 90)
print("STEP 6 COMPLETE")
print("=" * 90)

print("✓ Input dimensions validated")
print("✓ Transaction columns identified")
print("✓ Structural rows identified")
print("✓ Embedded header rows preserved")
print("✓ Text consistency checked")
print("✓ Safe text formatting cleaned")
print("✓ Sr_No structure preserved")
print("✓ Transaction numeric format validated")
print("✓ Missing values preserved")
print("✓ Existing zeros preserved")
print("✓ No missing-value imputation performed")
print("✓ No NaN converted to zero")
print("✓ No transaction values modified")
print("✓ No negative transaction values")
print("✓ No infinity values")
print("✓ Structural rows preserved")
print("✓ Column structure preserved")
print("✓ Saved-file integrity validated")
print("✓ All assertions passed")
print("✓ Checkpoint saved")

print(
    f"\nOutput file: {OUTPUT_FILE}"
)

print("=" * 90)

==========================================================================================
STEP 6: DATA CONSISTENCY & INTEGRITY CLEANING
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI_Step5_Duplicate_Handled.xlsx
Rows       : 40
Columns    : 42
✓ Input dimensions validated

CORE COLUMN VALIDATION
------------------------------------------------------------------------------------------
✓ Sr_No present
✓ NPCI_Operated_System present

TRANSACTION COLUMN IDENTIFICATION
------------------------------------------------------------------------------------------
Transaction columns : 40
Volume columns      : 20
Value columns       : 20
✓ Transaction column structure validated

STRUCTURAL ROW IDENTIFICATION
------------------------------------------------------------------------------------------
Embedded header rows : 2
Embedded headers     : [0, 29]
Empty-system rows    : 2
Empty-system indices : [29, 39]
Structural rows      : 3
Structural indices   : [0, 29, 39]
Transaction rows     : 37
✓ Structural rows identified correctly

ORIGINAL DATA STATE
------------------------------------------------------------------------------------------
Missing transaction cells : 218
Zero transaction cells    : 142

TEXT CONSISTENCY CHECK
------------------------------------------------------------------------------------------
System names with leading/trailing spaces : 17

CONTROLLED TEXT CONSISTENCY CLEANING
------------------------------------------------------------------------------------------
System-name formatting changes : 17
✓ Leading/trailing whitespace cleaned where present
✓ Internal text content preserved
✓ Structural rows preserved

Sr_No CONSISTENCY CHECK
------------------------------------------------------------------------------------------
Sr_No dtype : float64
✓ Sr_No dtype preserved

TRANSACTION NUMERIC VALIDATION
------------------------------------------------------------------------------------------
Numeric transaction cells     : 1262
Non-numeric transaction cells : 0
✓ All genuine transaction cells are numeric or missing

NUMERIC VALUE FORMAT VALIDATION
------------------------------------------------------------------------------------------
✓ All transaction values have valid numeric format

NEGATIVE VALUE CHECK
------------------------------------------------------------------------------------------
Negative volume cells : 0
Negative value cells  : 0
✓ No negative transaction values detected

INFINITY CHECK
------------------------------------------------------------------------------------------
Positive infinity cells : 0
Negative infinity cells : 0
✓ No infinity values detected

MISSING VALUE VALIDATION
------------------------------------------------------------------------------------------
Missing transaction cells before : 218
Missing transaction cells after  : 218
Zero transaction cells before    : 142
Zero transaction cells after     : 142
✓ Missing values preserved
✓ Existing zeros preserved

TRANSACTION VALUE INTEGRITY CHECK
------------------------------------------------------------------------------------------
Transaction values unchanged : True
✓ All transaction values unchanged

STRUCTURAL ROW INTEGRITY CHECK
------------------------------------------------------------------------------------------
✓ Structural rows completely unchanged

COLUMN STRUCTURE VALIDATION
------------------------------------------------------------------------------------------
✓ Column order preserved
✓ Column names preserved
✓ Row count preserved
✓ Column count preserved

SYSTEM NAME VALIDATION
------------------------------------------------------------------------------------------
Empty system names in transaction rows : 0
✓ All genuine transaction rows have system names
✓ Structural system-name values preserved

DATA MODIFICATION SUMMARY
------------------------------------------------------------------------------------------
Transaction data modified : False
Structural rows modified  : False
Dimensions modified       : False

SAVING STEP 6 CHECKPOINT
------------------------------------------------------------------------------------------
✓ Checkpoint saved: NPCI_Step6_Consistency_Cleaned.xlsx

SAVED-FILE INTEGRITY VALIDATION
------------------------------------------------------------------------------------------
✓ Saved dimensions validated
✓ Saved column structure validated
✓ Saved-file transaction values validated
✓ Saved-file missing values validated
✓ Saved-file zero values validated
✓ Saved structural rows validated

==========================================================================================
STEP 6 VALIDATION
==========================================================================================
Rows before                       : 40
Rows after                        : 40
Columns before                    : 42
Columns after                     : 42
Transaction columns              : 40
Volume columns                   : 20
Value columns                    : 20
Structural rows                  : 3
Transaction data rows            : 37
System-name formatting changes   : 17
Missing transaction cells before : 218
Missing transaction cells after  : 218
Zero transaction cells before    : 142
Zero transaction cells after     : 142
Numeric transaction cells        : 1262
Non-numeric transaction cells    : 0
Negative volume cells             : 0
Negative value cells              : 0
Positive infinity cells           : 0
Negative infinity cells           : 0
Transaction values modified       : False
Structural rows modified          : False
Missing values imputed             : False
NaN converted to zero              : False
Saved-file mismatches              : False

==========================================================================================
STEP 6 COMPLETE
==========================================================================================
✓ Input dimensions validated
✓ Transaction columns identified
✓ Structural rows identified
✓ Embedded header rows preserved
✓ Text consistency checked
✓ Safe text formatting cleaned
✓ Sr_No structure preserved
✓ Transaction numeric format validated
✓ Missing values preserved
✓ Existing zeros preserved
✓ No missing-value imputation performed
✓ No NaN converted to zero
✓ No transaction values modified
✓ No negative transaction values
✓ No infinity values
✓ Structural rows preserved
✓ Column structure preserved
✓ Saved-file integrity validated
✓ All assertions passed
✓ Checkpoint saved

Output file: NPCI_Step6_Consistency_Cleaned.xlsx
==========================================================================================

In [16]:
# =============================================================================
# STEP 7: FINAL DATA CLEANING VALIDATION & CLEAN DATASET EXPORT
# =============================================================================

import os
import pandas as pd
import numpy as np

print("=" * 90)
print("STEP 7: FINAL DATA CLEANING VALIDATION & CLEAN DATASET EXPORT")
print("=" * 90)


# =============================================================================
# 1. FILE PATHS
# =============================================================================

INPUT_FILE = "NPCI_Step6_Consistency_Cleaned.xlsx"
OUTPUT_FILE = "NPCI_Final_Cleaned.xlsx"


# =============================================================================
# 2. LOAD INPUT FILE
# =============================================================================

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}"
    )

df = pd.read_excel(INPUT_FILE)

print("\nINPUT FILE")
print("-" * 90)
print(f"Input file : {INPUT_FILE}")
print(f"Rows       : {df.shape[0]}")
print(f"Columns    : {df.shape[1]}")


# =============================================================================
# 3. INPUT DIMENSION VALIDATION
# =============================================================================

EXPECTED_ROWS = 40
EXPECTED_COLUMNS = 42

assert df.shape[0] == EXPECTED_ROWS, (
    f"Expected {EXPECTED_ROWS} rows, found {df.shape[0]}"
)

assert df.shape[1] == EXPECTED_COLUMNS, (
    f"Expected {EXPECTED_COLUMNS} columns, found {df.shape[1]}"
)

print("✓ Input dimensions validated")


# =============================================================================
# 4. CORE COLUMN VALIDATION
# =============================================================================

print("\nCORE COLUMN VALIDATION")
print("-" * 90)

assert "Sr_No" in df.columns
assert "NPCI_Operated_System" in df.columns

print("✓ Sr_No present")
print("✓ NPCI_Operated_System present")


# =============================================================================
# 5. TRANSACTION COLUMN IDENTIFICATION
# =============================================================================

transaction_columns = [
    col for col in df.columns
    if "Volume_in_Mn" in str(col)
    or "Value_in_Bn" in str(col)
]

volume_columns = [
    col for col in transaction_columns
    if "Volume_in_Mn" in str(col)
]

value_columns = [
    col for col in transaction_columns
    if "Value_in_Bn" in str(col)
]

print("\nTRANSACTION COLUMN IDENTIFICATION")
print("-" * 90)
print(f"Transaction columns : {len(transaction_columns)}")
print(f"Volume columns      : {len(volume_columns)}")
print(f"Value columns       : {len(value_columns)}")

assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

print("✓ Transaction column structure validated")


# =============================================================================
# 6. STRUCTURAL ROW IDENTIFICATION
# =============================================================================

system_col = "NPCI_Operated_System"

system_values = df[system_col]

empty_system_mask = (
    system_values.isna()
    | system_values.astype(str).str.strip().eq("")
)

empty_system_indices = df.index[empty_system_mask].tolist()


# -------------------------------------------------------------------------
# Detect embedded header rows
# -------------------------------------------------------------------------

embedded_header_mask = pd.Series(False, index=df.index)

for idx in df.index:

    matches = 0

    for col in transaction_columns:

        value = df.loc[idx, col]

        if isinstance(value, str):

            value_clean = value.strip().lower()

            if (
                value_clean == "volume (in mn)"
                or value_clean == "value (in bn)"
            ):
                matches += 1

    if matches >= 10:
        embedded_header_mask.loc[idx] = True


embedded_header_indices = df.index[
    embedded_header_mask
].tolist()


# -------------------------------------------------------------------------
# Structural rows
# -------------------------------------------------------------------------

structural_mask = (
    empty_system_mask
    | embedded_header_mask
)

structural_indices = df.index[
    structural_mask
].tolist()

transaction_mask = ~structural_mask

transaction_indices = df.index[
    transaction_mask
].tolist()


print("\nSTRUCTURAL ROW IDENTIFICATION")
print("-" * 90)
print(f"Embedded header rows : {len(embedded_header_indices)}")
print(f"Embedded headers     : {embedded_header_indices}")
print(f"Empty-system rows    : {len(empty_system_indices)}")
print(f"Empty-system indices : {empty_system_indices}")
print(f"Structural rows      : {len(structural_indices)}")
print(f"Structural indices   : {structural_indices}")
print(f"Transaction rows     : {len(transaction_indices)}")

assert len(embedded_header_indices) == 2
assert len(empty_system_indices) == 2
assert len(structural_indices) == 3
assert len(transaction_indices) == 37

print("✓ Structural rows identified correctly")


# =============================================================================
# 7. ORIGINAL FINAL CLEANED DATA STATE
# =============================================================================

transaction_before = df.loc[
    transaction_indices,
    transaction_columns
].copy()

missing_before = int(transaction_before.isna().sum().sum())

zero_before = int(
    (transaction_before == 0).sum().sum()
)

print("\nFINAL CLEANED DATA STATE")
print("-" * 90)
print(f"Missing transaction cells : {missing_before}")
print(f"Zero transaction cells    : {zero_before}")


# =============================================================================
# 8. TRANSACTION DATA TYPE VALIDATION
# =============================================================================

numeric_transaction_cells = 0
non_numeric_transaction_cells = 0

non_numeric_details = []

for col in transaction_columns:

    series = df.loc[
        transaction_indices,
        col
    ]

    numeric_mask = pd.to_numeric(
        series,
        errors="coerce"
    ).notna()

    missing_mask = series.isna()

    valid_mask = numeric_mask | missing_mask

    invalid_mask = ~valid_mask

    invalid_count = int(invalid_mask.sum())

    if invalid_count > 0:

        non_numeric_transaction_cells += invalid_count

        for idx in series.index[invalid_mask]:

            non_numeric_details.append(
                (
                    idx,
                    col,
                    series.loc[idx]
                )
            )

    numeric_transaction_cells += int(
        numeric_mask.sum()
    )


print("\nTRANSACTION DATA TYPE VALIDATION")
print("-" * 90)
print(
    f"Numeric transaction data cells    : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells     : "
    f"{non_numeric_transaction_cells}"
)

assert non_numeric_transaction_cells == 0

print("✓ All genuine transaction cells are numeric or missing")


# =============================================================================
# 9. NEGATIVE VALUE CHECK
# =============================================================================

negative_volume_cells = 0
negative_value_cells = 0

for col in volume_columns:

    series = pd.to_numeric(
        df.loc[transaction_indices, col],
        errors="coerce"
    )

    negative_volume_cells += int(
        (series < 0).sum()
    )


for col in value_columns:

    series = pd.to_numeric(
        df.loc[transaction_indices, col],
        errors="coerce"
    )

    negative_value_cells += int(
        (series < 0).sum()
    )


print("\nNEGATIVE VALUE CHECK")
print("-" * 90)
print(f"Negative volume cells : {negative_volume_cells}")
print(f"Negative value cells  : {negative_value_cells}")

assert negative_volume_cells == 0
assert negative_value_cells == 0

print("✓ No negative transaction values detected")


# =============================================================================
# 10. INFINITY CHECK
# =============================================================================

positive_infinity_cells = 0
negative_infinity_cells = 0

for col in transaction_columns:

    numeric_series = pd.to_numeric(
        df.loc[transaction_indices, col],
        errors="coerce"
    )

    positive_infinity_cells += int(
        np.isposinf(numeric_series).sum()
    )

    negative_infinity_cells += int(
        np.isneginf(numeric_series).sum()
    )


print("\nINFINITY CHECK")
print("-" * 90)
print(
    f"Positive infinity cells : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells : "
    f"{negative_infinity_cells}"
)

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

print("✓ No infinity values detected")


# =============================================================================
# 11. SYSTEM NAME VALIDATION
# =============================================================================

transaction_system_names = df.loc[
    transaction_indices,
    system_col
]

empty_transaction_system_names = (
    transaction_system_names.isna()
    | transaction_system_names.astype(str).str.strip().eq("")
)

empty_transaction_system_count = int(
    empty_transaction_system_names.sum()
)


print("\nSYSTEM NAME VALIDATION")
print("-" * 90)
print(
    "Empty system names in transaction rows : "
    f"{empty_transaction_system_count}"
)

assert empty_transaction_system_count == 0

print("✓ All genuine transaction rows have system names")


# =============================================================================
# 12. DUPLICATE VALIDATION
# =============================================================================

transaction_duplicate_count = int(
    df.loc[
        transaction_indices,
        [system_col] + transaction_columns
    ].duplicated().sum()
)


print("\nDUPLICATE VALIDATION")
print("-" * 90)
print(
    f"Exact duplicate transaction rows : "
    f"{transaction_duplicate_count}"
)

assert transaction_duplicate_count == 0

print("✓ No exact duplicate transaction records remain")


# =============================================================================
# 13. MISSING VALUE VALIDATION
# =============================================================================

transaction_after_validation = df.loc[
    transaction_indices,
    transaction_columns
].copy()

missing_after = int(
    transaction_after_validation.isna().sum().sum()
)

zero_after = int(
    (transaction_after_validation == 0).sum().sum()
)


missingness_preserved = (
    missing_before == missing_after
)

zero_count_preserved = (
    zero_before == zero_after
)


print("\nMISSING / ZERO VALIDATION")
print("-" * 90)
print(
    f"Missing transaction cells before : "
    f"{missing_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_after}"
)

print(
    f"Zero transaction cells before    : "
    f"{zero_before}"
)

print(
    f"Zero transaction cells after     : "
    f"{zero_after}"
)

assert missingness_preserved
assert zero_count_preserved

print("✓ Missing values preserved")
print("✓ Existing zeros preserved")


# =============================================================================
# 14. TRANSACTION VALUE INTEGRITY CHECK
# =============================================================================

transaction_values_match = (
    transaction_before.equals(
        transaction_after_validation
    )
)


print("\nTRANSACTION VALUE INTEGRITY CHECK")
print("-" * 90)

print(
    f"Transaction values unchanged : "
    f"{transaction_values_match}"
)

assert transaction_values_match

print("✓ All transaction values unchanged")


# =============================================================================
# 15. STRUCTURAL ROW INTEGRITY CHECK
# =============================================================================

# Reload original Step 6 file separately to compare structural rows.
original_df = pd.read_excel(INPUT_FILE)

structural_rows_unchanged = True

for idx in structural_indices:

    original_row = original_df.loc[idx]
    current_row = df.loc[idx]

    if not original_row.equals(current_row):
        structural_rows_unchanged = False
        break


print("\nSTRUCTURAL ROW INTEGRITY CHECK")
print("-" * 90)

print(
    f"Structural rows unchanged : "
    f"{structural_rows_unchanged}"
)

assert structural_rows_unchanged

print("✓ Structural rows completely unchanged")


# =============================================================================
# 16. COLUMN STRUCTURE VALIDATION
# =============================================================================

columns_preserved = (
    list(original_df.columns)
    == list(df.columns)
)

rows_preserved = (
    original_df.shape[0]
    == df.shape[0]
)

column_count_preserved = (
    original_df.shape[1]
    == df.shape[1]
)


print("\nCOLUMN / DIMENSION VALIDATION")
print("-" * 90)

print(
    f"Column order preserved : "
    f"{columns_preserved}"
)

print(
    f"Row count preserved    : "
    f"{rows_preserved}"
)

print(
    f"Column count preserved : "
    f"{column_count_preserved}"
)

assert columns_preserved
assert rows_preserved
assert column_count_preserved

print("✓ Column structure preserved")
print("✓ Row count preserved")
print("✓ Column count preserved")


# =============================================================================
# 17. FINAL DATA CLEANING RULE CHECK
# =============================================================================

print("\nFINAL DATA CLEANING RULE CHECK")
print("-" * 90)

# No imputation
imputation_performed = False

# No conversion of missing values to zero
nan_converted_to_zero = False

# No transaction value modifications
data_values_modified = not transaction_values_match

# No structural row modifications
structural_rows_modified = not structural_rows_unchanged


assert imputation_performed is False
assert nan_converted_to_zero is False
assert data_values_modified is False
assert structural_rows_modified is False

print("✓ No missing-value imputation performed")
print("✓ No NaN converted to zero")
print("✓ No transaction values modified")
print("✓ No structural rows modified")


# =============================================================================
# 18. SAVE FINAL CLEANED DATASET
# =============================================================================

print("\nSAVING FINAL CLEAN DATASET")
print("-" * 90)

df.to_excel(
    OUTPUT_FILE,
    index=False
)

assert os.path.exists(OUTPUT_FILE)

print(
    f"✓ Final cleaned dataset saved: "
    f"{OUTPUT_FILE}"
)


# =============================================================================
# 19. RELOAD SAVED FILE
# =============================================================================

saved_df = pd.read_excel(
    OUTPUT_FILE
)


# =============================================================================
# 20. SAVED-FILE DIMENSION VALIDATION
# =============================================================================

assert saved_df.shape == df.shape

assert list(saved_df.columns) == list(
    df.columns
)

print("\nSAVED-FILE INTEGRITY VALIDATION")
print("-" * 90)
print("✓ Saved dimensions validated")
print("✓ Saved column structure validated")


# =============================================================================
# 21. SAVED-FILE TRANSACTION VALUE VALIDATION
# =============================================================================

saved_transaction = saved_df.loc[
    transaction_indices,
    transaction_columns
]

saved_transaction_values_match = (
    transaction_after_validation.equals(
        saved_transaction
    )
)


print(
    f"✓ Saved-file transaction values "
    f"validated : {saved_transaction_values_match}"
)

assert saved_transaction_values_match


# =============================================================================
# 22. SAVED-FILE MISSING VALUE VALIDATION
# =============================================================================

saved_missing = int(
    saved_transaction.isna().sum().sum()
)

saved_zero = int(
    (saved_transaction == 0).sum().sum()
)


saved_missing_preserved = (
    saved_missing == missing_before
)

saved_zero_preserved = (
    saved_zero == zero_before
)


print(
    f"✓ Saved-file missing values "
    f"validated : {saved_missing_preserved}"
)

print(
    f"✓ Saved-file zero values "
    f"validated : {saved_zero_preserved}"
)

assert saved_missing_preserved
assert saved_zero_preserved


# =============================================================================
# 23. SAVED-FILE STRUCTURAL ROW VALIDATION
# =============================================================================

saved_structural_rows_unchanged = True

for idx in structural_indices:

    original_row = df.loc[idx]
    saved_row = saved_df.loc[idx]

    if not original_row.equals(saved_row):

        saved_structural_rows_unchanged = False
        break


print(
    f"✓ Saved structural rows "
    f"validated : {saved_structural_rows_unchanged}"
)

assert saved_structural_rows_unchanged


# =============================================================================
# 24. FINAL REPORT
# =============================================================================

print("\n" + "=" * 90)
print("STEP 7 VALIDATION")
print("=" * 90)

print(
    f"Rows before                       : "
    f"{df.shape[0]}"
)

print(
    f"Rows after                        : "
    f"{saved_df.shape[0]}"
)

print(
    f"Columns before                    : "
    f"{df.shape[1]}"
)

print(
    f"Columns after                     : "
    f"{saved_df.shape[1]}"
)

print(
    f"Transaction columns              : "
    f"{len(transaction_columns)}"
)

print(
    f"Volume columns                   : "
    f"{len(volume_columns)}"
)

print(
    f"Value columns                    : "
    f"{len(value_columns)}"
)

print(
    f"Structural rows                  : "
    f"{len(structural_indices)}"
)

print(
    f"Transaction data rows            : "
    f"{len(transaction_indices)}"
)

print(
    f"Missing transaction cells before : "
    f"{missing_before}"
)

print(
    f"Missing transaction cells after  : "
    f"{missing_after}"
)

print(
    f"Zero transaction cells before    : "
    f"{zero_before}"
)

print(
    f"Zero transaction cells after     : "
    f"{zero_after}"
)

print(
    f"Numeric transaction cells        : "
    f"{numeric_transaction_cells}"
)

print(
    f"Non-numeric transaction cells    : "
    f"{non_numeric_transaction_cells}"
)

print(
    f"Exact duplicate transaction rows : "
    f"{transaction_duplicate_count}"
)

print(
    f"Negative volume cells             : "
    f"{negative_volume_cells}"
)

print(
    f"Negative value cells              : "
    f"{negative_value_cells}"
)

print(
    f"Positive infinity cells           : "
    f"{positive_infinity_cells}"
)

print(
    f"Negative infinity cells           : "
    f"{negative_infinity_cells}"
)

print(
    f"Transaction values modified       : "
    f"{data_values_modified}"
)

print(
    f"Structural rows modified          : "
    f"{structural_rows_modified}"
)

print(
    f"Missing values imputed            : "
    f"{imputation_performed}"
)

print(
    f"NaN converted to zero             : "
    f"{nan_converted_to_zero}"
)

print(
    f"Saved-file values unchanged       : "
    f"{saved_transaction_values_match}"
)


# =============================================================================
# 25. FINAL ASSERTIONS
# =============================================================================

assert df.shape == (40, 42)
assert saved_df.shape == (40, 42)

assert len(transaction_columns) == 40
assert len(volume_columns) == 20
assert len(value_columns) == 20

assert len(structural_indices) == 3
assert len(transaction_indices) == 37

assert numeric_transaction_cells == 1262
assert non_numeric_transaction_cells == 0

assert negative_volume_cells == 0
assert negative_value_cells == 0

assert positive_infinity_cells == 0
assert negative_infinity_cells == 0

assert transaction_duplicate_count == 0

assert missingness_preserved
assert zero_count_preserved

assert transaction_values_match
assert structural_rows_unchanged

assert saved_transaction_values_match
assert saved_missing_preserved
assert saved_zero_preserved
assert saved_structural_rows_unchanged

assert imputation_performed is False
assert nan_converted_to_zero is False
assert data_values_modified is False
assert structural_rows_modified is False


# =============================================================================
# 26. COMPLETION MESSAGE
# =============================================================================

print("\n" + "=" * 90)
print("STEP 7 COMPLETE")
print("=" * 90)

print("✓ Input dimensions validated")
print("✓ Transaction columns identified")
print("✓ Structural rows validated")
print("✓ Embedded header rows preserved")
print("✓ Transaction data validated")
print("✓ All genuine transaction cells are numeric or missing")
print("✓ Missing values preserved")
print("✓ Existing zeros preserved")
print("✓ No missing-value imputation performed")
print("✓ No NaN converted to zero")
print("✓ No negative transaction values")
print("✓ No infinity values")
print("✓ No exact duplicate transaction records")
print("✓ Transaction values unchanged")
print("✓ Structural rows unchanged")
print("✓ Column structure preserved")
print("✓ Final dataset successfully exported")
print("✓ Saved-file integrity validated")
print("✓ All assertions passed")
print("✓ Final cleaning checkpoint saved")

print(f"\nFinal cleaned file: {OUTPUT_FILE}")

print("=" * 90)

==========================================================================================
STEP 7: FINAL DATA CLEANING VALIDATION & CLEAN DATASET EXPORT
==========================================================================================

INPUT FILE
------------------------------------------------------------------------------------------
Input file : NPCI_Step6_Consistency_Cleaned.xlsx
Rows       : 40
Columns    : 42
✓ Input dimensions validated

CORE COLUMN VALIDATION
------------------------------------------------------------------------------------------
✓ Sr_No present
✓ NPCI_Operated_System present

TRANSACTION COLUMN IDENTIFICATION
------------------------------------------------------------------------------------------
Transaction columns : 40
Volume columns      : 20
Value columns       : 20
✓ Transaction column structure validated

STRUCTURAL ROW IDENTIFICATION
------------------------------------------------------------------------------------------
Embedded header rows : 2
Embedded headers     : [0, 29]
Empty-system rows    : 2
Empty-system indices : [29, 39]
Structural rows      : 3
Structural indices   : [0, 29, 39]
Transaction rows     : 37
✓ Structural rows identified correctly

FINAL CLEANED DATA STATE
------------------------------------------------------------------------------------------
Missing transaction cells : 218
Zero transaction cells    : 142

TRANSACTION DATA TYPE VALIDATION
------------------------------------------------------------------------------------------
Numeric transaction data cells    : 1262
Non-numeric transaction cells     : 0
✓ All genuine transaction cells are numeric or missing

NEGATIVE VALUE CHECK
------------------------------------------------------------------------------------------
Negative volume cells : 0
Negative value cells  : 0
✓ No negative transaction values detected

INFINITY CHECK
------------------------------------------------------------------------------------------
Positive infinity cells : 0
Negative infinity cells : 0
✓ No infinity values detected

SYSTEM NAME VALIDATION
------------------------------------------------------------------------------------------
Empty system names in transaction rows : 0
✓ All genuine transaction rows have system names

DUPLICATE VALIDATION
------------------------------------------------------------------------------------------
Exact duplicate transaction rows : 0
✓ No exact duplicate transaction records remain

MISSING / ZERO VALIDATION
------------------------------------------------------------------------------------------
Missing transaction cells before : 218
Missing transaction cells after  : 218
Zero transaction cells before    : 142
Zero transaction cells after     : 142
✓ Missing values preserved
✓ Existing zeros preserved

TRANSACTION VALUE INTEGRITY CHECK
------------------------------------------------------------------------------------------
Transaction values unchanged : True
✓ All transaction values unchanged

STRUCTURAL ROW INTEGRITY CHECK
------------------------------------------------------------------------------------------
Structural rows unchanged : True
✓ Structural rows completely unchanged

COLUMN / DIMENSION VALIDATION
------------------------------------------------------------------------------------------
Column order preserved : True
Row count preserved    : True
Column count preserved : True
✓ Column structure preserved
✓ Row count preserved
✓ Column count preserved

FINAL DATA CLEANING RULE CHECK
------------------------------------------------------------------------------------------
✓ No missing-value imputation performed
✓ No NaN converted to zero
✓ No transaction values modified
✓ No structural rows modified

SAVING FINAL CLEAN DATASET
------------------------------------------------------------------------------------------
✓ Final cleaned dataset saved: NPCI_Final_Cleaned.xlsx

SAVED-FILE INTEGRITY VALIDATION
------------------------------------------------------------------------------------------
✓ Saved dimensions validated
✓ Saved column structure validated
✓ Saved-file transaction values validated : True
✓ Saved-file missing values validated : True
✓ Saved-file zero values validated : True
✓ Saved structural rows validated : True

==========================================================================================
STEP 7 VALIDATION
==========================================================================================
Rows before                       : 40
Rows after                        : 40
Columns before                    : 42
Columns after                     : 42
Transaction columns              : 40
Volume columns                   : 20
Value columns                    : 20
Structural rows                  : 3
Transaction data rows            : 37
Missing transaction cells before : 218
Missing transaction cells after  : 218
Zero transaction cells before    : 142
Zero transaction cells after     : 142
Numeric transaction cells        : 1262
Non-numeric transaction cells    : 0
Exact duplicate transaction rows : 0
Negative volume cells             : 0
Negative value cells              : 0
Positive infinity cells           : 0
Negative infinity cells           : 0
Transaction values modified       : False
Structural rows modified          : False
Missing values imputed            : False
NaN converted to zero             : False
Saved-file values unchanged       : True

==========================================================================================
STEP 7 COMPLETE
==========================================================================================
✓ Input dimensions validated
✓ Transaction columns identified
✓ Structural rows validated
✓ Embedded header rows preserved
✓ Transaction data validated
✓ All genuine transaction cells are numeric or missing
✓ Missing values preserved
✓ Existing zeros preserved
✓ No missing-value imputation performed
✓ No NaN converted to zero
✓ No negative transaction values
✓ No infinity values
✓ No exact duplicate transaction records
✓ Transaction values unchanged
✓ Structural rows unchanged
✓ Column structure preserved
✓ Final dataset successfully exported
✓ Saved-file integrity validated
✓ All assertions passed
✓ Final cleaning checkpoint saved

Final cleaned file: NPCI_Final_Cleaned.xlsx
==========================================================================================