In [6]:
import pandas as pd
import numpy as np

file_path = r"PSI_MASTER_2025 (1).xlsx"

xls = pd.ExcelFile(file_path)

print("Sheets:")
for sheet in xls.sheet_names:
    print("-", sheet)

Sheets:
- Part I - Payment Indicators
- Part II - Modes & Channels
- Part III - Infrastructures
- Part IV - International
- Part V - Domestic Frauds

In [7]:
sheets = {}

for sheet in xls.sheet_names:
    df = pd.read_excel(
        file_path,
        sheet_name=sheet,
        header=1
    )
    
    sheets[sheet] = df
    
    print(f"{sheet}: {df.shape}")
    print(df.columns.tolist())
    print()

Part I - Payment Indicators: (540, 17)
['Item', 'Volume (lakh) - FY Total', 'Volume (lakh) - Same Month Last Year', 'Volume (lakh) - Previous Month', 'Volume (lakh) - Current Month', 'Value (₹ crore) - FY Total', 'Value (₹ crore) - Same Month Last Year', 'Value (₹ crore) - Previous Month', 'Value (₹ crore) - Current Month', 'FY Period (as labelled in source)', 'Same-Month-Last-Year (as labelled in source)', 'Previous-Month (as labelled in source)', 'Current-Month (as labelled in source)', 'Year', 'Month', 'Quarter', 'Source File']

Part II - Modes & Channels: (204, 17)
['Item', 'Volume (lakh) - FY Total', 'Volume (lakh) - Same Month Last Year', 'Volume (lakh) - Previous Month', 'Volume (lakh) - Current Month', 'Value (₹ crore) - FY Total', 'Value (₹ crore) - Same Month Last Year', 'Value (₹ crore) - Previous Month', 'Value (₹ crore) - Current Month', 'FY Period (as labelled in source)', 'Same-Month-Last-Year (as labelled in source)', 'Previous-Month (as labelled in source)', 'Current-Month (as labelled in source)', 'Year', 'Month', 'Quarter', 'Source File']

Part III - Infrastructures: (168, 13)
['Item', 'Volume (lakh) - As on Reference Date', 'Volume (lakh) - Same Month Last Year', 'Volume (lakh) - Previous Month', 'Volume (lakh) - Current Month', 'Reference Date (as labelled in source)', 'Same-Month-Last-Year (as labelled in source)', 'Previous-Month (as labelled in source)', 'Current-Month (as labelled in source)', 'Year', 'Month', 'Quarter', 'Source File']

Part IV - International: (180, 11)
['Item', 'Volume (lakh) - Previous Month', 'Volume (lakh) - Current Month', 'Value (₹ crore) - Previous Month', 'Value (₹ crore) - Current Month', 'Previous-Month (as labelled in source)', 'Current-Month (as labelled in source)', 'Year', 'Month', 'Quarter', 'Source File']

Part V - Domestic Frauds: (426, 9)
['Month', 'Volume (Lakh)', 'Value (Crore)', 'One in every X payment transaction fraudulent', 'FTS (Fraud / Payment Value * 10000)', 'Report Year', 'Report Month', 'Report Quarter', 'Source File']

In [8]:
for sheet, df in sheets.items():
    print("\n" + "="*70)
    print(sheet)
    print("="*70)
    print("Shape:", df.shape)
    print("Columns:")
    
    for i, col in enumerate(df.columns):
        print(i, ":", repr(col))

======================================================================
Part I - Payment Indicators
======================================================================
Shape: (540, 17)
Columns:
0 : 'Item'
1 : 'Volume (lakh) - FY Total'
2 : 'Volume (lakh) - Same Month Last Year'
3 : 'Volume (lakh) - Previous Month'
4 : 'Volume (lakh) - Current Month'
5 : 'Value (₹ crore) - FY Total'
6 : 'Value (₹ crore) - Same Month Last Year'
7 : 'Value (₹ crore) - Previous Month'
8 : 'Value (₹ crore) - Current Month'
9 : 'FY Period (as labelled in source)'
10 : 'Same-Month-Last-Year (as labelled in source)'
11 : 'Previous-Month (as labelled in source)'
12 : 'Current-Month (as labelled in source)'
13 : 'Year'
14 : 'Month'
15 : 'Quarter'
16 : 'Source File'

======================================================================
Part II - Modes & Channels
======================================================================
Shape: (204, 17)
Columns:
0 : 'Item'
1 : 'Volume (lakh) - FY Total'
2 : 'Volume (lakh) - Same Month Last Year'
3 : 'Volume (lakh) - Previous Month'
4 : 'Volume (lakh) - Current Month'
5 : 'Value (₹ crore) - FY Total'
6 : 'Value (₹ crore) - Same Month Last Year'
7 : 'Value (₹ crore) - Previous Month'
8 : 'Value (₹ crore) - Current Month'
9 : 'FY Period (as labelled in source)'
10 : 'Same-Month-Last-Year (as labelled in source)'
11 : 'Previous-Month (as labelled in source)'
12 : 'Current-Month (as labelled in source)'
13 : 'Year'
14 : 'Month'
15 : 'Quarter'
16 : 'Source File'

======================================================================
Part III - Infrastructures
======================================================================
Shape: (168, 13)
Columns:
0 : 'Item'
1 : 'Volume (lakh) - As on Reference Date'
2 : 'Volume (lakh) - Same Month Last Year'
3 : 'Volume (lakh) - Previous Month'
4 : 'Volume (lakh) - Current Month'
5 : 'Reference Date (as labelled in source)'
6 : 'Same-Month-Last-Year (as labelled in source)'
7 : 'Previous-Month (as labelled in source)'
8 : 'Current-Month (as labelled in source)'
9 : 'Year'
10 : 'Month'
11 : 'Quarter'
12 : 'Source File'

======================================================================
Part IV - International
======================================================================
Shape: (180, 11)
Columns:
0 : 'Item'
1 : 'Volume (lakh) - Previous Month'
2 : 'Volume (lakh) - Current Month'
3 : 'Value (₹ crore) - Previous Month'
4 : 'Value (₹ crore) - Current Month'
5 : 'Previous-Month (as labelled in source)'
6 : 'Current-Month (as labelled in source)'
7 : 'Year'
8 : 'Month'
9 : 'Quarter'
10 : 'Source File'

======================================================================
Part V - Domestic Frauds
======================================================================
Shape: (426, 9)
Columns:
0 : 'Month'
1 : 'Volume (Lakh)'
2 : 'Value (Crore)'
3 : 'One in every X payment transaction fraudulent'
4 : 'FTS (Fraud / Payment Value * 10000)'
5 : 'Report Year'
6 : 'Report Month'
7 : 'Report Quarter'
8 : 'Source File'

In [10]:
for sheet, df in sheets.items():
    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    print("Total rows:", len(df))

    if "Item" in df.columns:
        print("Missing Item:", df["Item"].isna().sum())
        
        display(
            df[df["Item"].isna()].head(20)
        )

    elif sheet == "Part V - Domestic Frauds":
        print("Missing Month:", df["Month"].isna().sum())
        
        display(
            df[df["Month"].isna()].head(20)
        )

======================================================================
Part I - Payment Indicators
======================================================================
Total rows: 540
Missing Item: 0

Empty DataFrame
Columns: [Item, Volume (lakh) - FY Total, Volume (lakh) - Same Month Last Year, Volume (lakh) - Previous Month, Volume (lakh) - Current Month, Value (₹ crore) - FY Total, Value (₹ crore) - Same Month Last Year, Value (₹ crore) - Previous Month, Value (₹ crore) - Current Month, FY Period (as labelled in source), Same-Month-Last-Year (as labelled in source), Previous-Month (as labelled in source), Current-Month (as labelled in source), Year, Month, Quarter, Source File]
Index: []

======================================================================
Part II - Modes & Channels
======================================================================
Total rows: 204
Missing Item: 0

Empty DataFrame
Columns: [Item, Volume (lakh) - FY Total, Volume (lakh) - Same Month Last Year, Volume (lakh) - Previous Month, Volume (lakh) - Current Month, Value (₹ crore) - FY Total, Value (₹ crore) - Same Month Last Year, Value (₹ crore) - Previous Month, Value (₹ crore) - Current Month, FY Period (as labelled in source), Same-Month-Last-Year (as labelled in source), Previous-Month (as labelled in source), Current-Month (as labelled in source), Year, Month, Quarter, Source File]
Index: []

======================================================================
Part III - Infrastructures
======================================================================
Total rows: 168
Missing Item: 0

Empty DataFrame
Columns: [Item, Volume (lakh) - As on Reference Date, Volume (lakh) - Same Month Last Year, Volume (lakh) - Previous Month, Volume (lakh) - Current Month, Reference Date (as labelled in source), Same-Month-Last-Year (as labelled in source), Previous-Month (as labelled in source), Current-Month (as labelled in source), Year, Month, Quarter, Source File]
Index: []

======================================================================
Part IV - International
======================================================================
Total rows: 180
Missing Item: 0

Empty DataFrame
Columns: [Item, Volume (lakh) - Previous Month, Volume (lakh) - Current Month, Value (₹ crore) - Previous Month, Value (₹ crore) - Current Month, Previous-Month (as labelled in source), Current-Month (as labelled in source), Year, Month, Quarter, Source File]
Index: []

======================================================================
Part V - Domestic Frauds
======================================================================
Total rows: 426
Missing Month: 0

Empty DataFrame
Columns: [Month, Volume (Lakh), Value (Crore), One in every X payment transaction fraudulent, FTS (Fraud / Payment Value * 10000), Report Year, Report Month, Report Quarter, Source File]
Index: []

In [11]:
# Step 5: Detailed missing-value check

for sheet, df in sheets.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    missing = df.isna().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    missing_summary = pd.DataFrame({
        "Missing Values": missing,
        "Missing %": missing_pct
    })

    missing_summary = missing_summary[
        missing_summary["Missing Values"] > 0
    ].sort_values("Missing Values", ascending=False)

    if missing_summary.empty:
        print("No missing values.")
    else:
        display(missing_summary)

======================================================================
Part I - Payment Indicators
======================================================================

                                              Missing Values  Missing %
Same-Month-Last-Year (as labelled in source)             540     100.00
Volume (lakh) - FY Total                                  60      11.11
Volume (lakh) - Previous Month                            60      11.11
Volume (lakh) - Same Month Last Year                      60      11.11
Value (₹ crore) - FY Total                                60      11.11
Value (₹ crore) - Same Month Last Year                    60      11.11
Value (₹ crore) - Previous Month                          60      11.11
Volume (lakh) - Current Month                             60      11.11
Value (₹ crore) - Current Month                           60      11.11
FY Period (as labelled in source)                         60      11.11
Previous-Month (as labelled in source)                    60      11.11
Current-Month (as labelled in source)                     60      11.11
Year                                                      60      11.11
Month                                                     60      11.11
Quarter                                                   60      11.11
Source File                                               60      11.11

======================================================================
Part II - Modes & Channels
======================================================================

                                              Missing Values  Missing %
Same-Month-Last-Year (as labelled in source)             204     100.00
Volume (lakh) - FY Total                                  24      11.76
Volume (lakh) - Previous Month                            24      11.76
Volume (lakh) - Same Month Last Year                      24      11.76
Value (₹ crore) - FY Total                                24      11.76
Value (₹ crore) - Same Month Last Year                    24      11.76
Value (₹ crore) - Previous Month                          24      11.76
Volume (lakh) - Current Month                             24      11.76
Value (₹ crore) - Current Month                           24      11.76
FY Period (as labelled in source)                         24      11.76
Previous-Month (as labelled in source)                    24      11.76
Current-Month (as labelled in source)                     24      11.76
Year                                                      24      11.76
Month                                                     24      11.76
Quarter                                                   24      11.76
Source File                                               24      11.76

======================================================================
Part III - Infrastructures
======================================================================

                                              Missing Values  Missing %
Volume (lakh) - As on Reference Date                      12       7.14
Volume (lakh) - Same Month Last Year                      12       7.14
Volume (lakh) - Previous Month                            12       7.14
Volume (lakh) - Current Month                             12       7.14
Reference Date (as labelled in source)                    12       7.14
Same-Month-Last-Year (as labelled in source)              12       7.14
Previous-Month (as labelled in source)                    12       7.14
Current-Month (as labelled in source)                     12       7.14
Year                                                      12       7.14
Month                                                     12       7.14
Quarter                                                   12       7.14
Source File                                               12       7.14

======================================================================
Part IV - International
======================================================================
No missing values.

======================================================================
Part V - Domestic Frauds
======================================================================

                                               Missing Values  Missing %
Volume (Lakh)                                              12       2.82
Value (Crore)                                              12       2.82
One in every X payment transaction fraudulent              12       2.82
FTS (Fraud / Payment Value * 10000)                        12       2.82
Report Year                                                12       2.82
Report Month                                               12       2.82
Report Quarter                                             12       2.82
Source File                                                12       2.82

In [13]:
# Step 6: Remove structural/header rows

cleaned_sheets = {}

for sheet, df in sheets.items():

    df = df.copy()

    if "Year" in df.columns:
        # Keep only actual monthly observations
        df = df[df["Year"].notna()].copy()

    elif "Report Year" in df.columns:
        # Part V: keep only actual fraud observations
        df = df[df["Report Year"].notna()].copy()

    cleaned_sheets[sheet] = df.reset_index(drop=True)

    print(f"{sheet}:")
    print("  Original rows :", len(sheets[sheet]))
    print("  Cleaned rows  :", len(df))
    print("  Removed rows  :", len(sheets[sheet]) - len(df))

Part I - Payment Indicators:
  Original rows : 540
  Cleaned rows  : 480
  Removed rows  : 60
Part II - Modes & Channels:
  Original rows : 204
  Cleaned rows  : 180
  Removed rows  : 24
Part III - Infrastructures:
  Original rows : 168
  Cleaned rows  : 156
  Removed rows  : 12
Part IV - International:
  Original rows : 180
  Cleaned rows  : 180
  Removed rows  : 0
Part V - Domestic Frauds:
  Original rows : 426
  Cleaned rows  : 414
  Removed rows  : 12

In [14]:
for sheet, df in sheets.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    print("Total rows:", len(df))
    print("Exact duplicate rows:", df.duplicated().sum())

    if df.duplicated().sum() > 0:
        print("\nDuplicate rows:")
        display(
            df[df.duplicated(keep=False)]
            .sort_values(by=df.columns.tolist())
            .head(30)
        )

======================================================================
Part I - Payment Indicators
======================================================================
Total rows: 540
Exact duplicate rows: 55

Duplicate rows:

,Item,Volume (lakh) - FY Total,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Value (₹ crore) - FY Total,Value (₹ crore) - Same Month Last Year,Value (₹ crore) - Previous Month,Value (₹ crore) - Current Month,FY Period (as labelled in source),Same-Month-Last-Year (as labelled in source),Previous-Month (as labelled in source),Current-Month (as labelled in source),Year,Month,Quarter,Source File
0,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Part II - Modes & Channels
======================================================================
Total rows: 204
Exact duplicate rows: 22

Duplicate rows:

,Item,Volume (lakh) - FY Total,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Value (₹ crore) - FY Total,Value (₹ crore) - Same Month Last Year,Value (₹ crore) - Previous Month,Value (₹ crore) - Current Month,FY Period (as labelled in source),Same-Month-Last-Year (as labelled in source),Previous-Month (as labelled in source),Current-Month (as labelled in source),Year,Month,Quarter,Source File
0,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Part III - Infrastructures
======================================================================
Total rows: 168
Exact duplicate rows: 11

Duplicate rows:

,Item,Volume (lakh) - As on Reference Date,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Reference Date (as labelled in source),Same-Month-Last-Year (as labelled in source),Previous-Month (as labelled in source),Current-Month (as labelled in source),Year,Month,Quarter,Source File
0,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Part IV - International
======================================================================
Total rows: 180
Exact duplicate rows: 0

======================================================================
Part V - Domestic Frauds
======================================================================
Total rows: 426
Exact duplicate rows: 0

In [15]:
for sheet, df in sheets.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    if sheet == "Part V - Domestic Frauds":
        key_cols = ["Month", "Report Year", "Report Month"]
    else:
        key_cols = ["Item", "Year", "Month"]

    duplicate_count = df.duplicated(
        subset=key_cols,
        keep=False
    ).sum()

    print("Duplicate observations based on:", key_cols)
    print("Duplicate rows:", duplicate_count)

    if duplicate_count > 0:
        display(
            df[df.duplicated(subset=key_cols, keep=False)]
            .sort_values(key_cols)
            .head(30)
        )

======================================================================
Part I - Payment Indicators
======================================================================
Duplicate observations based on: ['Item', 'Year', 'Month']
Duplicate rows: 60

,Item,Volume (lakh) - FY Total,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Value (₹ crore) - FY Total,Value (₹ crore) - Same Month Last Year,Value (₹ crore) - Previous Month,Value (₹ crore) - Current Month,FY Period (as labelled in source),Same-Month-Last-Year (as labelled in source),Previous-Month (as labelled in source),Current-Month (as labelled in source),Year,Month,Quarter,Source File
0,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,B. Payment Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Part II - Modes & Channels
======================================================================
Duplicate observations based on: ['Item', 'Year', 'Month']
Duplicate rows: 24

,Item,Volume (lakh) - FY Total,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Value (₹ crore) - FY Total,Value (₹ crore) - Same Month Last Year,Value (₹ crore) - Previous Month,Value (₹ crore) - Current Month,FY Period (as labelled in source),Same-Month-Last-Year (as labelled in source),Previous-Month (as labelled in source),Current-Month (as labelled in source),Year,Month,Quarter,Source File
0,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,A. Other Payment Channels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,B. ATMs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Part III - Infrastructures
======================================================================
Duplicate observations based on: ['Item', 'Year', 'Month']
Duplicate rows: 12

,Item,Volume (lakh) - As on Reference Date,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Reference Date (as labelled in source),Same-Month-Last-Year (as labelled in source),Previous-Month (as labelled in source),Current-Month (as labelled in source),Year,Month,Quarter,Source File
0,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,Payment System Infrastructures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Part IV - International
======================================================================
Duplicate observations based on: ['Item', 'Year', 'Month']
Duplicate rows: 0

======================================================================
Part V - Domestic Frauds
======================================================================
Duplicate observations based on: ['Month', 'Report Year', 'Report Month']
Duplicate rows: 0

In [17]:
# Create cleaned copies of all sheets
# We remove only rows where the time/report Year is missing.
# These are the structural/header rows identified earlier.

sheets_cleaned = {}

for sheet, df in sheets.items():

    df = df.copy()

    if sheet == "Part V - Domestic Frauds":
        # Part V uses Report Year
        df_clean = df[df["Report Year"].notna()].copy()
    else:
        # Parts I-IV use Year
        df_clean = df[df["Year"].notna()].copy()

    sheets_cleaned[sheet] = df_clean

    print(f"{sheet}:")
    print(f"  Original rows : {len(df)}")
    print(f"  Cleaned rows  : {len(df_clean)}")
    print(f"  Removed rows  : {len(df) - len(df_clean)}")

Part I - Payment Indicators:
  Original rows : 540
  Cleaned rows  : 480
  Removed rows  : 60
Part II - Modes & Channels:
  Original rows : 204
  Cleaned rows  : 180
  Removed rows  : 24
Part III - Infrastructures:
  Original rows : 168
  Cleaned rows  : 156
  Removed rows  : 12
Part IV - International:
  Original rows : 180
  Cleaned rows  : 180
  Removed rows  : 0
Part V - Domestic Frauds:
  Original rows : 426
  Cleaned rows  : 414
  Removed rows  : 12

In [18]:
for sheet, df in sheets_cleaned.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    if sheet == "Part V - Domestic Frauds":
        print("Missing Report Year:", df["Report Year"].isna().sum())
    else:
        print("Missing Year:", df["Year"].isna().sum())

======================================================================
Part I - Payment Indicators
======================================================================
Missing Year: 0

======================================================================
Part II - Modes & Channels
======================================================================
Missing Year: 0

======================================================================
Part III - Infrastructures
======================================================================
Missing Year: 0

======================================================================
Part IV - International
======================================================================
Missing Year: 0

======================================================================
Part V - Domestic Frauds
======================================================================
Missing Report Year: 0

In [19]:
# Step 2: Check exact duplicate rows in the cleaned data

for sheet, df in sheets_cleaned.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    duplicate_count = df.duplicated().sum()

    print("Exact duplicate rows:", duplicate_count)

    if duplicate_count > 0:
        display(df[df.duplicated(keep=False)].head(20))

======================================================================
Part I - Payment Indicators
======================================================================
Exact duplicate rows: 0

======================================================================
Part II - Modes & Channels
======================================================================
Exact duplicate rows: 0

======================================================================
Part III - Infrastructures
======================================================================
Exact duplicate rows: 0

======================================================================
Part IV - International
======================================================================
Exact duplicate rows: 0

======================================================================
Part V - Domestic Frauds
======================================================================
Exact duplicate rows: 0

In [20]:
# Step 3: Check data types

for sheet, df in sheets_cleaned.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    display(
        pd.DataFrame({
            "Column": df.columns,
            "Data Type": df.dtypes.astype(str).values,
            "Non-Null Values": df.notna().sum().values
        })
    )

======================================================================
Part I - Payment Indicators
======================================================================

                                          Column Data Type  Non-Null Values
0                                           Item       str              480
1                       Volume (lakh) - FY Total   float64              480
2           Volume (lakh) - Same Month Last Year   float64              480
3                 Volume (lakh) - Previous Month   float64              480
4                  Volume (lakh) - Current Month   float64              480
5                     Value (₹ crore) - FY Total   float64              480
6         Value (₹ crore) - Same Month Last Year   float64              480
7               Value (₹ crore) - Previous Month   float64              480
8                Value (₹ crore) - Current Month   float64              480
9              FY Period (as labelled in source)       str              480
10  Same-Month-Last-Year (as labelled in source)   float64                0
11        Previous-Month (as labelled in source)   float64              480
12         Current-Month (as labelled in source)   float64              480
13                                          Year   float64              480
14                                         Month       str              480
15                                       Quarter       str              480
16                                   Source File       str              480

======================================================================
Part II - Modes & Channels
======================================================================

                                          Column Data Type  Non-Null Values
0                                           Item       str              180
1                       Volume (lakh) - FY Total   float64              180
2           Volume (lakh) - Same Month Last Year   float64              180
3                 Volume (lakh) - Previous Month   float64              180
4                  Volume (lakh) - Current Month   float64              180
5                     Value (₹ crore) - FY Total   float64              180
6         Value (₹ crore) - Same Month Last Year   float64              180
7               Value (₹ crore) - Previous Month   float64              180
8                Value (₹ crore) - Current Month   float64              180
9              FY Period (as labelled in source)       str              180
10  Same-Month-Last-Year (as labelled in source)   float64                0
11        Previous-Month (as labelled in source)   float64              180
12         Current-Month (as labelled in source)   float64              180
13                                          Year   float64              180
14                                         Month       str              180
15                                       Quarter       str              180
16                                   Source File       str              180

======================================================================
Part III - Infrastructures
======================================================================

                                          Column Data Type  Non-Null Values
0                                           Item       str              156
1           Volume (lakh) - As on Reference Date   float64              156
2           Volume (lakh) - Same Month Last Year   float64              156
3                 Volume (lakh) - Previous Month   float64              156
4                  Volume (lakh) - Current Month   float64              156
5         Reference Date (as labelled in source)       str              156
6   Same-Month-Last-Year (as labelled in source)       str              156
7         Previous-Month (as labelled in source)       str              156
8          Current-Month (as labelled in source)       str              156
9                                           Year   float64              156
10                                         Month       str              156
11                                       Quarter       str              156
12                                   Source File       str              156

======================================================================
Part IV - International
======================================================================

                                    Column Data Type  Non-Null Values
0                                     Item       str              180
1           Volume (lakh) - Previous Month   float64              180
2            Volume (lakh) - Current Month   float64              180
3         Value (₹ crore) - Previous Month   float64              180
4          Value (₹ crore) - Current Month   float64              180
5   Previous-Month (as labelled in source)       str              180
6    Current-Month (as labelled in source)       str              180
7                                     Year     int64              180
8                                    Month       str              180
9                                  Quarter       str              180
10                             Source File       str              180

======================================================================
Part V - Domestic Frauds
======================================================================

                                          Column Data Type  Non-Null Values
0                                          Month       str              414
1                                  Volume (Lakh)   float64              414
2                                  Value (Crore)   float64              414
3  One in every X payment transaction fraudulent   float64              414
4            FTS (Fraud / Payment Value * 10000)       str              414
5                                    Report Year   float64              414
6                                   Report Month       str              414
7                                 Report Quarter       str              414
8                                    Source File       str              414

In [21]:
# Step 4: Identify completely empty columns

for sheet, df in sheets_cleaned.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    empty_cols = df.columns[df.isna().all()].tolist()

    print("Completely empty columns:")
    print(empty_cols)

======================================================================
Part I - Payment Indicators
======================================================================
Completely empty columns:
['Same-Month-Last-Year (as labelled in source)']

======================================================================
Part II - Modes & Channels
======================================================================
Completely empty columns:
['Same-Month-Last-Year (as labelled in source)']

======================================================================
Part III - Infrastructures
======================================================================
Completely empty columns:
[]

======================================================================
Part IV - International
======================================================================
Completely empty columns:
[]

======================================================================
Part V - Domestic Frauds
======================================================================
Completely empty columns:
[]

In [22]:
# Remove columns that contain no data at all

for sheet in sheets_cleaned:

    df = sheets_cleaned[sheet]

    empty_cols = df.columns[df.isna().all()].tolist()

    if empty_cols:
        sheets_cleaned[sheet] = df.drop(columns=empty_cols)

        print(f"{sheet}: removed {len(empty_cols)} empty column(s)")
        print(empty_cols)
    else:
        print(f"{sheet}: no completely empty columns")

Part I - Payment Indicators: removed 1 empty column(s)
['Same-Month-Last-Year (as labelled in source)']
Part II - Modes & Channels: removed 1 empty column(s)
['Same-Month-Last-Year (as labelled in source)']
Part III - Infrastructures: no completely empty columns
Part IV - International: no completely empty columns
Part V - Domestic Frauds: no completely empty columns

In [23]:
# Step 5: Check negative and zero values in numerical columns

for sheet, df in sheets_cleaned.items():

    print("\n" + "="*70)
    print(sheet)
    print("="*70)

    numeric_cols = df.select_dtypes(include="number").columns

    for col in numeric_cols:

        negative_count = (df[col] < 0).sum()
        zero_count = (df[col] == 0).sum()

        if negative_count > 0 or zero_count > 0:

            print(f"\n{col}")
            print("  Negative values:", negative_count)
            print("  Zero values    :", zero_count)

======================================================================
Part I - Payment Indicators
======================================================================

Volume (lakh) - FY Total
  Negative values: 0
  Zero values    : 12

Volume (lakh) - Same Month Last Year
  Negative values: 0
  Zero values    : 12

Volume (lakh) - Previous Month
  Negative values: 0
  Zero values    : 12

Volume (lakh) - Current Month
  Negative values: 0
  Zero values    : 12

Value (₹ crore) - FY Total
  Negative values: 0
  Zero values    : 12

Value (₹ crore) - Same Month Last Year
  Negative values: 0
  Zero values    : 12

Value (₹ crore) - Previous Month
  Negative values: 0
  Zero values    : 12

Value (₹ crore) - Current Month
  Negative values: 0
  Zero values    : 12

======================================================================
Part II - Modes & Channels
======================================================================

======================================================================
Part III - Infrastructures
======================================================================

======================================================================
Part IV - International
======================================================================

======================================================================
Part V - Domestic Frauds
======================================================================

In [24]:
df = sheets_cleaned["Part I - Payment Indicators"]

numeric_cols = [
    "Volume (lakh) - FY Total",
    "Volume (lakh) - Same Month Last Year",
    "Volume (lakh) - Previous Month",
    "Volume (lakh) - Current Month",
    "Value (₹ crore) - FY Total",
    "Value (₹ crore) - Same Month Last Year",
    "Value (₹ crore) - Previous Month",
    "Value (₹ crore) - Current Month"
]

# Find rows where all payment volume/value measures are zero
zero_rows = df[(df[numeric_cols] == 0).all(axis=1)]

print("Rows where all payment measures are zero:", len(zero_rows))

display(
    zero_rows[
        ["Item", "Year", "Month", "Quarter"] + numeric_cols
    ]
)

Rows where all payment measures are zero: 12

,Item,Year,Month,Quarter,Volume (lakh) - FY Total,Volume (lakh) - Same Month Last Year,Volume (lakh) - Previous Month,Volume (lakh) - Current Month,Value (₹ crore) - FY Total,Value (₹ crore) - Same Month Last Year,Value (₹ crore) - Previous Month,Value (₹ crore) - Current Month
41,6.2 Others,2025.0,January,Q1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,6.2 Others,2025.0,February,Q1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
131,6.2 Others,2025.0,March,Q1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176,6.2 Others,2025.0,April,Q2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221,6.2 Others,2025.0,May,Q2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,6.2 Others,2025.0,June,Q2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
311,6.2 Others,2025.0,July,Q3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
356,6.2 Others,2025.0,August,Q3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
401,6.2 Others,2025.0,September,Q3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
446,6.2 Others,2025.0,October,Q4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
491,6.2 Others,2025.0,November,Q4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536,6.2 Others,2025.0,December,Q4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
# Check categorical and temporal consistency

month_order = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

quarter_order = {
    "January": "Q1",
    "February": "Q1",
    "March": "Q1",
    "April": "Q2",
    "May": "Q2",
    "June": "Q2",
    "July": "Q3",
    "August": "Q3",
    "September": "Q3",
    "October": "Q4",
    "November": "Q4",
    "December": "Q4"
}

for sheet, df in sheets_cleaned.items():

    print("\n" + "=" * 70)
    print(sheet)
    print("=" * 70)

    if sheet == "Part V - Domestic Frauds":
        year_col = "Report Year"
        month_col = "Report Month"
        quarter_col = "Report Quarter"
    else:
        year_col = "Year"
        month_col = "Month"
        quarter_col = "Quarter"

    # Check invalid months
    invalid_months = df[
        ~df[month_col].isin(month_order.keys())
    ]

    print("Invalid months:", len(invalid_months))

    if len(invalid_months) > 0:
        display(invalid_months[[month_col]].drop_duplicates())

    # Check invalid quarters
    invalid_quarters = df[
        ~df[quarter_col].isin(["Q1", "Q2", "Q3", "Q4"])
    ]

    print("Invalid quarters:", len(invalid_quarters))

    if len(invalid_quarters) > 0:
        display(invalid_quarters[[quarter_col]].drop_duplicates())

    # Check Month → Quarter consistency
    expected_quarter = df[month_col].map(quarter_order)

    inconsistent_quarter = df[
        expected_quarter.notna() &
        (df[quarter_col] != expected_quarter)
    ]

    print("Month-Quarter inconsistencies:", len(inconsistent_quarter))

    if len(inconsistent_quarter) > 0:
        display(
            inconsistent_quarter[
                [month_col, quarter_col]
            ].drop_duplicates()
        )

======================================================================
Part I - Payment Indicators
======================================================================
Invalid months: 0
Invalid quarters: 0
Month-Quarter inconsistencies: 0

======================================================================
Part II - Modes & Channels
======================================================================
Invalid months: 0
Invalid quarters: 0
Month-Quarter inconsistencies: 0

======================================================================
Part III - Infrastructures
======================================================================
Invalid months: 0
Invalid quarters: 0
Month-Quarter inconsistencies: 0

======================================================================
Part IV - International
======================================================================
Invalid months: 0
Invalid quarters: 0
Month-Quarter inconsistencies: 0

======================================================================
Part V - Domestic Frauds
======================================================================
Invalid months: 0
Invalid quarters: 0
Month-Quarter inconsistencies: 0

In [26]:
# Check numeric columns for invalid / non-numeric values

for sheet, df in sheets_cleaned.items():

    print("\n" + "=" * 70)
    print(sheet)
    print("=" * 70)

    # Identify numeric-looking columns
    numeric_columns = []

    for col in df.columns:
        if any(keyword in col.lower() for keyword in [
            "volume",
            "value",
            "year",
            "fraud",
            "fts",
            "one in every"
        ]):
            numeric_columns.append(col)

    for col in numeric_columns:

        # Try converting to numeric without changing original data
        converted = pd.to_numeric(df[col], errors="coerce")

        # Values that were not numeric
        invalid = df[col].notna() & converted.isna()

        print(f"\n{col}")
        print("  Data type       :", df[col].dtype)
        print("  Non-null values :", df[col].notna().sum())
        print("  Non-numeric     :", invalid.sum())

        if invalid.sum() > 0:
            print("  Examples:")
            print(df.loc[invalid, col].unique()[:10])

======================================================================
Part I - Payment Indicators
======================================================================

Volume (lakh) - FY Total
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Volume (lakh) - Same Month Last Year
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Volume (lakh) - Previous Month
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Volume (lakh) - Current Month
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Value (₹ crore) - FY Total
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Value (₹ crore) - Same Month Last Year
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Value (₹ crore) - Previous Month
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Value (₹ crore) - Current Month
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

Year
  Data type       : float64
  Non-null values : 480
  Non-numeric     : 0

======================================================================
Part II - Modes & Channels
======================================================================

Volume (lakh) - FY Total
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Volume (lakh) - Same Month Last Year
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Volume (lakh) - Previous Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Volume (lakh) - Current Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Value (₹ crore) - FY Total
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Value (₹ crore) - Same Month Last Year
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Value (₹ crore) - Previous Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Value (₹ crore) - Current Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Year
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

======================================================================
Part III - Infrastructures
======================================================================

Volume (lakh) - As on Reference Date
  Data type       : float64
  Non-null values : 156
  Non-numeric     : 0

Volume (lakh) - Same Month Last Year
  Data type       : float64
  Non-null values : 156
  Non-numeric     : 0

Volume (lakh) - Previous Month
  Data type       : float64
  Non-null values : 156
  Non-numeric     : 0

Volume (lakh) - Current Month
  Data type       : float64
  Non-null values : 156
  Non-numeric     : 0

Same-Month-Last-Year (as labelled in source)
  Data type       : str
  Non-null values : 156
  Non-numeric     : 156
  Examples:
<ArrowStringArray>
[  '2024\nJanuary',  '2024\nFebruary',     '2024\nMarch',     '2024\nApril',
       '2024\nMay',      '2024\nJune',      '2024\nJuly',    '2024\nAugust',
 '2024\nSeptember',   '2024\nOctober']
Length: 10, dtype: str

Year
  Data type       : float64
  Non-null values : 156
  Non-numeric     : 0

======================================================================
Part IV - International
======================================================================

Volume (lakh) - Previous Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Volume (lakh) - Current Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Value (₹ crore) - Previous Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Value (₹ crore) - Current Month
  Data type       : float64
  Non-null values : 180
  Non-numeric     : 0

Year
  Data type       : int64
  Non-null values : 180
  Non-numeric     : 0

======================================================================
Part V - Domestic Frauds
======================================================================

Volume (Lakh)
  Data type       : float64
  Non-null values : 414
  Non-numeric     : 0

Value (Crore)
  Data type       : float64
  Non-null values : 414
  Non-numeric     : 0

One in every X payment transaction fraudulent
  Data type       : float64
  Non-null values : 414
  Non-numeric     : 0

FTS (Fraud / Payment Value * 10000)
  Data type       : str
  Non-null values : 414
  Non-numeric     : 414
  Examples:
<ArrowStringArray>
['0.127 bps', '0.143 bps', '0.103 bps', '0.106 bps', '0.177 bps', '0.142 bps',
 '0.152 bps', '0.147 bps', '0.128 bps', '0.146 bps']
Length: 10, dtype: str

Report Year
  Data type       : float64
  Non-null values : 414
  Non-numeric     : 0

In [27]:
# Convert FTS from text like "0.127 bps" into a numeric column

fraud_df = sheets_cleaned["Part V - Domestic Frauds"].copy()

fraud_df["FTS (bps)"] = (
    fraud_df["FTS (Fraud / Payment Value * 10000)"]
    .str.replace("bps", "", regex=False)
    .str.strip()
    .astype(float)
)

print("Original FTS column:")
print(fraud_df["FTS (Fraud / Payment Value * 10000)"].head())

print("\nConverted FTS (bps):")
print(fraud_df["FTS (bps)"].head())

print("\nData type:")
print(fraud_df["FTS (bps)"].dtype)

print("\nMissing values:")
print(fraud_df["FTS (bps)"].isna().sum())

Original FTS column:
1    0.127 bps
2    0.127 bps
3    0.143 bps
4    0.103 bps
5    0.106 bps
Name: FTS (Fraud / Payment Value * 10000), dtype: str

Converted FTS (bps):
1    0.127
2    0.127
3    0.143
4    0.103
5    0.106
Name: FTS (bps), dtype: float64

Data type:
float64

Missing values:
0

In [28]:
sheets_cleaned["Part V - Domestic Frauds"] = fraud_df

In [29]:
# Check numerical ranges and potential outliers

for sheet, df in sheets_cleaned.items():

    print("\n" + "=" * 70)
    print(sheet)
    print("=" * 70)

    numeric_cols = df.select_dtypes(include="number").columns

    for col in numeric_cols:

        s = df[col].dropna()

        if len(s) == 0:
            continue

        q1 = s.quantile(0.25)
        q3 = s.quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outliers = s[(s < lower) | (s > upper)]

        print(f"\n{col}")
        print(f"  Min       : {s.min()}")
        print(f"  Max       : {s.max()}")
        print(f"  Mean      : {s.mean():.4f}")
        print(f"  Median    : {s.median():.4f}")
        print(f"  Q1        : {q1:.4f}")
        print(f"  Q3        : {q3:.4f}")
        print(f"  IQR       : {iqr:.4f}")
        print(f"  Outliers  : {len(outliers)}")

======================================================================
Part I - Payment Indicators
======================================================================

Volume (lakh) - FY Total
  Min       : 0.0
  Max       : 2225910.00799988
  Mean      : 268034.7456
  Median    : 10547.9344
  Q1        : 39.2964
  Q3        : 49030.1694
  IQR       : 48990.8729
  Outliers  : 60

Volume (lakh) - Same Month Last Year
  Min       : 0.0
  Max       : 199610.989311529
  Mean      : 21862.2887
  Median    : 889.2754
  Q1        : 2.6992
  Q3        : 4025.9455
  IQR       : 4023.2463
  Outliers  : 60

Volume (lakh) - Previous Month
  Min       : 0.0
  Max       : 242250.175096286
  Mean      : 27550.7972
  Median    : 908.3849
  Q1        : 3.6610
  Q3        : 4523.6528
  IQR       : 4519.9918
  Outliers  : 60

Volume (lakh) - Current Month
  Min       : 0.0
  Max       : 251531.459379983
  Mean      : 28105.6756
  Median    : 908.3849
  Q1        : 3.6610
  Q3        : 4586.6535
  IQR       : 4582.9925
  Outliers  : 60

Value (₹ crore) - FY Total
  Min       : 0.0
  Max       : 296218030.451949
  Mean      : 49827927.5229
  Median    : 2316073.1969
  Q1        : 216751.3672
  Q3        : 77286610.5600
  IQR       : 77069859.1928
  Outliers  : 46

Value (₹ crore) - Same Month Last Year
  Min       : 0.0
  Max       : 27448819.7175689
  Mean      : 4070994.4969
  Median    : 199191.9810
  Q1        : 16286.5936
  Q3        : 6303683.6861
  IQR       : 6287397.0925
  Outliers  : 49

Value (₹ crore) - Previous Month
  Min       : 0.0
  Max       : 32781615.5070443
  Mean      : 4732802.2743
  Median    : 222995.0182
  Q1        : 19175.2201
  Q3        : 7182110.4550
  IQR       : 7162935.2350
  Outliers  : 48

Value (₹ crore) - Current Month
  Min       : 0.0
  Max       : 34813890.9704505
  Mean      : 4808078.6904
  Median    : 223485.3650
  Q1        : 19438.3757
  Q3        : 7315037.9055
  IQR       : 7295599.5298
  Outliers  : 47

Previous-Month (as labelled in source)
  Min       : 2024.0
  Max       : 2025.0
  Mean      : 2024.9167
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 40

Current-Month (as labelled in source)
  Min       : 2025.0
  Max       : 2025.0
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

Year
  Min       : 2025.0
  Max       : 2025.0
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

======================================================================
Part II - Modes & Channels
======================================================================

Volume (lakh) - FY Total
  Min       : 0.11695
  Max       : 1756976.91487
  Mean      : 239063.9027
  Median    : 13056.3696
  Q1        : 97.2509
  Q3        : 60308.1079
  IQR       : 60210.8570
  Outliers  : 24

Volume (lakh) - Same Month Last Year
  Min       : 0.01253
  Max       : 156763.27573
  Mean      : 19573.0632
  Median    : 1147.5885
  Q1        : 8.6080
  Q3        : 5167.8940
  IQR       : 5159.2860
  Outliers  : 24

Volume (lakh) - Previous Month
  Min       : 0.02022
  Max       : 190010.12288
  Mean      : 24259.3408
  Median    : 1093.3250
  Q1        : 7.3530
  Q3        : 4609.9427
  IQR       : 4602.5897
  Outliers  : 24

Volume (lakh) - Current Month
  Min       : 0.02022
  Max       : 198740.92261
  Mean      : 24711.2998
  Median    : 1084.3400
  Q1        : 7.0778
  Q3        : 4601.6881
  IQR       : 4594.6103
  Outliers  : 24

Value (₹ crore) - FY Total
  Min       : 0.652615665
  Max       : 131858132.554256
  Mean      : 22407259.9073
  Median    : 3046987.4904
  Q1        : 5083.8568
  Q3        : 39206168.4343
  IQR       : 39201084.5774
  Outliers  : 12

Value (₹ crore) - Same Month Last Year
  Min       : 0.1033819
  Max       : 12203094.9023198
  Mean      : 1835514.3933
  Median    : 250739.0887
  Q1        : 443.4007
  Q3        : 2978994.4080
  IQR       : 2978551.0073
  Outliers  : 12

Value (₹ crore) - Previous Month
  Min       : 0.2639387
  Max       : 13992340.250978
  Mean      : 2151166.7991
  Median    : 233504.6466
  Q1        : 408.5744
  Q3        : 3458721.8437
  IQR       : 3458313.2693
  Outliers  : 12

Value (₹ crore) - Current Month
  Min       : 0.2639387
  Max       : 15193135.3829347
  Mean      : 2139094.7725
  Median    : 233504.6466
  Q1        : 401.1965
  Q3        : 3401860.4930
  IQR       : 3401459.2965
  Outliers  : 11

Previous-Month (as labelled in source)
  Min       : 2024.0
  Max       : 2025.0
  Mean      : 2024.9167
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 15

Current-Month (as labelled in source)
  Min       : 2025.0
  Max       : 2025.0
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

Year
  Min       : 2025.0
  Max       : 2025.0
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

======================================================================
Part III - Infrastructures
======================================================================

Volume (lakh) - As on Reference Date
  Min       : 0.34602
  Max       : 16743.62719
  Mean      : 4312.5301
  Median    : 1098.8469
  Q1        : 14.8188
  Q3        : 8678.4398
  IQR       : 8663.6210
  Outliers  : 0

Volume (lakh) - Same Month Last Year
  Min       : 0.34004
  Max       : 17676.26355
  Mean      : 4458.5346
  Median    : 1041.9073
  Q1        : 14.5261
  Q3        : 9697.3238
  IQR       : 9682.7977
  Outliers  : 0

Volume (lakh) - Previous Month
  Min       : 0.3559
  Max       : 19107.1291
  Mean      : 4505.2341
  Median    : 1111.9748
  Q1        : 14.6341
  Q3        : 9724.2340
  IQR       : 9709.5999
  Outliers  : 0

Volume (lakh) - Current Month
  Min       : 0.3559
  Max       : 20873.16385
  Mean      : 4615.3961
  Median    : 1114.1018
  Q1        : 14.5976
  Q3        : 9829.4864
  IQR       : 9814.8888
  Outliers  : 0

Year
  Min       : 2025.0
  Max       : 2025.0
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

======================================================================
Part IV - International
======================================================================

Volume (lakh) - Previous Month
  Min       : 0.35004
  Max       : 187.97279
  Mean      : 41.0920
  Median    : 25.8251
  Q1        : 4.6298
  Q3        : 48.8661
  IQR       : 44.2363
  Outliers  : 22

Volume (lakh) - Current Month
  Min       : 0.34779
  Max       : 187.97279
  Mean      : 41.6136
  Median    : 26.4079
  Q1        : 4.6298
  Q3        : 50.6821
  IQR       : 46.0523
  Outliers  : 21

Value (₹ crore) - Previous Month
  Min       : 62.9681207988756
  Max       : 13403.7119572119
  Mean      : 3018.7630
  Median    : 1345.5956
  Q1        : 658.2130
  Q3        : 4578.1424
  IQR       : 3919.9293
  Outliers  : 12

Value (₹ crore) - Current Month
  Min       : 53.1790572563651
  Max       : 13403.7119572119
  Mean      : 3040.7789
  Median    : 1339.0832
  Q1        : 658.2130
  Q3        : 4886.5665
  IQR       : 4228.3535
  Outliers  : 10

Year
  Min       : 2025
  Max       : 2025
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

======================================================================
Part V - Domestic Frauds
======================================================================

Volume (Lakh)
  Min       : 1.53622
  Max       : 3.03
  Mean      : 2.2317
  Median    : 2.2916
  Q1        : 1.8676
  Q3        : 2.5353
  IQR       : 0.6677
  Outliers  : 0

Value (Crore)
  Min       : 194.9630324
  Max       : 545.043771202
  Mean      : 356.1197
  Median    : 344.8223
  Q1        : 285.9565
  Q3        : 428.4056
  IQR       : 142.4491
  Outliers  : 0

One in every X payment transaction fraudulent
  Min       : 47018.0027404792
  Max       : 121303.32789618
  Mean      : 73647.8521
  Median    : 70681.8117
  Q1        : 58391.7103
  Q3        : 83924.5813
  IQR       : 25532.8709
  Outliers  : 0

Report Year
  Min       : 2025.0
  Max       : 2025.0
  Mean      : 2025.0000
  Median    : 2025.0000
  Q1        : 2025.0000
  Q3        : 2025.0000
  IQR       : 0.0000
  Outliers  : 0

FTS (bps)
  Min       : 0.094
  Max       : 0.24
  Mean      : 0.1586
  Median    : 0.1550
  Q1        : 0.1290
  Q3        : 0.1770
  IQR       : 0.0480
  Outliers  : 0

In [30]:
for sheet, df in sheets_cleaned.items():
    if sheet == "Part V - Domestic Frauds":
        df["Report Year"] = df["Report Year"].astype("int64")
    elif "Year" in df.columns:
        df["Year"] = df["Year"].astype("int64")

In [31]:
for sheet, df in sheets_cleaned.items():
    print(sheet)

    if sheet == "Part V - Domestic Frauds":
        print(df["Report Year"].dtype)
    else:
        print(df["Year"].dtype)

Part I - Payment Indicators
int64
Part II - Modes & Channels
int64
Part III - Infrastructures
int64
Part IV - International
int64
Part V - Domestic Frauds
int64

In [32]:
# ============================================================
# FINAL DATA CLEANING VALIDATION
# ============================================================

for sheet, df in sheets_cleaned.items():

    print("\n" + "=" * 70)
    print(sheet)
    print("=" * 70)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    # Missing values
    print("Total missing values:", df.isna().sum().sum())

    # Duplicate rows
    print("Exact duplicate rows:", df.duplicated().sum())

    # Empty columns
    empty_cols = df.columns[df.isna().all()].tolist()
    print("Completely empty columns:", empty_cols)

    # Year validation
    if sheet == "Part V - Domestic Frauds":
        print("Report Year dtype:", df["Report Year"].dtype)
    else:
        print("Year dtype:", df["Year"].dtype)

======================================================================
Part I - Payment Indicators
======================================================================
Rows: 480
Columns: 16
Total missing values: 0
Exact duplicate rows: 0
Completely empty columns: []
Year dtype: int64

======================================================================
Part II - Modes & Channels
======================================================================
Rows: 180
Columns: 16
Total missing values: 0
Exact duplicate rows: 0
Completely empty columns: []
Year dtype: int64

======================================================================
Part III - Infrastructures
======================================================================
Rows: 156
Columns: 13
Total missing values: 0
Exact duplicate rows: 0
Completely empty columns: []
Year dtype: int64

======================================================================
Part IV - International
======================================================================
Rows: 180
Columns: 11
Total missing values: 0
Exact duplicate rows: 0
Completely empty columns: []
Year dtype: int64

======================================================================
Part V - Domestic Frauds
======================================================================
Rows: 414
Columns: 10
Total missing values: 0
Exact duplicate rows: 0
Completely empty columns: []
Report Year dtype: int64

In [33]:
# ============================================================
# SAVE CLEANED DATA
# ============================================================

output_file = "PSI_Cleaned.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    for sheet, df in sheets_cleaned.items():
        df.to_excel(writer, sheet_name=sheet[:31], index=False)

print("Cleaned dataset saved successfully as:", output_file)

Cleaned dataset saved successfully as: PSI_Cleaned.xlsx

In [34]:
import os

print("File exists:", os.path.exists(output_file))
print("File path:", os.path.abspath(output_file))

File exists: True
File path: C:\Users\THARUNI REDDY V\Downloads\analytics\PSI_Cleaned.xlsx